package QuickQuirkGameLab;

import java.awt.CardLayout;

public class ChemistryCourse extends javax.swing.JFrame {

    private int x;
    private int y;
    private String uname; // This needs to be passed on to the game
    private String fname;
    
    CardLayout cardlayout;
    CardLayout som;
    
    
    public ChemistryCourse() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        cardlayout = (CardLayout)(SelectedCourseCards.getLayout());
        SelectedCourseCards.add(Welcome, "Welcome");
        SelectedCourseCards.add(Lesson1, "Lesson1");
        cardlayout.show(SelectedCourseCards, "Welcome");
        
        som = (CardLayout)(Lesson1.getLayout());
        Lesson1.add(Gas, "Gas");
        Lesson1.add(Liquid, "Liquid");
        Lesson1.add(Solid, "Solid");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopupWindowTop = new javax.swing.JPanel();
        ClosePopup = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        CourseMainBody = new javax.swing.JSplitPane();
        CourseSelector = new javax.swing.JPanel();
        WelcomeButton = new javax.swing.JButton();
        Lesson1Button = new javax.swing.JButton();
        SelectedCourseCards = new javax.swing.JPanel();
        Welcome = new javax.swing.JPanel();
        AccessCoursesTitle = new javax.swing.JLabel();
        WelcomeMessage = new javax.swing.JLabel();
        Instruction = new javax.swing.JLabel();
        Design = new javax.swing.JLabel();
        Lesson1 = new javax.swing.JPanel();
        Gas = new javax.swing.JPanel();
        IceImage3 = new javax.swing.JLabel();
        SolidGraph2 = new javax.swing.JLabel();
        IntegersPanel8 = new javax.swing.JPanel();
        AdditionSubtitle19 = new javax.swing.JLabel();
        AdditionSubtitle23 = new javax.swing.JLabel();
        CondenseButton = new javax.swing.JButton();
        AccessCoursesTitle3 = new javax.swing.JLabel();
        Liquid = new javax.swing.JPanel();
        IceImage2 = new javax.swing.JLabel();
        SolidGraph1 = new javax.swing.JLabel();
        IntegersPanel7 = new javax.swing.JPanel();
        AdditionSubtitle18 = new javax.swing.JLabel();
        AdditionSubtitle22 = new javax.swing.JLabel();
        FreezeButton = new javax.swing.JButton();
        EvaporateButton = new javax.swing.JButton();
        AccessCoursesTitle2 = new javax.swing.JLabel();
        Solid = new javax.swing.JPanel();
        MeltButton = new javax.swing.JButton();
        SolidGraph = new javax.swing.JLabel();
        IceImage1 = new javax.swing.JLabel();
        IntegersPanel6 = new javax.swing.JPanel();
        AdditionSubtitle17 = new javax.swing.JLabel();
        AdditionSubtitle21 = new javax.swing.JLabel();
        AccessCoursesTitle1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);

        PopupWindowTop.setBackground(new java.awt.Color(85, 143, 127));
        PopupWindowTop.setForeground(new java.awt.Color(85, 143, 127));
        PopupWindowTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PopupWindowTopMouseDragged(evt);
            }
        });
        PopupWindowTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PopupWindowTopMousePressed(evt);
            }
        });

        ClosePopup.setBackground(new java.awt.Color(242, 0, 0));
        ClosePopup.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        ClosePopup.setForeground(new java.awt.Color(255, 255, 255));
        ClosePopup.setText("x");
        ClosePopup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ClosePopupMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout PopupWindowTopLayout = new javax.swing.GroupLayout(PopupWindowTop);
        PopupWindowTop.setLayout(PopupWindowTopLayout);
        PopupWindowTopLayout.setHorizontalGroup(
            PopupWindowTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PopupWindowTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ClosePopup)
                .addGap(16, 16, 16))
        );
        PopupWindowTopLayout.setVerticalGroup(
            PopupWindowTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopupWindowTopLayout.createSequentialGroup()
                .addComponent(ClosePopup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        Background.setBackground(new java.awt.Color(230, 241, 231));

        CourseMainBody.setDividerLocation(-10);
        CourseMainBody.setDividerSize(0);

        CourseSelector.setBackground(new java.awt.Color(27, 47, 51));
        CourseSelector.setMaximumSize(new java.awt.Dimension(200, 538));
        CourseSelector.setMinimumSize(new java.awt.Dimension(200, 538));
        CourseSelector.setPreferredSize(new java.awt.Dimension(200, 538));

        WelcomeButton.setBackground(new java.awt.Color(84, 129, 118));
        WelcomeButton.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        WelcomeButton.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeButton.setText("Welcome to Chemistry!");
        WelcomeButton.setBorder(null);
        WelcomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WelcomeButtonActionPerformed(evt);
            }
        });

        Lesson1Button.setBackground(new java.awt.Color(84, 129, 118));
        Lesson1Button.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        Lesson1Button.setForeground(new java.awt.Color(255, 255, 255));
        Lesson1Button.setText("States of Matter");
        Lesson1Button.setBorder(null);
        Lesson1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson1ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CourseSelectorLayout = new javax.swing.GroupLayout(CourseSelector);
        CourseSelector.setLayout(CourseSelectorLayout);
        CourseSelectorLayout.setHorizontalGroup(
            CourseSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CourseSelectorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(CourseSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lesson1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WelcomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        CourseSelectorLayout.setVerticalGroup(
            CourseSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CourseSelectorLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(WelcomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lesson1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        CourseMainBody.setLeftComponent(CourseSelector);

        SelectedCourseCards.setBackground(new java.awt.Color(230, 241, 231));
        SelectedCourseCards.setLayout(new java.awt.CardLayout());

        Welcome.setBackground(new java.awt.Color(230, 241, 231));
        Welcome.setMaximumSize(new java.awt.Dimension(600, 538));
        Welcome.setMinimumSize(new java.awt.Dimension(600, 538));
        Welcome.setPreferredSize(new java.awt.Dimension(600, 538));

        AccessCoursesTitle.setFont(new java.awt.Font("Fredoka Medium", 1, 24)); // NOI18N
        AccessCoursesTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessCoursesTitle.setText("Welcome to the lab of wonders!");

        WelcomeMessage.setBackground(new java.awt.Color(235, 246, 236));
        WelcomeMessage.setFont(new java.awt.Font("Fredoka", 0, 18)); // NOI18N
        WelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeMessage.setText("<html><center>Here you'll learn how matter changes, what everything is made of, and how cool experiments explain the world around us.<br>Let’s break down molecules and stir up some science fun!</center></html>");

        Instruction.setBackground(new java.awt.Color(235, 246, 236));
        Instruction.setFont(new java.awt.Font("Fredoka", 0, 18)); // NOI18N
        Instruction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Instruction.setText("<html><center>Cick on a course on the left to start learning!</center></html>");

        Design.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DesignMath1.png"))); // NOI18N

        javax.swing.GroupLayout WelcomeLayout = new javax.swing.GroupLayout(Welcome);
        Welcome.setLayout(WelcomeLayout);
        WelcomeLayout.setHorizontalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccessCoursesTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
            .addComponent(WelcomeMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(Design, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Instruction)
                .addContainerGap())
        );
        WelcomeLayout.setVerticalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(AccessCoursesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Instruction, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Design, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SelectedCourseCards.add(Welcome, "card2");

        Lesson1.setBackground(new java.awt.Color(230, 241, 231));
        Lesson1.setLayout(new java.awt.CardLayout());

        Gas.setBackground(new java.awt.Color(230, 241, 231));
        Gas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IceImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Steam.png"))); // NOI18N
        Gas.add(IceImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 152, 150));

        SolidGraph2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Gas.png"))); // NOI18N
        Gas.add(SolidGraph2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 152, 150));

        IntegersPanel8.setBackground(new java.awt.Color(255, 255, 255));
        IntegersPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle19.setFont(new java.awt.Font("Fredoka", 1, 18)); // NOI18N
        AdditionSubtitle19.setText("Gas!");
        IntegersPanel8.add(AdditionSubtitle19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 30));

        AdditionSubtitle23.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle23.setText("<html>They are materials that float, with particles that stay far away from one another!<br><br>- Example: Steam!</html>");
        IntegersPanel8.add(AdditionSubtitle23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 150));

        Gas.add(IntegersPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 220, 210));

        CondenseButton.setBackground(new java.awt.Color(204, 255, 255));
        CondenseButton.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        CondenseButton.setText("<html><center>Cool the gas!<br><b>(Condensing)</b></center></html>");
        CondenseButton.setBorder(null);
        CondenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CondenseButtonActionPerformed(evt);
            }
        });
        Gas.add(CondenseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 160, 60));

        AccessCoursesTitle3.setFont(new java.awt.Font("Fredoka Medium", 1, 24)); // NOI18N
        AccessCoursesTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessCoursesTitle3.setText("State of Matter");
        Gas.add(AccessCoursesTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, -1));

        Lesson1.add(Gas, "card2");

        Liquid.setBackground(new java.awt.Color(230, 241, 231));
        Liquid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IceImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Water.png"))); // NOI18N
        Liquid.add(IceImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 152, 150));

        SolidGraph1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Liquid.png"))); // NOI18N
        Liquid.add(SolidGraph1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 152, 150));

        IntegersPanel7.setBackground(new java.awt.Color(255, 255, 255));
        IntegersPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle18.setFont(new java.awt.Font("Fredoka", 1, 18)); // NOI18N
        AdditionSubtitle18.setText("Liquid!");
        IntegersPanel7.add(AdditionSubtitle18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 30));

        AdditionSubtitle22.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle22.setText("<html>They are materials that flow, with particles that slide around one another!<br><br>- Example: Water!</html>");
        IntegersPanel7.add(AdditionSubtitle22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 150));

        Liquid.add(IntegersPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 220, 210));

        FreezeButton.setBackground(new java.awt.Color(204, 255, 255));
        FreezeButton.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        FreezeButton.setText("<html><center>Cool the liquid!<br><b>(Freezing)</b></center></html>");
        FreezeButton.setBorder(null);
        FreezeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FreezeButtonActionPerformed(evt);
            }
        });
        Liquid.add(FreezeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 160, 60));

        EvaporateButton.setBackground(new java.awt.Color(255, 153, 0));
        EvaporateButton.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        EvaporateButton.setText("<html><center>Heat the liquid!<br><b>(Evaporating)</b></center></html>");
        EvaporateButton.setBorder(null);
        EvaporateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvaporateButtonActionPerformed(evt);
            }
        });
        Liquid.add(EvaporateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 160, 60));

        AccessCoursesTitle2.setFont(new java.awt.Font("Fredoka Medium", 1, 24)); // NOI18N
        AccessCoursesTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessCoursesTitle2.setText("State of Matter");
        Liquid.add(AccessCoursesTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, -1));

        Lesson1.add(Liquid, "card2");

        Solid.setBackground(new java.awt.Color(230, 241, 231));
        Solid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MeltButton.setBackground(new java.awt.Color(255, 153, 0));
        MeltButton.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        MeltButton.setText("<html><center>Heat the solid!<br><b>(Melting)</b></center></html>");
        MeltButton.setBorder(null);
        MeltButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeltButtonActionPerformed(evt);
            }
        });
        Solid.add(MeltButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 160, 60));

        SolidGraph.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Solid.png"))); // NOI18N
        Solid.add(SolidGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 152, 150));

        IceImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IceCubes.png"))); // NOI18N
        Solid.add(IceImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 152, 150));

        IntegersPanel6.setBackground(new java.awt.Color(255, 255, 255));
        IntegersPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle17.setFont(new java.awt.Font("Fredoka", 1, 18)); // NOI18N
        AdditionSubtitle17.setText("Solid!");
        IntegersPanel6.add(AdditionSubtitle17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 30));

        AdditionSubtitle21.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle21.setText("<html>They are materials that are hard, with particles tightly packed together!<br><br>- Example: Ice Cubes!</html>");
        IntegersPanel6.add(AdditionSubtitle21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 150));

        Solid.add(IntegersPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 220, 210));

        AccessCoursesTitle1.setFont(new java.awt.Font("Fredoka Medium", 1, 24)); // NOI18N
        AccessCoursesTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessCoursesTitle1.setText("State of Matter");
        Solid.add(AccessCoursesTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, -1));

        Lesson1.add(Solid, "card2");

        SelectedCourseCards.add(Lesson1, "card3");

        CourseMainBody.setRightComponent(SelectedCourseCards);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CourseMainBody)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CourseMainBody)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PopupWindowTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PopupWindowTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClosePopupMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosePopupMouseReleased
        this.dispose();
    }//GEN-LAST:event_ClosePopupMouseReleased

    private void PopupWindowTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopupWindowTopMouseDragged
        // Moves application based on cursor location
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();

        this.setLocation(x1- x, y1 - y);
    }//GEN-LAST:event_PopupWindowTopMouseDragged

    private void PopupWindowTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopupWindowTopMousePressed
        // Get current cursor location upon clicking Top
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_PopupWindowTopMousePressed

    private void WelcomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WelcomeButtonActionPerformed
        cardlayout.show(SelectedCourseCards, "Welcome");
        System.out.println("Panel Changed to Welcome");
    }//GEN-LAST:event_WelcomeButtonActionPerformed

    private void Lesson1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson1ButtonActionPerformed
        cardlayout.show(SelectedCourseCards, "Lesson1");
        som.show(Lesson1,"Solid");
        System.out.println("Panel Changed to L1");
    }//GEN-LAST:event_Lesson1ButtonActionPerformed

    private void MeltButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeltButtonActionPerformed
        som.show(Lesson1,"Liquid");
    }//GEN-LAST:event_MeltButtonActionPerformed

    private void FreezeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FreezeButtonActionPerformed
        som.show(Lesson1,"Solid");
    }//GEN-LAST:event_FreezeButtonActionPerformed

    private void EvaporateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvaporateButtonActionPerformed
        som.show(Lesson1,"Gas");
    }//GEN-LAST:event_EvaporateButtonActionPerformed

    private void CondenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CondenseButtonActionPerformed
        som.show(Lesson1,"Liquid");
    }//GEN-LAST:event_CondenseButtonActionPerformed

    public void setname(String uname, String fname){
        this.uname = uname;
        this.fname = fname;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChemistryCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChemistryCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChemistryCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChemistryCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChemistryCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccessCoursesTitle;
    private javax.swing.JLabel AccessCoursesTitle1;
    private javax.swing.JLabel AccessCoursesTitle2;
    private javax.swing.JLabel AccessCoursesTitle3;
    private javax.swing.JLabel AdditionSubtitle17;
    private javax.swing.JLabel AdditionSubtitle18;
    private javax.swing.JLabel AdditionSubtitle19;
    private javax.swing.JLabel AdditionSubtitle21;
    private javax.swing.JLabel AdditionSubtitle22;
    private javax.swing.JLabel AdditionSubtitle23;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel ClosePopup;
    private javax.swing.JButton CondenseButton;
    private javax.swing.JSplitPane CourseMainBody;
    private javax.swing.JPanel CourseSelector;
    private javax.swing.JLabel Design;
    private javax.swing.JButton EvaporateButton;
    private javax.swing.JButton FreezeButton;
    private javax.swing.JPanel Gas;
    private javax.swing.JLabel IceImage1;
    private javax.swing.JLabel IceImage2;
    private javax.swing.JLabel IceImage3;
    private javax.swing.JLabel Instruction;
    private javax.swing.JPanel IntegersPanel6;
    private javax.swing.JPanel IntegersPanel7;
    private javax.swing.JPanel IntegersPanel8;
    private javax.swing.JPanel Lesson1;
    private javax.swing.JButton Lesson1Button;
    private javax.swing.JPanel Liquid;
    private javax.swing.JButton MeltButton;
    private javax.swing.JPanel PopupWindowTop;
    private javax.swing.JPanel SelectedCourseCards;
    private javax.swing.JPanel Solid;
    private javax.swing.JLabel SolidGraph;
    private javax.swing.JLabel SolidGraph1;
    private javax.swing.JLabel SolidGraph2;
    private javax.swing.JPanel Welcome;
    private javax.swing.JButton WelcomeButton;
    private javax.swing.JLabel WelcomeMessage;
    // End of variables declaration//GEN-END:variables
}
