package QuickQuirkGameLab;

import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.ImageIcon;

public class EditProfileLearner extends javax.swing.JFrame {

    private int x; // Needed to make application draggable
    private int y; // Needed to make application draggable
    
    private String fname;
    private String email;
    private String uname;
    private String pass;
    private String icon;
    private String iconPath;
    private boolean chemistryUnlocked = false;
    private boolean physicsUnlocked = false;
    private boolean mathsUnlocked = false;
    private boolean planetUnlocked = false;
    
    CardLayout cardLayout;
    
    public EditProfileLearner() {
        initComponents();
        this.setLocationRelativeTo(null); // Puts the application in the center
        
        cardLayout = (CardLayout)(EPPanelCards.getLayout());
        EPPanelCards.add(EditDetailsPanel, "EditDetailsPanel");
        EPPanelCards.add(EditIconPanel, "EditIconPanel");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProfileEditTop = new javax.swing.JPanel();
        ClosePopup = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        EPMainBody = new javax.swing.JSplitPane();
        EditProfileControlSide = new javax.swing.JPanel();
        EditDetailButton = new javax.swing.JButton();
        EditIconButton = new javax.swing.JButton();
        EPProfileIcon = new javax.swing.JLabel();
        CurrentLoginUsername = new javax.swing.JTextField();
        CurrentLoginName = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        EPPanelCards = new javax.swing.JPanel();
        EditDetailsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EPFnameLabel = new javax.swing.JLabel();
        EPFnameInput = new javax.swing.JTextField();
        EPEmailLabel = new javax.swing.JLabel();
        EPEmailInput = new javax.swing.JTextField();
        EPPassLabel = new javax.swing.JLabel();
        EPUnameLabel = new javax.swing.JLabel();
        EPUnameInput = new javax.swing.JTextField();
        EPPassInput = new javax.swing.JTextField();
        EditIconPanel = new javax.swing.JPanel();
        SetIcon = new javax.swing.JLabel();
        DefaultIcon1 = new javax.swing.JLabel();
        ChemistryIconSelect = new javax.swing.JLabel();
        DefaultIcon2 = new javax.swing.JLabel();
        PhysicsIconSelect = new javax.swing.JLabel();
        MathsIconSelect = new javax.swing.JLabel();
        PlanetIconSelect = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DefIcon1Label = new javax.swing.JLabel();
        DefIcon2Label = new javax.swing.JLabel();
        ChemistryIconLabel = new javax.swing.JLabel();
        PlanetIconLabel = new javax.swing.JLabel();
        MathsIconLabel = new javax.swing.JLabel();
        PhysicsIconLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ProfileEditTop.setBackground(new java.awt.Color(85, 143, 127));
        ProfileEditTop.setForeground(new java.awt.Color(85, 143, 127));
        ProfileEditTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ProfileEditTopMouseDragged(evt);
            }
        });
        ProfileEditTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProfileEditTopMousePressed(evt);
            }
        });

        ClosePopup.setBackground(new java.awt.Color(242, 0, 0));
        ClosePopup.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        ClosePopup.setForeground(new java.awt.Color(255, 255, 255));
        ClosePopup.setText("x");
        ClosePopup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ClosePopupMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout ProfileEditTopLayout = new javax.swing.GroupLayout(ProfileEditTop);
        ProfileEditTop.setLayout(ProfileEditTopLayout);
        ProfileEditTopLayout.setHorizontalGroup(
            ProfileEditTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileEditTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ClosePopup)
                .addGap(16, 16, 16))
        );
        ProfileEditTopLayout.setVerticalGroup(
            ProfileEditTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileEditTopLayout.createSequentialGroup()
                .addComponent(ClosePopup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        Background.setBackground(new java.awt.Color(27, 47, 51));
        Background.setPreferredSize(new java.awt.Dimension(672, 474));

        EPMainBody.setDividerSize(0);
        EPMainBody.setPreferredSize(new java.awt.Dimension(672, 554));

        EditProfileControlSide.setBackground(new java.awt.Color(30, 57, 62));

        EditDetailButton.setBackground(new java.awt.Color(84, 129, 118));
        EditDetailButton.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        EditDetailButton.setForeground(new java.awt.Color(255, 255, 255));
        EditDetailButton.setText("Edit Details");
        EditDetailButton.setBorder(null);
        EditDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditDetailButtonActionPerformed(evt);
            }
        });

        EditIconButton.setBackground(new java.awt.Color(84, 129, 118));
        EditIconButton.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        EditIconButton.setForeground(new java.awt.Color(255, 255, 255));
        EditIconButton.setText("Edit Icon");
        EditIconButton.setBorder(null);
        EditIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditIconButtonActionPerformed(evt);
            }
        });

        EPProfileIcon.setBackground(new java.awt.Color(30, 57, 62));
        EPProfileIcon.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        EPProfileIcon.setForeground(new java.awt.Color(255, 255, 255));
        EPProfileIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EPProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DefaultIcon1.png"))); // NOI18N
        EPProfileIcon.setText("\n");
        EPProfileIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        CurrentLoginUsername.setEditable(false);
        CurrentLoginUsername.setBackground(new java.awt.Color(30, 57, 62));
        CurrentLoginUsername.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        CurrentLoginUsername.setForeground(new java.awt.Color(255, 255, 255));
        CurrentLoginUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CurrentLoginUsername.setText("TestUser");
        CurrentLoginUsername.setBorder(null);

        CurrentLoginName.setEditable(false);
        CurrentLoginName.setBackground(new java.awt.Color(30, 57, 62));
        CurrentLoginName.setFont(new java.awt.Font("Bahnschrift", 0, 17)); // NOI18N
        CurrentLoginName.setForeground(new java.awt.Color(255, 255, 255));
        CurrentLoginName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CurrentLoginName.setText("Test User");
        CurrentLoginName.setBorder(null);

        SaveButton.setBackground(new java.awt.Color(95, 146, 133));
        SaveButton.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("Save");
        SaveButton.setBorder(null);
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditProfileControlSideLayout = new javax.swing.GroupLayout(EditProfileControlSide);
        EditProfileControlSide.setLayout(EditProfileControlSideLayout);
        EditProfileControlSideLayout.setHorizontalGroup(
            EditProfileControlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditProfileControlSideLayout.createSequentialGroup()
                .addGroup(EditProfileControlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditProfileControlSideLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EditProfileControlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CurrentLoginName)
                            .addComponent(EPProfileIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CurrentLoginUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(EditProfileControlSideLayout.createSequentialGroup()
                        .addGroup(EditProfileControlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditProfileControlSideLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(EditProfileControlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EditIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditDetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EditProfileControlSideLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        EditProfileControlSideLayout.setVerticalGroup(
            EditProfileControlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditProfileControlSideLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(EPProfileIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CurrentLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(CurrentLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(EditDetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        EPMainBody.setLeftComponent(EditProfileControlSide);

        EPPanelCards.setBackground(new java.awt.Color(25, 47, 51));
        EPPanelCards.setLayout(new java.awt.CardLayout());

        EditDetailsPanel.setBackground(new java.awt.Color(25, 47, 51));
        EditDetailsPanel.setPreferredSize(new java.awt.Dimension(534, 554));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Details");

        EPFnameLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        EPFnameLabel.setForeground(new java.awt.Color(242, 242, 242));
        EPFnameLabel.setText("Full Name");

        EPFnameInput.setBackground(new java.awt.Color(74, 126, 112));
        EPFnameInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        EPFnameInput.setForeground(new java.awt.Color(255, 255, 255));
        EPFnameInput.setBorder(null);

        EPEmailLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        EPEmailLabel.setForeground(new java.awt.Color(242, 242, 242));
        EPEmailLabel.setText("Email");

        EPEmailInput.setBackground(new java.awt.Color(74, 126, 112));
        EPEmailInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        EPEmailInput.setForeground(new java.awt.Color(255, 255, 255));
        EPEmailInput.setBorder(null);

        EPPassLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        EPPassLabel.setForeground(new java.awt.Color(242, 242, 242));
        EPPassLabel.setText("Password");

        EPUnameLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        EPUnameLabel.setForeground(new java.awt.Color(242, 242, 242));
        EPUnameLabel.setText("Username");

        EPUnameInput.setEditable(false);
        EPUnameInput.setBackground(new java.awt.Color(83, 105, 99));
        EPUnameInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        EPUnameInput.setForeground(new java.awt.Color(204, 204, 204));
        EPUnameInput.setBorder(null);

        EPPassInput.setBackground(new java.awt.Color(74, 126, 112));
        EPPassInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        EPPassInput.setForeground(new java.awt.Color(255, 255, 255));
        EPPassInput.setBorder(null);

        javax.swing.GroupLayout EditDetailsPanelLayout = new javax.swing.GroupLayout(EditDetailsPanel);
        EditDetailsPanel.setLayout(EditDetailsPanelLayout);
        EditDetailsPanelLayout.setHorizontalGroup(
            EditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditDetailsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditDetailsPanelLayout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addGroup(EditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EPPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EPPassInput, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EPUnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EPUnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EPEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EPEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EPFnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EPFnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))))
        );
        EditDetailsPanelLayout.setVerticalGroup(
            EditDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditDetailsPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(EPFnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EPFnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EPEmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EPEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EPUnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EPUnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EPPassLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EPPassInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        EPPanelCards.add(EditDetailsPanel, "card3");

        EditIconPanel.setBackground(new java.awt.Color(25, 47, 51));
        EditIconPanel.setMaximumSize(new java.awt.Dimension(534, 554));
        EditIconPanel.setMinimumSize(new java.awt.Dimension(534, 554));
        EditIconPanel.setPreferredSize(new java.awt.Dimension(534, 554));

        SetIcon.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        SetIcon.setForeground(new java.awt.Color(242, 242, 242));
        SetIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SetIcon.setText("Set Icon");

        DefaultIcon1.setForeground(new java.awt.Color(255, 255, 255));
        DefaultIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DefaultIcon1.png"))); // NOI18N
        DefaultIcon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DefaultIcon1MouseClicked(evt);
            }
        });

        ChemistryIconSelect.setForeground(new java.awt.Color(255, 255, 255));
        ChemistryIconSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ChemistryIconLocked.png"))); // NOI18N
        ChemistryIconSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChemistryIconSelectMouseClicked(evt);
            }
        });

        DefaultIcon2.setForeground(new java.awt.Color(255, 255, 255));
        DefaultIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DefaultIcon2.png"))); // NOI18N
        DefaultIcon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DefaultIcon2MouseClicked(evt);
            }
        });

        PhysicsIconSelect.setForeground(new java.awt.Color(255, 255, 255));
        PhysicsIconSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PhysicsIconLocked.png"))); // NOI18N
        PhysicsIconSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhysicsIconSelectMouseClicked(evt);
            }
        });

        MathsIconSelect.setForeground(new java.awt.Color(255, 255, 255));
        MathsIconSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MathsIconLocked.png"))); // NOI18N
        MathsIconSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MathsIconSelectMouseClicked(evt);
            }
        });

        PlanetIconSelect.setForeground(new java.awt.Color(255, 255, 255));
        PlanetIconSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PlanetIconLocked.png"))); // NOI18N
        PlanetIconSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlanetIconSelectMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Click on a photo to set your new profile picture!");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DefIcon1Label.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        DefIcon1Label.setForeground(new java.awt.Color(255, 255, 255));
        DefIcon1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DefIcon1Label.setText("Default Icon 1");

        DefIcon2Label.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        DefIcon2Label.setForeground(new java.awt.Color(255, 255, 255));
        DefIcon2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DefIcon2Label.setText("Default Icon 2");

        ChemistryIconLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ChemistryIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        ChemistryIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChemistryIconLabel.setText("Locked!");

        PlanetIconLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        PlanetIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        PlanetIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlanetIconLabel.setText("Locked!");

        MathsIconLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        MathsIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        MathsIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MathsIconLabel.setText("Locked!");

        PhysicsIconLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        PhysicsIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        PhysicsIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PhysicsIconLabel.setText("Locked!");

        javax.swing.GroupLayout EditIconPanelLayout = new javax.swing.GroupLayout(EditIconPanel);
        EditIconPanel.setLayout(EditIconPanelLayout);
        EditIconPanelLayout.setHorizontalGroup(
            EditIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditIconPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(EditIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditIconPanelLayout.createSequentialGroup()
                        .addComponent(PhysicsIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(MathsIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(PlanetIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SetIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DefaultIcon1)
                    .addGroup(EditIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EditIconPanelLayout.createSequentialGroup()
                            .addGroup(EditIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PhysicsIconSelect)
                                .addComponent(DefIcon1Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(64, 64, 64)
                            .addGroup(EditIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(MathsIconSelect)
                                .addComponent(DefaultIcon2)
                                .addComponent(DefIcon2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(64, 64, 64)
                            .addGroup(EditIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ChemistryIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ChemistryIconSelect)
                                .addComponent(PlanetIconSelect)))))
                .addGap(48, 48, 48))
        );
        EditIconPanelLayout.setVerticalGroup(
            EditIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditIconPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(SetIcon)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(EditIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DefaultIcon1)
                    .addComponent(ChemistryIconSelect, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DefaultIcon2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DefIcon1Label)
                    .addComponent(DefIcon2Label)
                    .addComponent(ChemistryIconLabel))
                .addGap(32, 32, 32)
                .addGroup(EditIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PhysicsIconSelect, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MathsIconSelect)
                    .addComponent(PlanetIconSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhysicsIconLabel)
                    .addComponent(MathsIconLabel)
                    .addComponent(PlanetIconLabel))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        EPPanelCards.add(EditIconPanel, "card3");

        EPMainBody.setRightComponent(EPPanelCards);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EPMainBody, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EPMainBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProfileEditTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ProfileEditTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClosePopupMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosePopupMouseReleased
        this.dispose();
    }//GEN-LAST:event_ClosePopupMouseReleased

    private void ProfileEditTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileEditTopMouseDragged
        // Moves application based on cursor location
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();

        this.setLocation(x1- x, y1 - y);
    }//GEN-LAST:event_ProfileEditTopMouseDragged

    private void ProfileEditTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileEditTopMousePressed
        // Get current cursor location upon clicking Top
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_ProfileEditTopMousePressed

    private void EditDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDetailButtonActionPerformed
        cardLayout.show(EPPanelCards,"EditDetailsPanel");
        System.out.println("Panel Changed to Edit Detail");
    }//GEN-LAST:event_EditDetailButtonActionPerformed

    private void EditIconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditIconButtonActionPerformed
        cardLayout.show(EPPanelCards,"EditIconPanel");
        System.out.println("Panel Changed to Edit Icon");
    }//GEN-LAST:event_EditIconButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        File filePath = new File("Learner/" + this.uname + "/accountDetails.csv");
        File tempFilePath = new File ("Learner/" + this.uname + "/temp.csv");

        // New values
        this.fname = EPFnameInput.getText();
        this.email = EPEmailInput.getText();
        this.pass = EPPassInput.getText();
        

        // Updates the account file
        try {
            BufferedReader reader = new BufferedReader(new FileReader(filePath));
            BufferedWriter writer = new BufferedWriter(new FileWriter(tempFilePath));

            String line;
            int lineNumber = 0;

            while ((line = reader.readLine()) != null) {
                switch (lineNumber) {
                    case 0: writer.write(this.fname); break; // Replace fname
                    case 2: writer.write(this.pass); break; // Replace pass
                    case 3: writer.write(this.email); break;// Replace email
                    case 5: writer.write(this.icon); break; // Replaces icon (after choosing it)
                    default: writer.write(line); break;    // Keep original
                }
                writer.newLine();
                lineNumber++;
            }

            reader.close();
            writer.close();

            if (filePath.delete()) {
                if (tempFilePath.renameTo(filePath)) {
                    System.out.println("Updated successfully!"); // Debug
                } else {
                    System.out.println(" Couldn't rename temp file."); // Debug
                }
            } else {
                System.out.println("Couldn't delete original file."); // Debug
            }

        } catch (IOException e) {
            e.printStackTrace();
        }

        // Updates the master file
        String masterFileUpdate = "usermasterlist.csv";
        try {
            File inputFile = new File(masterFileUpdate);
            File tempFile = new File("temp.csv");

            BufferedReader reader = new BufferedReader(new FileReader(inputFile));
            BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile));

            String line;
            while ((line = reader.readLine()) != null) {
                String[] columns = line.split(",");

                if (columns[1].equals(this.uname)) {
                    columns[0] = this.fname;
                    columns[2] = this.pass;
                    columns[3] = this.email;
                }

                writer.write(String.join(",", columns));
                writer.newLine();
            }

            reader.close();
            writer.close();

            // Replace original file with the updated file
            if (inputFile.delete()) {
                tempFile.renameTo(inputFile);
            }

            System.out.println("Master file Update complete");

        } catch (IOException e) {
            e.printStackTrace();
        }

        // Create a new pop up message
        PopupWindow updateSuccess = new PopupWindow();
        updateSuccess.setVisible(true);
        updateSuccess.setMessages("Update Sucessful!","Please log in again to see your changes");
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void DefaultIcon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DefaultIcon1MouseClicked
        setIcon("DefaultIcon1");
    }//GEN-LAST:event_DefaultIcon1MouseClicked

    private void DefaultIcon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DefaultIcon2MouseClicked
        setIcon("DefaultIcon2");
    }//GEN-LAST:event_DefaultIcon2MouseClicked

    private void ChemistryIconSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChemistryIconSelectMouseClicked
        if (chemistryUnlocked == false){
            locked();
        } else {
            setIcon("ChemistryIcon");
        }
    }//GEN-LAST:event_ChemistryIconSelectMouseClicked

    private void PhysicsIconSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhysicsIconSelectMouseClicked
        if (physicsUnlocked == false){
            locked();
        } else {
            setIcon("PhysicsIcon");
        }
    }//GEN-LAST:event_PhysicsIconSelectMouseClicked

    private void MathsIconSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MathsIconSelectMouseClicked
        if (mathsUnlocked == false){
            locked();
        } else {
            setIcon("MathsIcon");
        }
    }//GEN-LAST:event_MathsIconSelectMouseClicked

    private void PlanetIconSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlanetIconSelectMouseClicked
        if (planetUnlocked == false){
            locked();
        } else {
            setIcon("PlanetIcon");
        }
    }//GEN-LAST:event_PlanetIconSelectMouseClicked

    public void setTempProfile(String fname, String email, String uname, String pass, String icon){
        this.fname = fname;
        this.email = email;
        this.uname = uname;
        this.pass = pass;
        this.icon = icon;   // This sets the name of the icon
        this.iconPath = "src/img/" + icon + ".png";
        
        System.out.println("\n Display current editing username: " + this.uname);
        
        //Display Profile
        displayTempProfile(this.fname, this.email, this.uname, this.pass, this.icon);
    }
    
    private void displayTempProfile(String fname, String email, String uname, String pass, String icon){
        EPFnameInput.setText(fname);
        EPEmailInput.setText(email);
        EPUnameInput.setText(uname);
        EPPassInput.setText(pass);
        EPProfileIcon.setIcon(new ImageIcon(this.iconPath));
        
        CurrentLoginUsername.setText(uname);
        CurrentLoginName.setText(fname);
        
        this.unlockIcon();
    }
    
    private void unlockIcon(){
        try {
            BufferedReader reader = new BufferedReader(new FileReader("Learner/" + this.uname + "/inventory.csv"));
            String line;

            while ((line = reader.readLine()) != null) {
                // Optional: trim to avoid accidental whitespace
                line = line.trim();

                if (line.equals("ChemistryIcon")) {
                    chemistryUnlocked = true;
                } else if (line.equals("PhysicsIcon")) {
                    physicsUnlocked = true;
                } else if (line.equals("MathsIcon")) {
                    mathsUnlocked = true;
                } else if (line.equals("PlanetIcon")) {
                    planetUnlocked = true;
                }
            }

            reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        // Displays the icons in the edit icon menu
        if (chemistryUnlocked == true) {
            ChemistryIconSelect.setIcon(new ImageIcon("src/img/ChemistryIcon.png"));
            ChemistryIconLabel.setText("Chemisty Icon");
        }
        if (physicsUnlocked == true) {
            PhysicsIconSelect.setIcon(new ImageIcon("src/img/PhysicsIcon.png"));
            PhysicsIconLabel.setText("Physics Icon");
        }
        if (mathsUnlocked == true) {
            MathsIconSelect.setIcon(new ImageIcon("src/img/MathsIcon.png"));
            MathsIconLabel.setText("Maths Icon");
        }
        if (planetUnlocked == true) {
            PlanetIconSelect.setIcon(new ImageIcon("src/img/PlanetIcon.png"));
            PlanetIconLabel.setText("Planet Icon");
        }
    }
    
    private void setIcon(String icon){
        String path = "src/img/" + icon + ".png";
        EPProfileIcon.setIcon(new ImageIcon(path));
        this.icon = icon;
        this.iconPath = path;
    }
    
    // This method is used to tell the user that the item is locked
    private void locked(){
        PopupWindow locked = new PopupWindow();
        locked.setVisible(true);
        locked.setMessages("This item is locked!","Purchase this item from the shop!");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfileLearner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfileLearner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfileLearner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfileLearner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfileLearner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel ChemistryIconLabel;
    private javax.swing.JLabel ChemistryIconSelect;
    private javax.swing.JLabel ClosePopup;
    private javax.swing.JTextField CurrentLoginName;
    private javax.swing.JTextField CurrentLoginUsername;
    private javax.swing.JLabel DefIcon1Label;
    private javax.swing.JLabel DefIcon2Label;
    private javax.swing.JLabel DefaultIcon1;
    private javax.swing.JLabel DefaultIcon2;
    private javax.swing.JTextField EPEmailInput;
    private javax.swing.JLabel EPEmailLabel;
    private javax.swing.JTextField EPFnameInput;
    private javax.swing.JLabel EPFnameLabel;
    private javax.swing.JSplitPane EPMainBody;
    private javax.swing.JPanel EPPanelCards;
    private javax.swing.JTextField EPPassInput;
    private javax.swing.JLabel EPPassLabel;
    private javax.swing.JLabel EPProfileIcon;
    private javax.swing.JTextField EPUnameInput;
    private javax.swing.JLabel EPUnameLabel;
    private javax.swing.JButton EditDetailButton;
    private javax.swing.JPanel EditDetailsPanel;
    private javax.swing.JButton EditIconButton;
    private javax.swing.JPanel EditIconPanel;
    private javax.swing.JPanel EditProfileControlSide;
    private javax.swing.JLabel MathsIconLabel;
    private javax.swing.JLabel MathsIconSelect;
    private javax.swing.JLabel PhysicsIconLabel;
    private javax.swing.JLabel PhysicsIconSelect;
    private javax.swing.JLabel PlanetIconLabel;
    private javax.swing.JLabel PlanetIconSelect;
    private javax.swing.JPanel ProfileEditTop;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel SetIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
