package QuickQuirkGameLab;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import javax.swing.table.DefaultTableModel;

public class EnglishGame extends javax.swing.JFrame {

    private String uname;
    private String fname;
    private int rank;
    
    // User input for game

    private String corrAns; // Correct answer of the question
    
    // Scoring
    int score = 0, corrAnsCount = 0, wroAnsCount = 0;
    int coins;
    String strscore, strcorrAnsCount, strwroAnsCount, strcoins;
    
    // Question Counting
    int questioncount = 0;
    
    // User Answer
    String inputAnswer;
        
    
    CardLayout cardlayout;
    
    public EnglishGame() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        cardlayout = (CardLayout)(GamePanelCards.getLayout());
        GamePanelCards.add(Instruction, "Instruction");
        GamePanelCards.add(MainGame, "MainGame");
        GamePanelCards.add(GameEnd, "GameEnd");
        GamePanelCards.add(LeaderboardPanel, "LeaderboardPanelFromInstruction");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GamePanelCards = new javax.swing.JPanel();
        MainGame = new javax.swing.JPanel();
        GamePanelDefinition = new javax.swing.JPanel();
        DefinitionOutput = new javax.swing.JLabel();
        AnsCorrCount = new javax.swing.JLabel();
        AnsCorrect = new javax.swing.JLabel();
        AnsWrong = new javax.swing.JLabel();
        AnsWrongCount = new javax.swing.JLabel();
        AnsWrong4 = new javax.swing.JLabel();
        ScoreCount = new javax.swing.JLabel();
        GamePanelScrabledWord = new javax.swing.JPanel();
        ScrambledWordOutput = new javax.swing.JLabel();
        AnswerInput = new javax.swing.JTextField();
        AnsWrong5 = new javax.swing.JLabel();
        Instruction = new javax.swing.JPanel();
        GameTitle = new javax.swing.JLabel();
        InstructionPanel = new javax.swing.JPanel();
        AdditionSubtitle22 = new javax.swing.JLabel();
        GamePanel1 = new javax.swing.JPanel();
        AdditionSubtitle23 = new javax.swing.JLabel();
        StartButton = new javax.swing.JButton();
        Leaderboard2 = new javax.swing.JButton();
        QuitButton = new javax.swing.JButton();
        GameEnd = new javax.swing.JPanel();
        ScreenPanelSample1 = new javax.swing.JPanel();
        FinalCorrectAnswers = new javax.swing.JTextField();
        FinalCorrectAnswersOutput = new javax.swing.JTextField();
        FinalWrongAnswersOutput = new javax.swing.JTextField();
        FinalWrongAnswers = new javax.swing.JTextField();
        FinalScore = new javax.swing.JTextField();
        FinalScoreOutput = new javax.swing.JTextField();
        CoinsGetOutput = new javax.swing.JTextField();
        CoinsGet = new javax.swing.JTextField();
        AdditionSubtitle18 = new javax.swing.JLabel();
        Leaderboard = new javax.swing.JButton();
        RestartButton = new javax.swing.JButton();
        QuitButton3 = new javax.swing.JButton();
        LeaderboardPanel = new javax.swing.JPanel();
        LeaderboardScrollPanel1 = new javax.swing.JScrollPane();
        Leaderboard1 = new javax.swing.JTable();
        GameTitle1 = new javax.swing.JLabel();
        BacktoInstructionButton = new javax.swing.JButton();
        QuitButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GamePanelCards.setLayout(new java.awt.CardLayout());

        MainGame.setBackground(new java.awt.Color(38, 60, 76));
        MainGame.setMaximumSize(new java.awt.Dimension(800, 500));
        MainGame.setMinimumSize(new java.awt.Dimension(800, 500));
        MainGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GamePanelDefinition.setBackground(new java.awt.Color(75, 99, 115));

        DefinitionOutput.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        DefinitionOutput.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout GamePanelDefinitionLayout = new javax.swing.GroupLayout(GamePanelDefinition);
        GamePanelDefinition.setLayout(GamePanelDefinitionLayout);
        GamePanelDefinitionLayout.setHorizontalGroup(
            GamePanelDefinitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamePanelDefinitionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DefinitionOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                .addContainerGap())
        );
        GamePanelDefinitionLayout.setVerticalGroup(
            GamePanelDefinitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePanelDefinitionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DefinitionOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainGame.add(GamePanelDefinition, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 740, 120));

        AnsCorrCount.setBackground(new java.awt.Color(255, 255, 255));
        AnsCorrCount.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AnsCorrCount.setForeground(new java.awt.Color(204, 255, 204));
        AnsCorrCount.setText("0");
        MainGame.add(AnsCorrCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 30, -1));

        AnsCorrect.setBackground(new java.awt.Color(255, 255, 255));
        AnsCorrect.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AnsCorrect.setForeground(new java.awt.Color(204, 255, 204));
        AnsCorrect.setText("Correct Answers: ");
        MainGame.add(AnsCorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, -1));

        AnsWrong.setBackground(new java.awt.Color(255, 255, 255));
        AnsWrong.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AnsWrong.setForeground(new java.awt.Color(255, 204, 204));
        AnsWrong.setText("Wrong Answers: ");
        MainGame.add(AnsWrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 120, 20));

        AnsWrongCount.setBackground(new java.awt.Color(255, 255, 255));
        AnsWrongCount.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AnsWrongCount.setForeground(new java.awt.Color(255, 204, 204));
        AnsWrongCount.setText("0");
        MainGame.add(AnsWrongCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 30, 20));

        AnsWrong4.setBackground(new java.awt.Color(255, 255, 255));
        AnsWrong4.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AnsWrong4.setForeground(new java.awt.Color(255, 255, 255));
        AnsWrong4.setText("Answer:");
        MainGame.add(AnsWrong4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 50, -1));

        ScoreCount.setBackground(new java.awt.Color(255, 255, 255));
        ScoreCount.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        ScoreCount.setForeground(new java.awt.Color(255, 255, 255));
        ScoreCount.setText("0");
        MainGame.add(ScoreCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 80, -1));

        GamePanelScrabledWord.setBackground(new java.awt.Color(75, 99, 115));

        ScrambledWordOutput.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ScrambledWordOutput.setForeground(new java.awt.Color(255, 255, 255));
        ScrambledWordOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout GamePanelScrabledWordLayout = new javax.swing.GroupLayout(GamePanelScrabledWord);
        GamePanelScrabledWord.setLayout(GamePanelScrabledWordLayout);
        GamePanelScrabledWordLayout.setHorizontalGroup(
            GamePanelScrabledWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamePanelScrabledWordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrambledWordOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );
        GamePanelScrabledWordLayout.setVerticalGroup(
            GamePanelScrabledWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamePanelScrabledWordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrambledWordOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainGame.add(GamePanelScrabledWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 510, 70));

        AnswerInput.setBackground(new java.awt.Color(114, 142, 160));
        AnswerInput.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        AnswerInput.setForeground(new java.awt.Color(255, 255, 255));
        AnswerInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AnswerInput.setBorder(null);
        AnswerInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AnswerInputKeyPressed(evt);
            }
        });
        MainGame.add(AnswerInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 490, 60));

        AnsWrong5.setBackground(new java.awt.Color(255, 255, 255));
        AnsWrong5.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AnsWrong5.setForeground(new java.awt.Color(255, 255, 255));
        AnsWrong5.setText("Score:");
        MainGame.add(AnsWrong5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 50, -1));

        GamePanelCards.add(MainGame, "card2");

        Instruction.setBackground(new java.awt.Color(38, 60, 76));
        Instruction.setMaximumSize(new java.awt.Dimension(800, 500));
        Instruction.setMinimumSize(new java.awt.Dimension(800, 500));
        Instruction.setPreferredSize(new java.awt.Dimension(800, 500));
        Instruction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GameTitle.setFont(new java.awt.Font("Fredoka Medium", 1, 36)); // NOI18N
        GameTitle.setForeground(new java.awt.Color(167, 210, 233));
        GameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GameTitle.setText("Quickquirk Spelling Bee!");
        Instruction.add(GameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 780, 60));

        InstructionPanel.setBackground(new java.awt.Color(75, 99, 115));

        AdditionSubtitle22.setFont(new java.awt.Font("Fredoka", 0, 18)); // NOI18N
        AdditionSubtitle22.setForeground(new java.awt.Color(255, 255, 255));
        AdditionSubtitle22.setText("<html>A definition of an English term will be provided, along with an scrambled word. </html>");

        javax.swing.GroupLayout InstructionPanelLayout = new javax.swing.GroupLayout(InstructionPanel);
        InstructionPanel.setLayout(InstructionPanelLayout);
        InstructionPanelLayout.setHorizontalGroup(
            InstructionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstructionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle22, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        InstructionPanelLayout.setVerticalGroup(
            InstructionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstructionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle22, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        Instruction.add(InstructionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 740, 50));

        GamePanel1.setBackground(new java.awt.Color(75, 99, 115));

        AdditionSubtitle23.setBackground(new java.awt.Color(75, 99, 115));
        AdditionSubtitle23.setFont(new java.awt.Font("Fredoka", 0, 18)); // NOI18N
        AdditionSubtitle23.setForeground(new java.awt.Color(255, 255, 255));
        AdditionSubtitle23.setText("<html>Your job is to unscramble the word and type it into the answer box to score points! </html>");

        javax.swing.GroupLayout GamePanel1Layout = new javax.swing.GroupLayout(GamePanel1);
        GamePanel1.setLayout(GamePanel1Layout);
        GamePanel1Layout.setHorizontalGroup(
            GamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle23, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                .addContainerGap())
        );
        GamePanel1Layout.setVerticalGroup(
            GamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle23, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        Instruction.add(GamePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 740, 60));

        StartButton.setBackground(new java.awt.Color(159, 211, 211));
        StartButton.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        StartButton.setText("Start!");
        StartButton.setBorder(null);
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });
        Instruction.add(StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 210, 60));

        Leaderboard2.setBackground(new java.awt.Color(204, 204, 255));
        Leaderboard2.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        Leaderboard2.setText("Leaderboard");
        Leaderboard2.setBorder(null);
        Leaderboard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Leaderboard2ActionPerformed(evt);
            }
        });
        Instruction.add(Leaderboard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 170, 40));

        QuitButton.setBackground(new java.awt.Color(255, 204, 204));
        QuitButton.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        QuitButton.setText("Quit");
        QuitButton.setBorder(null);
        QuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButtonActionPerformed(evt);
            }
        });
        Instruction.add(QuitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 170, 40));

        GamePanelCards.add(Instruction, "card3");

        GameEnd.setBackground(new java.awt.Color(38, 60, 76));
        GameEnd.setMaximumSize(new java.awt.Dimension(800, 500));
        GameEnd.setMinimumSize(new java.awt.Dimension(800, 500));
        GameEnd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScreenPanelSample1.setBackground(new java.awt.Color(75, 99, 115));
        ScreenPanelSample1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FinalCorrectAnswers.setEditable(false);
        FinalCorrectAnswers.setBackground(new java.awt.Color(75, 99, 115));
        FinalCorrectAnswers.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        FinalCorrectAnswers.setForeground(new java.awt.Color(255, 255, 255));
        FinalCorrectAnswers.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        FinalCorrectAnswers.setText("Correct Answers:");
        FinalCorrectAnswers.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample1.add(FinalCorrectAnswers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 30));

        FinalCorrectAnswersOutput.setEditable(false);
        FinalCorrectAnswersOutput.setBackground(new java.awt.Color(75, 99, 115));
        FinalCorrectAnswersOutput.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        FinalCorrectAnswersOutput.setForeground(new java.awt.Color(153, 255, 153));
        FinalCorrectAnswersOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FinalCorrectAnswersOutput.setText("0");
        FinalCorrectAnswersOutput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample1.add(FinalCorrectAnswersOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 200, 30));

        FinalWrongAnswersOutput.setEditable(false);
        FinalWrongAnswersOutput.setBackground(new java.awt.Color(75, 99, 115));
        FinalWrongAnswersOutput.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        FinalWrongAnswersOutput.setForeground(new java.awt.Color(255, 204, 204));
        FinalWrongAnswersOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FinalWrongAnswersOutput.setText("0");
        FinalWrongAnswersOutput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample1.add(FinalWrongAnswersOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 200, 30));

        FinalWrongAnswers.setEditable(false);
        FinalWrongAnswers.setBackground(new java.awt.Color(75, 99, 115));
        FinalWrongAnswers.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        FinalWrongAnswers.setForeground(new java.awt.Color(255, 255, 255));
        FinalWrongAnswers.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        FinalWrongAnswers.setText("Wrong Answers:");
        FinalWrongAnswers.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample1.add(FinalWrongAnswers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 240, 30));

        FinalScore.setEditable(false);
        FinalScore.setBackground(new java.awt.Color(75, 99, 115));
        FinalScore.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        FinalScore.setForeground(new java.awt.Color(255, 255, 255));
        FinalScore.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        FinalScore.setText("Final Score:");
        FinalScore.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample1.add(FinalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 240, 30));

        FinalScoreOutput.setEditable(false);
        FinalScoreOutput.setBackground(new java.awt.Color(75, 99, 115));
        FinalScoreOutput.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        FinalScoreOutput.setForeground(new java.awt.Color(255, 255, 255));
        FinalScoreOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FinalScoreOutput.setText("0");
        FinalScoreOutput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample1.add(FinalScoreOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 200, 30));

        CoinsGetOutput.setEditable(false);
        CoinsGetOutput.setBackground(new java.awt.Color(75, 99, 115));
        CoinsGetOutput.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        CoinsGetOutput.setForeground(new java.awt.Color(255, 255, 204));
        CoinsGetOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CoinsGetOutput.setText("0");
        CoinsGetOutput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample1.add(CoinsGetOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 200, 40));

        CoinsGet.setEditable(false);
        CoinsGet.setBackground(new java.awt.Color(75, 99, 115));
        CoinsGet.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        CoinsGet.setForeground(new java.awt.Color(255, 255, 255));
        CoinsGet.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CoinsGet.setText("Coins Earned:");
        CoinsGet.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample1.add(CoinsGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 240, 40));

        GameEnd.add(ScreenPanelSample1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 460, 200));

        AdditionSubtitle18.setFont(new java.awt.Font("Fredoka Medium", 1, 36)); // NOI18N
        AdditionSubtitle18.setForeground(new java.awt.Color(255, 255, 255));
        AdditionSubtitle18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdditionSubtitle18.setText("Game End!");
        GameEnd.add(AdditionSubtitle18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 780, 60));

        Leaderboard.setBackground(new java.awt.Color(204, 204, 255));
        Leaderboard.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        Leaderboard.setText("Leaderboard");
        Leaderboard.setBorder(null);
        Leaderboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaderboardActionPerformed(evt);
            }
        });
        GameEnd.add(Leaderboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 220, 40));

        RestartButton.setBackground(new java.awt.Color(255, 255, 102));
        RestartButton.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        RestartButton.setText("Restart!");
        RestartButton.setBorder(null);
        RestartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartButtonActionPerformed(evt);
            }
        });
        GameEnd.add(RestartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 220, 40));

        QuitButton3.setBackground(new java.awt.Color(255, 204, 204));
        QuitButton3.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        QuitButton3.setText("Quit");
        QuitButton3.setBorder(null);
        QuitButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButton3ActionPerformed(evt);
            }
        });
        GameEnd.add(QuitButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 220, 40));

        GamePanelCards.add(GameEnd, "card3");

        LeaderboardPanel.setBackground(new java.awt.Color(38, 60, 76));
        LeaderboardPanel.setMaximumSize(new java.awt.Dimension(800, 500));
        LeaderboardPanel.setMinimumSize(new java.awt.Dimension(800, 500));
        LeaderboardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeaderboardScrollPanel1.setBackground(new java.awt.Color(116, 143, 118));
        LeaderboardScrollPanel1.setBorder(null);
        LeaderboardScrollPanel1.setForeground(new java.awt.Color(116, 143, 118));
        LeaderboardScrollPanel1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        LeaderboardScrollPanel1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        LeaderboardScrollPanel1.setMaximumSize(new java.awt.Dimension(710, 330));
        LeaderboardScrollPanel1.setMinimumSize(new java.awt.Dimension(710, 330));
        LeaderboardScrollPanel1.setPreferredSize(new java.awt.Dimension(710, 330));

        Leaderboard1.setAutoCreateRowSorter(true);
        Leaderboard1.setBackground(new java.awt.Color(75, 99, 115));
        Leaderboard1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Leaderboard1.setForeground(new java.awt.Color(255, 255, 255));
        Leaderboard1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Rank", "Username", "Full Name", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Leaderboard1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Leaderboard1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Leaderboard1.setGridColor(new java.awt.Color(210, 224, 212));
        Leaderboard1.setMaximumSize(new java.awt.Dimension(452, 402));
        Leaderboard1.setMinimumSize(new java.awt.Dimension(452, 402));
        Leaderboard1.setPreferredSize(new java.awt.Dimension(452, 402));
        Leaderboard1.setRowHeight(40);
        Leaderboard1.getTableHeader().setResizingAllowed(false);
        Leaderboard1.getTableHeader().setReorderingAllowed(false);
        LeaderboardScrollPanel1.setViewportView(Leaderboard1);

        LeaderboardPanel.add(LeaderboardScrollPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 710, 250));

        GameTitle1.setFont(new java.awt.Font("Fredoka Medium", 1, 36)); // NOI18N
        GameTitle1.setForeground(new java.awt.Color(167, 210, 233));
        GameTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GameTitle1.setText("Leaderboard");
        LeaderboardPanel.add(GameTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 780, 60));

        BacktoInstructionButton.setBackground(new java.awt.Color(159, 211, 211));
        BacktoInstructionButton.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        BacktoInstructionButton.setText("Go Back");
        BacktoInstructionButton.setBorder(null);
        BacktoInstructionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoInstructionButtonActionPerformed(evt);
            }
        });
        LeaderboardPanel.add(BacktoInstructionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 200, 70));

        QuitButton4.setBackground(new java.awt.Color(255, 204, 204));
        QuitButton4.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        QuitButton4.setText("Quit");
        QuitButton4.setBorder(null);
        QuitButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButton4ActionPerformed(evt);
            }
        });
        LeaderboardPanel.add(QuitButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 200, 70));

        GamePanelCards.add(LeaderboardPanel, "card3");

        getContentPane().add(GamePanelCards, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        cardlayout.show(GamePanelCards,"MainGame");
        score = corrAnsCount = wroAnsCount = questioncount = 0;
        // Call question logic here
        this.QuestionBank();
        AnswerInput.requestFocusInWindow();
    }//GEN-LAST:event_StartButtonActionPerformed

    private void Leaderboard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Leaderboard2ActionPerformed
        cardlayout.show(GamePanelCards,"LeaderboardPanelFromInstruction");
        displayLeaderboard();
    }//GEN-LAST:event_Leaderboard2ActionPerformed

    private void QuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButtonActionPerformed
        this.dispose();
        EnglishCourse ec = new EnglishCourse();
        ec.setVisible(true);
    }//GEN-LAST:event_QuitButtonActionPerformed

    private void BacktoInstructionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktoInstructionButtonActionPerformed
        cardlayout.show(GamePanelCards,"Instruction");
    }//GEN-LAST:event_BacktoInstructionButtonActionPerformed

    private void QuitButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButton4ActionPerformed
        this.dispose();
        EnglishCourse ec = new EnglishCourse();
        ec.setname(this.uname, this.fname);
        ec.setVisible(true);
    }//GEN-LAST:event_QuitButton4ActionPerformed

    private void LeaderboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaderboardActionPerformed
        // Leaderboard Method here
        cardlayout.show(GamePanelCards,"LeaderboardPanelFromInstruction");
        displayLeaderboard();

    }//GEN-LAST:event_LeaderboardActionPerformed

    private void RestartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartButtonActionPerformed
        cardlayout.show(GamePanelCards,"MainGame");
        score = corrAnsCount = wroAnsCount = questioncount = 0;
        
        strwroAnsCount = "0";
        strcorrAnsCount = "0";
        strscore = "0";
        
        this.QuestionBank();
        AnswerInput.requestFocusInWindow();
    }//GEN-LAST:event_RestartButtonActionPerformed

    private void QuitButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButton3ActionPerformed
        this.dispose();
        EnglishCourse ec = new EnglishCourse();
        ec.setVisible(true);
    }//GEN-LAST:event_QuitButton3ActionPerformed

    private void AnswerInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AnswerInputKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(AnswerInput.getText().trim().equals(corrAns.trim())){
                corrAnsCount++;
                score = score + 200;
                strcorrAnsCount = Integer.toString(corrAnsCount);
                strscore = Integer.toString(score);
                
                AnsCorrCount.setText(strcorrAnsCount);
                ScoreCount.setText(strscore);
            } else {
                wroAnsCount++;
                strwroAnsCount = Integer.toString(wroAnsCount);
                
                AnsWrongCount.setText(strwroAnsCount);
            }
            
            AnswerInput.setText(""); // Clears the input
            
            
            if(questioncount == 4){
                // Go to end page
                cardlayout.show(GamePanelCards, "GameEnd");
                
                // Coins earned set at score/10
                coins = score/10;
                strcoins = Integer.toString(coins);
                CoinsGetOutput.setText(strcoins);
                updateCoins(coins);
                
                if(score == 0){
                    strscore = "0";
                } else if (corrAnsCount == 0){
                    strcorrAnsCount = "0";
                } else if (wroAnsCount == 0){
                    strwroAnsCount = "0";
                }
                
                FinalScoreOutput.setText(strscore);
                FinalCorrectAnswersOutput.setText(strcorrAnsCount);
                FinalWrongAnswersOutput.setText(strwroAnsCount);

                // Update Leaderboard
                AddtoLeaderboard();
                sortLeaderboard();
                
            } else {
                System.out.println("\nNext Question:\n");
                questioncount++;
                this.QuestionBank();
            }
        }
    }//GEN-LAST:event_AnswerInputKeyPressed

    // Setting username to use for leaderboard
    public void setname(String uname, String fname){
        this.uname = uname;
        this.fname = fname;
    }
    
    // Game Logic from this line onwards
    //===============================================================================
    
    // Random Number Generator
    private int rndNum(int maxNum){
        long seed = System.currentTimeMillis();
        Random rnd = new Random(seed);
        
        int rndNum = rnd.nextInt(maxNum) + 1;
        return rndNum;
    }
    
    private void setQuestion(String question, String answer){
        DefinitionOutput.setText(question);
        ScrambledWordOutput.setText(scrambleWord(answer));
        this.corrAns = answer;
        
        System.out.println("Correct answer: " + answer);
    }
    
    public String scrambleWord(String word) {
        char[] characters = word.toCharArray();
        Random random = new Random();

        for (int i = characters.length - 1; i > 0; i--) {
            int j = random.nextInt(i + 1); // Random index from 0 to i
            
            char temp = characters[i];
            characters[i] = characters[j];
            characters[j] = temp;
        }

        return new String(characters);
    }
    
    // Game logic
    private void QuestionBank(){
        int questionnumber = rndNum(10);
        switch(questionnumber){
            case 1:
                setQuestion("Something absolutely necessary.","Essential");
                break;
            case 2:
                setQuestion("Relaxed and informal; not fancy.","Casual");
                break;
            case 3:
                setQuestion("Someone or something you can trust to work well.","Reliable");
                break;
            case 4:
                setQuestion("Very short in duration or length.","Brief");
                break;
            case 5:
                setQuestion("To think carefully about something.","Consider");
                break;
            case 6:
                setQuestion("Physical or mental energy used to do something.","Effort");
                break;
            case 7:
                setQuestion("Feeling upset because something is difficult or annoying.","Frustrated");
                break;
            case 8:
                setQuestion("Easy and suitable for your needs.","Convenient");
                break;
            case 9:
                setQuestion("Happening often; many times.","Frequently");
                break;
            case 10:
                setQuestion("Ready for use or ready to help.","Available");
                break;
            default: System.out.println("Random number outside of range: " + questionnumber); break; // Debug
        }
        
    }
    
    // Leaderboard
    private void AddtoLeaderboard(){
        boolean unamefound = false;
        try {
            File leaderboardfile = new File("Leaderboard/engGame.csv");
            File templeaderboardfile = new File("Leaderboard/temp.csv");
            
            System.out.println("\nUsername: " + this.uname); // Debug

            if (!leaderboardfile.exists()) {
                leaderboardfile.createNewFile();
            }
            
            BufferedReader lbreader = new BufferedReader(new FileReader(leaderboardfile));
            BufferedWriter lbwriter = new BufferedWriter(new FileWriter(templeaderboardfile));
            
            String line;
            
            // If the leaderboard has username in it, updates it.
            while((line = lbreader.readLine()) != null){
                String[] parts = line.split(",");
                
                if (parts[1].trim().equals(this.uname.trim())){
                    unamefound = true;
                    System.out.println("\nUsername found: " + unamefound + 
                            "\nUsername: " + parts[1] + 
                            "\nUpdating score only..."); //Debug
                    parts[3] = strscore; // Changes the score to the new score
                }
                
                lbwriter.write(String.join(",", parts));
                lbwriter.newLine();
            }
            
            // If the username is not found, then adds one
            if (unamefound == false){
                String newinput = "" + "," + this.uname + "," + this.fname + "," +
                        score;
                lbwriter.write(newinput);
            }
            
            lbreader.close();
            lbwriter.close();
            
            if (leaderboardfile.delete()) {
                templeaderboardfile.renameTo(leaderboardfile);
            }
            
        } catch (IOException e){
            e.printStackTrace();
        }
        
    }
    
    private void sortLeaderboard(){
        File leaderboardFile = new File("Leaderboard/engGame.csv");
        File templeaderboardFile = new File("Leaderboard/temp.csv");

        String[][] data = new String[100][4]; // Max 100 rows, 4 columns
        int rowCount = 0;

        // Read file into array [rows][columns]
        try {
            BufferedReader reader = new BufferedReader(new FileReader(leaderboardFile));
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length == 4) {
                    for (int i = 0; i < 4; i++) {
                        data[rowCount][i] = parts[i];
                    }
                    rowCount++;
                }
            }
            
            reader.close();
            
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Insertion sort by score
        for (int i = 1; i < rowCount; i++) {
            String[] key = data[i];
            int keyScore = Integer.parseInt(key[3].trim());

            int j = i - 1;

            // Shift elements that are less than keyScore
            while (j >= 0 && Integer.parseInt(data[j][3].trim()) < keyScore) {
                data[j + 1] = data[j];
                j--;
            }

            data[j + 1] = key;
        }

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(templeaderboardFile))) {
            for (int i = 0; i < rowCount; i++) {
                String rank = Integer.toString(i + 1);
                writer.write(rank + "," + data[i][1] + "," + data[i][2] + "," + data[i][3]);
                writer.newLine();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        // Replace original file with sorted temp file
        if (leaderboardFile.delete()) {
            templeaderboardFile.renameTo(leaderboardFile);
        }
    
    }
    
    private void updateCoins(int coins){
        // Retrieve public information (Name, username)
        File userfile = new File("Learner/" + this.uname + "/accountDetails.csv");
        File tempuserfilePath = new File("Learner/" + this.uname + "/temp.csv");
        try {
            BufferedReader reader = new BufferedReader(new FileReader(userfile));
            BufferedWriter writer = new BufferedWriter(new FileWriter(tempuserfilePath));

            String line;
            int lineNumber = 0;

            while ((line = reader.readLine()) != null) {
                switch (lineNumber) {
                    case 4:
                        int oldcoins = Integer.parseInt(line);
                        int newcoins = oldcoins + coins;
                        String strtotalcoins = Integer.toString(newcoins);
                        writer.write(strtotalcoins); 
                        break; // Update coins
                    case 7:
                        int oldscore = Integer.parseInt(line);
                        if(score > oldscore){
                            String strnewscore = Integer.toString(score);
                            writer.write(strnewscore);
                            break; // updates high score
                        }
                    default: writer.write(line); break;    // Keep original
                }
                writer.newLine();
                lineNumber++;
            }

            reader.close();
            writer.close();

            if (userfile.delete()) {
                if (tempuserfilePath.renameTo(userfile)) {
                    System.out.println("Updated successfully!"); // Debug
                } else {
                    System.out.println(" Couldn't rename temp file."); // Debug
                }
            } else {
                System.out.println("Couldn't delete original file."); // Debug
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void displayLeaderboard(){
        String[] columnNames = { "Rank", "Username", "Full Name", "Score" };
        String[][] rowData = new String[100][4];
        int rowCount = 0;

        try (BufferedReader reader = new BufferedReader(new FileReader("Leaderboard/engGame.csv"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length == 4) {
                    for (int i = 0; i < 4; i++) {
                        rowData[rowCount][i] = parts[i];
                    }
                    rowCount++;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Trim the array to actual data size, this will be used for users outside of top 7
        String[][] trimmedData = new String[rowCount][4];
        for (int i = 0; i < rowCount; i++) {
            for (int j = 0; j < 4; j++) {
                trimmedData[i][j] = rowData[i][j];
            }
            
        }
        
        // Top 7 make it to leaderboard
        int topCount = Math.min(rowCount, 7);
        String[][] topData = new String[topCount][4];

        for (int i = 0; i < topCount; i++) {
            for (int j = 0; j < 4; j++) {
                topData[i][j] = trimmedData[i][j];
            }
        }
        
        DefaultTableModel model = new DefaultTableModel(topData, columnNames);
        Leaderboard1.setModel(model);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnglishGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnglishGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnglishGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnglishGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnglishGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdditionSubtitle18;
    private javax.swing.JLabel AdditionSubtitle22;
    private javax.swing.JLabel AdditionSubtitle23;
    private javax.swing.JLabel AnsCorrCount;
    private javax.swing.JLabel AnsCorrect;
    private javax.swing.JLabel AnsWrong;
    private javax.swing.JLabel AnsWrong4;
    private javax.swing.JLabel AnsWrong5;
    private javax.swing.JLabel AnsWrongCount;
    private javax.swing.JTextField AnswerInput;
    private javax.swing.JButton BacktoInstructionButton;
    private javax.swing.JTextField CoinsGet;
    private javax.swing.JTextField CoinsGetOutput;
    private javax.swing.JLabel DefinitionOutput;
    private javax.swing.JTextField FinalCorrectAnswers;
    private javax.swing.JTextField FinalCorrectAnswersOutput;
    private javax.swing.JTextField FinalScore;
    private javax.swing.JTextField FinalScoreOutput;
    private javax.swing.JTextField FinalWrongAnswers;
    private javax.swing.JTextField FinalWrongAnswersOutput;
    private javax.swing.JPanel GameEnd;
    private javax.swing.JPanel GamePanel1;
    private javax.swing.JPanel GamePanelCards;
    private javax.swing.JPanel GamePanelDefinition;
    private javax.swing.JPanel GamePanelScrabledWord;
    private javax.swing.JLabel GameTitle;
    private javax.swing.JLabel GameTitle1;
    private javax.swing.JPanel Instruction;
    private javax.swing.JPanel InstructionPanel;
    private javax.swing.JButton Leaderboard;
    private javax.swing.JTable Leaderboard1;
    private javax.swing.JButton Leaderboard2;
    private javax.swing.JPanel LeaderboardPanel;
    private javax.swing.JScrollPane LeaderboardScrollPanel1;
    private javax.swing.JPanel MainGame;
    private javax.swing.JButton QuitButton;
    private javax.swing.JButton QuitButton3;
    private javax.swing.JButton QuitButton4;
    private javax.swing.JButton RestartButton;
    private javax.swing.JLabel ScoreCount;
    private javax.swing.JLabel ScrambledWordOutput;
    private javax.swing.JPanel ScreenPanelSample1;
    private javax.swing.JButton StartButton;
    // End of variables declaration//GEN-END:variables
}
