package QuickQuirkGameLab;

import java.awt.CardLayout;

public class EnglishCourse extends javax.swing.JFrame {

    private int x;
    private int y;
    private String uname; // This needs to be passed on to the game
    private String fname;
    
    CardLayout cardlayout;
    CardLayout vocab1;
    CardLayout vocab2;
    CardLayout vocab3;
    CardLayout vocab4;
    
    public EnglishCourse() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        cardlayout = (CardLayout)(SelectedCourseCards.getLayout());
        SelectedCourseCards.add(Welcome, "Welcome");
        SelectedCourseCards.add(Lesson1, "Lesson1");
        SelectedCourseCards.add(Lesson2, "Lesson2");
        
        vocab1 = (CardLayout)(VocabularyParentPanel1.getLayout());
        VocabularyParentPanel1.add(Vocabulary1, "Vocabulary1");
        VocabularyParentPanel1.add(Definition1, "Definition1");
        
        vocab2 = (CardLayout)(VocabularyParentPanel2.getLayout());
        VocabularyParentPanel2.add(Vocabulary2, "Vocabulary2");
        VocabularyParentPanel2.add(Definition2, "Definition2");
        
        vocab3 = (CardLayout)(VocabularyParentPanel3.getLayout());
        VocabularyParentPanel3.add(Vocabulary3, "Vocabulary3");
        VocabularyParentPanel3.add(Definition3, "Definition3");
        
        vocab4 = (CardLayout)(VocabularyParentPanel4.getLayout());
        VocabularyParentPanel4.add(Vocabulary4, "Vocabulary4");
        VocabularyParentPanel4.add(Definition4, "Definition4");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopupWindowTop = new javax.swing.JPanel();
        ClosePopup = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        CourseMainBody = new javax.swing.JSplitPane();
        CourseSelector = new javax.swing.JPanel();
        WelcomeButton = new javax.swing.JButton();
        PlayGameButton = new javax.swing.JButton();
        Lesson1Button = new javax.swing.JButton();
        Lesson3Button = new javax.swing.JButton();
        SelectedCourseCards = new javax.swing.JPanel();
        Welcome = new javax.swing.JPanel();
        AccessCoursesTitle = new javax.swing.JLabel();
        WelcomeMessage = new javax.swing.JLabel();
        Instruction = new javax.swing.JLabel();
        Design = new javax.swing.JLabel();
        Lesson1 = new javax.swing.JPanel();
        AccessCoursesTitle1 = new javax.swing.JLabel();
        AdditionPanel = new javax.swing.JPanel();
        AdditionSubtitle = new javax.swing.JLabel();
        AdditionSubtitle1 = new javax.swing.JLabel();
        SubtractionPanel = new javax.swing.JPanel();
        SubstractSubtitle = new javax.swing.JLabel();
        AdditionSubtitle3 = new javax.swing.JLabel();
        MultiplicationPanel = new javax.swing.JPanel();
        SubstractSubtitle1 = new javax.swing.JLabel();
        AdditionSubtitle4 = new javax.swing.JLabel();
        DivisionPanel = new javax.swing.JPanel();
        SubstractSubtitle2 = new javax.swing.JLabel();
        AdditionSubtitle5 = new javax.swing.JLabel();
        ArithmeticImg = new javax.swing.JLabel();
        ArithmeticImg1 = new javax.swing.JLabel();
        ArithmeticImg2 = new javax.swing.JLabel();
        ArithmeticImg3 = new javax.swing.JLabel();
        Lesson2 = new javax.swing.JPanel();
        IaRTitle1 = new javax.swing.JLabel();
        VocabularyParentPanel1 = new javax.swing.JPanel();
        Vocabulary1 = new javax.swing.JPanel();
        AdditionSubtitle6 = new javax.swing.JLabel();
        Definition1 = new javax.swing.JPanel();
        AdditionSubtitle2 = new javax.swing.JLabel();
        VocabularyParentPanel2 = new javax.swing.JPanel();
        Vocabulary2 = new javax.swing.JPanel();
        AdditionSubtitle7 = new javax.swing.JLabel();
        Definition2 = new javax.swing.JPanel();
        AdditionSubtitle8 = new javax.swing.JLabel();
        VocabularyParentPanel3 = new javax.swing.JPanel();
        Vocabulary3 = new javax.swing.JPanel();
        AdditionSubtitle9 = new javax.swing.JLabel();
        Definition3 = new javax.swing.JPanel();
        AdditionSubtitle10 = new javax.swing.JLabel();
        VocabularyParentPanel4 = new javax.swing.JPanel();
        Vocabulary4 = new javax.swing.JPanel();
        AdditionSubtitle11 = new javax.swing.JLabel();
        Definition4 = new javax.swing.JPanel();
        AdditionSubtitle12 = new javax.swing.JLabel();
        AdditionSubtitle13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);

        PopupWindowTop.setBackground(new java.awt.Color(85, 143, 127));
        PopupWindowTop.setForeground(new java.awt.Color(85, 143, 127));
        PopupWindowTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PopupWindowTopMouseDragged(evt);
            }
        });
        PopupWindowTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PopupWindowTopMousePressed(evt);
            }
        });

        ClosePopup.setBackground(new java.awt.Color(242, 0, 0));
        ClosePopup.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        ClosePopup.setForeground(new java.awt.Color(255, 255, 255));
        ClosePopup.setText("x");
        ClosePopup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ClosePopupMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout PopupWindowTopLayout = new javax.swing.GroupLayout(PopupWindowTop);
        PopupWindowTop.setLayout(PopupWindowTopLayout);
        PopupWindowTopLayout.setHorizontalGroup(
            PopupWindowTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PopupWindowTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ClosePopup)
                .addGap(16, 16, 16))
        );
        PopupWindowTopLayout.setVerticalGroup(
            PopupWindowTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopupWindowTopLayout.createSequentialGroup()
                .addComponent(ClosePopup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        Background.setBackground(new java.awt.Color(230, 241, 231));

        CourseMainBody.setDividerLocation(-10);
        CourseMainBody.setDividerSize(0);

        CourseSelector.setBackground(new java.awt.Color(27, 47, 51));
        CourseSelector.setMaximumSize(new java.awt.Dimension(200, 538));
        CourseSelector.setMinimumSize(new java.awt.Dimension(200, 538));
        CourseSelector.setPreferredSize(new java.awt.Dimension(200, 538));

        WelcomeButton.setBackground(new java.awt.Color(84, 129, 118));
        WelcomeButton.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        WelcomeButton.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeButton.setText("Welcome to English!");
        WelcomeButton.setBorder(null);
        WelcomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WelcomeButtonActionPerformed(evt);
            }
        });

        PlayGameButton.setBackground(new java.awt.Color(255, 255, 102));
        PlayGameButton.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        PlayGameButton.setText("Play Game! ");
        PlayGameButton.setBorder(null);
        PlayGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayGameButtonActionPerformed(evt);
            }
        });

        Lesson1Button.setBackground(new java.awt.Color(84, 129, 118));
        Lesson1Button.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        Lesson1Button.setForeground(new java.awt.Color(255, 255, 255));
        Lesson1Button.setText("Basic Punctuation");
        Lesson1Button.setBorder(null);
        Lesson1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson1ButtonActionPerformed(evt);
            }
        });

        Lesson3Button.setBackground(new java.awt.Color(84, 129, 118));
        Lesson3Button.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        Lesson3Button.setForeground(new java.awt.Color(255, 255, 255));
        Lesson3Button.setText("<html><center>Learning New<br>Vocabularies</center></html>");
        Lesson3Button.setBorder(null);
        Lesson3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson3ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CourseSelectorLayout = new javax.swing.GroupLayout(CourseSelector);
        CourseSelector.setLayout(CourseSelectorLayout);
        CourseSelectorLayout.setHorizontalGroup(
            CourseSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CourseSelectorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(CourseSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lesson3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lesson1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlayGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WelcomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        CourseSelectorLayout.setVerticalGroup(
            CourseSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CourseSelectorLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(WelcomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lesson1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lesson3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(PlayGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        CourseMainBody.setLeftComponent(CourseSelector);

        SelectedCourseCards.setBackground(new java.awt.Color(230, 241, 231));
        SelectedCourseCards.setLayout(new java.awt.CardLayout());

        Welcome.setBackground(new java.awt.Color(230, 241, 231));
        Welcome.setMaximumSize(new java.awt.Dimension(600, 538));
        Welcome.setMinimumSize(new java.awt.Dimension(600, 538));
        Welcome.setPreferredSize(new java.awt.Dimension(600, 538));

        AccessCoursesTitle.setFont(new java.awt.Font("Fredoka Medium", 1, 24)); // NOI18N
        AccessCoursesTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessCoursesTitle.setText("Welcome to the language of the world!");

        WelcomeMessage.setBackground(new java.awt.Color(235, 246, 236));
        WelcomeMessage.setFont(new java.awt.Font("Fredoka", 0, 18)); // NOI18N
        WelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeMessage.setText("<html><center>Whether you're just starting or building up your skills, this course will help you read better, write smarter, and speak with confidence.<br> Let's explore stories, words, and expressions together!</center></html>");

        Instruction.setBackground(new java.awt.Color(235, 246, 236));
        Instruction.setFont(new java.awt.Font("Fredoka", 0, 18)); // NOI18N
        Instruction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Instruction.setText("<html><center>Cick on a course on the left to start learning!</center></html>");

        Design.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DesignMath1.png"))); // NOI18N

        javax.swing.GroupLayout WelcomeLayout = new javax.swing.GroupLayout(Welcome);
        Welcome.setLayout(WelcomeLayout);
        WelcomeLayout.setHorizontalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccessCoursesTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
            .addComponent(WelcomeMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(Design, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Instruction)
                .addContainerGap())
        );
        WelcomeLayout.setVerticalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(AccessCoursesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Instruction, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Design, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SelectedCourseCards.add(Welcome, "card2");

        Lesson1.setBackground(new java.awt.Color(230, 241, 231));
        Lesson1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccessCoursesTitle1.setFont(new java.awt.Font("Fredoka Medium", 1, 24)); // NOI18N
        AccessCoursesTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessCoursesTitle1.setText("Basic Punctuation");
        Lesson1.add(AccessCoursesTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 590, 70));

        AdditionPanel.setBackground(new java.awt.Color(255, 255, 255));
        AdditionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        AdditionSubtitle.setText("Period .");
        AdditionPanel.add(AdditionSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        AdditionSubtitle1.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle1.setText("<html>Period ( . ) are used to end a statement.</html>");
        AdditionPanel.add(AdditionSubtitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 40));

        Lesson1.add(AdditionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, 110));

        SubtractionPanel.setBackground(new java.awt.Color(255, 255, 255));
        SubtractionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubstractSubtitle.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        SubstractSubtitle.setText("Exclamation Mark !");
        SubtractionPanel.add(SubstractSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        AdditionSubtitle3.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle3.setText("<html>Exclamation marks ( ! ) are used to show excitement</html>");
        SubtractionPanel.add(AdditionSubtitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 50));

        Lesson1.add(SubtractionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 220, 100));

        MultiplicationPanel.setBackground(new java.awt.Color(255, 255, 255));
        MultiplicationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubstractSubtitle1.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        SubstractSubtitle1.setText("Comma ,");
        MultiplicationPanel.add(SubstractSubtitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        AdditionSubtitle4.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle4.setText("<html>Comma ( , ) are used to separate items in a list, or adds a small pause.</html>");
        MultiplicationPanel.add(AdditionSubtitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 50));

        Lesson1.add(MultiplicationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 220, 100));

        DivisionPanel.setBackground(new java.awt.Color(255, 255, 255));
        DivisionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubstractSubtitle2.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        SubstractSubtitle2.setText("Question Mark ?");
        DivisionPanel.add(SubstractSubtitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        AdditionSubtitle5.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle5.setText("<html>Question marks ( ? ) are used to end a question.</html>");
        DivisionPanel.add(AdditionSubtitle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 60));

        Lesson1.add(DivisionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 220, 100));

        ArithmeticImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PeriodExample.png"))); // NOI18N
        Lesson1.add(ArithmeticImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 280, 80));

        ArithmeticImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CommaExample.png"))); // NOI18N
        Lesson1.add(ArithmeticImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 280, 100));

        ArithmeticImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/QuestionMarkExample.png"))); // NOI18N
        Lesson1.add(ArithmeticImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 280, 100));

        ArithmeticImg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ExclamationMarkExample.png"))); // NOI18N
        Lesson1.add(ArithmeticImg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 280, 100));

        SelectedCourseCards.add(Lesson1, "card3");

        Lesson2.setBackground(new java.awt.Color(230, 241, 231));
        Lesson2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IaRTitle1.setFont(new java.awt.Font("Fredoka Medium", 1, 24)); // NOI18N
        IaRTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IaRTitle1.setText("Learn new Vocabularies!");
        Lesson2.add(IaRTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 590, 70));

        VocabularyParentPanel1.setBackground(new java.awt.Color(255, 255, 255));
        VocabularyParentPanel1.setLayout(new java.awt.CardLayout());

        Vocabulary1.setBackground(new java.awt.Color(255, 255, 255));
        Vocabulary1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Vocabulary1MouseEntered(evt);
            }
        });

        AdditionSubtitle6.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        AdditionSubtitle6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdditionSubtitle6.setText("Brave");

        javax.swing.GroupLayout Vocabulary1Layout = new javax.swing.GroupLayout(Vocabulary1);
        Vocabulary1.setLayout(Vocabulary1Layout);
        Vocabulary1Layout.setHorizontalGroup(
            Vocabulary1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Vocabulary1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Vocabulary1Layout.setVerticalGroup(
            Vocabulary1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vocabulary1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(AdditionSubtitle6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        VocabularyParentPanel1.add(Vocabulary1, "card2");

        Definition1.setBackground(new java.awt.Color(255, 255, 255));
        Definition1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Definition1MouseExited(evt);
            }
        });

        AdditionSubtitle2.setFont(new java.awt.Font("Fredoka", 0, 18)); // NOI18N
        AdditionSubtitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdditionSubtitle2.setText("<html><center>Showing courage and not being afraid of danger.</center></html>");

        javax.swing.GroupLayout Definition1Layout = new javax.swing.GroupLayout(Definition1);
        Definition1.setLayout(Definition1Layout);
        Definition1Layout.setHorizontalGroup(
            Definition1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Definition1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        Definition1Layout.setVerticalGroup(
            Definition1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Definition1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        VocabularyParentPanel1.add(Definition1, "card3");

        Lesson2.add(VocabularyParentPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 230, 100));

        VocabularyParentPanel2.setBackground(new java.awt.Color(255, 255, 255));
        VocabularyParentPanel2.setLayout(new java.awt.CardLayout());

        Vocabulary2.setBackground(new java.awt.Color(255, 255, 255));
        Vocabulary2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Vocabulary2MouseEntered(evt);
            }
        });

        AdditionSubtitle7.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        AdditionSubtitle7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdditionSubtitle7.setText("Joyful");

        javax.swing.GroupLayout Vocabulary2Layout = new javax.swing.GroupLayout(Vocabulary2);
        Vocabulary2.setLayout(Vocabulary2Layout);
        Vocabulary2Layout.setHorizontalGroup(
            Vocabulary2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Vocabulary2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle7, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        Vocabulary2Layout.setVerticalGroup(
            Vocabulary2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vocabulary2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(AdditionSubtitle7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        VocabularyParentPanel2.add(Vocabulary2, "card2");

        Definition2.setBackground(new java.awt.Color(255, 255, 255));
        Definition2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Definition2MouseExited(evt);
            }
        });

        AdditionSubtitle8.setFont(new java.awt.Font("Fredoka", 0, 18)); // NOI18N
        AdditionSubtitle8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdditionSubtitle8.setText("Feeling very happy!");

        javax.swing.GroupLayout Definition2Layout = new javax.swing.GroupLayout(Definition2);
        Definition2.setLayout(Definition2Layout);
        Definition2Layout.setHorizontalGroup(
            Definition2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Definition2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle8, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        Definition2Layout.setVerticalGroup(
            Definition2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Definition2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle8, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        VocabularyParentPanel2.add(Definition2, "card3");

        Lesson2.add(VocabularyParentPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 230, 100));

        VocabularyParentPanel3.setBackground(new java.awt.Color(255, 255, 255));
        VocabularyParentPanel3.setLayout(new java.awt.CardLayout());

        Vocabulary3.setBackground(new java.awt.Color(255, 255, 255));
        Vocabulary3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Vocabulary3MouseEntered(evt);
            }
        });

        AdditionSubtitle9.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        AdditionSubtitle9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdditionSubtitle9.setText("Careful");

        javax.swing.GroupLayout Vocabulary3Layout = new javax.swing.GroupLayout(Vocabulary3);
        Vocabulary3.setLayout(Vocabulary3Layout);
        Vocabulary3Layout.setHorizontalGroup(
            Vocabulary3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Vocabulary3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle9, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        Vocabulary3Layout.setVerticalGroup(
            Vocabulary3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vocabulary3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(AdditionSubtitle9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        VocabularyParentPanel3.add(Vocabulary3, "card2");

        Definition3.setBackground(new java.awt.Color(255, 255, 255));
        Definition3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Definition3MouseExited(evt);
            }
        });

        AdditionSubtitle10.setFont(new java.awt.Font("Fredoka", 0, 18)); // NOI18N
        AdditionSubtitle10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdditionSubtitle10.setText("<html><center>Being cautious and not trying to make mistakes</center></html>");

        javax.swing.GroupLayout Definition3Layout = new javax.swing.GroupLayout(Definition3);
        Definition3.setLayout(Definition3Layout);
        Definition3Layout.setHorizontalGroup(
            Definition3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Definition3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle10, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        Definition3Layout.setVerticalGroup(
            Definition3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Definition3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle10, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        VocabularyParentPanel3.add(Definition3, "card3");

        Lesson2.add(VocabularyParentPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 230, 100));

        VocabularyParentPanel4.setBackground(new java.awt.Color(255, 255, 255));
        VocabularyParentPanel4.setLayout(new java.awt.CardLayout());

        Vocabulary4.setBackground(new java.awt.Color(255, 255, 255));
        Vocabulary4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Vocabulary4MouseEntered(evt);
            }
        });

        AdditionSubtitle11.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        AdditionSubtitle11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdditionSubtitle11.setText("Melancholy");

        javax.swing.GroupLayout Vocabulary4Layout = new javax.swing.GroupLayout(Vocabulary4);
        Vocabulary4.setLayout(Vocabulary4Layout);
        Vocabulary4Layout.setHorizontalGroup(
            Vocabulary4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Vocabulary4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle11, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        Vocabulary4Layout.setVerticalGroup(
            Vocabulary4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Vocabulary4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle11, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        VocabularyParentPanel4.add(Vocabulary4, "card2");

        Definition4.setBackground(new java.awt.Color(255, 255, 255));
        Definition4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Definition4MouseExited(evt);
            }
        });

        AdditionSubtitle12.setFont(new java.awt.Font("Fredoka", 0, 18)); // NOI18N
        AdditionSubtitle12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdditionSubtitle12.setText("Feeling very sad.");

        javax.swing.GroupLayout Definition4Layout = new javax.swing.GroupLayout(Definition4);
        Definition4.setLayout(Definition4Layout);
        Definition4Layout.setHorizontalGroup(
            Definition4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Definition4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle12, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        Definition4Layout.setVerticalGroup(
            Definition4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Definition4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionSubtitle12, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        VocabularyParentPanel4.add(Definition4, "card3");

        Lesson2.add(VocabularyParentPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 230, 100));

        AdditionSubtitle13.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdditionSubtitle13.setText("Hover over a vocabulary to find its definition!");
        Lesson2.add(AdditionSubtitle13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 530, 50));

        SelectedCourseCards.add(Lesson2, "card5");

        CourseMainBody.setRightComponent(SelectedCourseCards);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CourseMainBody)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CourseMainBody)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PopupWindowTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PopupWindowTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClosePopupMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosePopupMouseReleased
        this.dispose();
    }//GEN-LAST:event_ClosePopupMouseReleased

    private void PopupWindowTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopupWindowTopMouseDragged
        // Moves application based on cursor location
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();

        this.setLocation(x1- x, y1 - y);
    }//GEN-LAST:event_PopupWindowTopMouseDragged

    private void PopupWindowTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopupWindowTopMousePressed
        // Get current cursor location upon clicking Top
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_PopupWindowTopMousePressed

    private void WelcomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WelcomeButtonActionPerformed
        cardlayout.show(SelectedCourseCards, "Welcome");
        System.out.println("Panel Changed to Welcome");
    }//GEN-LAST:event_WelcomeButtonActionPerformed

    private void Lesson1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson1ButtonActionPerformed
        cardlayout.show(SelectedCourseCards, "Lesson1");
        System.out.println("Panel Changed to L1");
    }//GEN-LAST:event_Lesson1ButtonActionPerformed

    private void Lesson3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson3ButtonActionPerformed
        cardlayout.show(SelectedCourseCards, "Lesson2");
        System.out.println("Panel Changed to L2");
    }//GEN-LAST:event_Lesson3ButtonActionPerformed

    private void PlayGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayGameButtonActionPerformed
        this.dispose();
        EnglishGame eg = new EnglishGame();
        eg.setVisible(true);
        eg.setname(this.uname,this.fname);
        
    }//GEN-LAST:event_PlayGameButtonActionPerformed

    private void Vocabulary1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Vocabulary1MouseEntered
        vocab1.show(VocabularyParentPanel1, "Definition1");
        System.out.println("Panel changed to definition");
    }//GEN-LAST:event_Vocabulary1MouseEntered

    private void Definition1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Definition1MouseExited
        vocab1.show(VocabularyParentPanel1, "Vocabulary1");
        System.out.println("Panel changed to vocabulary");
    }//GEN-LAST:event_Definition1MouseExited

    private void Vocabulary2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Vocabulary2MouseEntered
        vocab2.show(VocabularyParentPanel2, "Definition2");
    }//GEN-LAST:event_Vocabulary2MouseEntered

    private void Definition2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Definition2MouseExited
        vocab2.show(VocabularyParentPanel2, "Vocabulary2");
    }//GEN-LAST:event_Definition2MouseExited

    private void Vocabulary3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Vocabulary3MouseEntered
        vocab3.show(VocabularyParentPanel3, "Definition3");
    }//GEN-LAST:event_Vocabulary3MouseEntered

    private void Definition3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Definition3MouseExited
        vocab3.show(VocabularyParentPanel3, "Vocabulary3");
    }//GEN-LAST:event_Definition3MouseExited

    private void Vocabulary4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Vocabulary4MouseEntered
        vocab4.show(VocabularyParentPanel4, "Definition4");
    }//GEN-LAST:event_Vocabulary4MouseEntered

    private void Definition4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Definition4MouseExited
        vocab4.show(VocabularyParentPanel4, "Vocabulary4");
    }//GEN-LAST:event_Definition4MouseExited

    public void setname(String uname, String fname){
        this.uname = uname;
        this.fname = fname;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnglishCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnglishCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnglishCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnglishCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnglishCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccessCoursesTitle;
    private javax.swing.JLabel AccessCoursesTitle1;
    private javax.swing.JPanel AdditionPanel;
    private javax.swing.JLabel AdditionSubtitle;
    private javax.swing.JLabel AdditionSubtitle1;
    private javax.swing.JLabel AdditionSubtitle10;
    private javax.swing.JLabel AdditionSubtitle11;
    private javax.swing.JLabel AdditionSubtitle12;
    private javax.swing.JLabel AdditionSubtitle13;
    private javax.swing.JLabel AdditionSubtitle2;
    private javax.swing.JLabel AdditionSubtitle3;
    private javax.swing.JLabel AdditionSubtitle4;
    private javax.swing.JLabel AdditionSubtitle5;
    private javax.swing.JLabel AdditionSubtitle6;
    private javax.swing.JLabel AdditionSubtitle7;
    private javax.swing.JLabel AdditionSubtitle8;
    private javax.swing.JLabel AdditionSubtitle9;
    private javax.swing.JLabel ArithmeticImg;
    private javax.swing.JLabel ArithmeticImg1;
    private javax.swing.JLabel ArithmeticImg2;
    private javax.swing.JLabel ArithmeticImg3;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel ClosePopup;
    private javax.swing.JSplitPane CourseMainBody;
    private javax.swing.JPanel CourseSelector;
    private javax.swing.JPanel Definition1;
    private javax.swing.JPanel Definition2;
    private javax.swing.JPanel Definition3;
    private javax.swing.JPanel Definition4;
    private javax.swing.JLabel Design;
    private javax.swing.JPanel DivisionPanel;
    private javax.swing.JLabel IaRTitle1;
    private javax.swing.JLabel Instruction;
    private javax.swing.JPanel Lesson1;
    private javax.swing.JButton Lesson1Button;
    private javax.swing.JPanel Lesson2;
    private javax.swing.JButton Lesson3Button;
    private javax.swing.JPanel MultiplicationPanel;
    private javax.swing.JButton PlayGameButton;
    private javax.swing.JPanel PopupWindowTop;
    private javax.swing.JPanel SelectedCourseCards;
    private javax.swing.JLabel SubstractSubtitle;
    private javax.swing.JLabel SubstractSubtitle1;
    private javax.swing.JLabel SubstractSubtitle2;
    private javax.swing.JPanel SubtractionPanel;
    private javax.swing.JPanel Vocabulary1;
    private javax.swing.JPanel Vocabulary2;
    private javax.swing.JPanel Vocabulary3;
    private javax.swing.JPanel Vocabulary4;
    private javax.swing.JPanel VocabularyParentPanel1;
    private javax.swing.JPanel VocabularyParentPanel2;
    private javax.swing.JPanel VocabularyParentPanel3;
    private javax.swing.JPanel VocabularyParentPanel4;
    private javax.swing.JPanel Welcome;
    private javax.swing.JButton WelcomeButton;
    private javax.swing.JLabel WelcomeMessage;
    // End of variables declaration//GEN-END:variables
}
