
package QuickQuirkGameLab;

import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.ImageIcon;


public class LearnerMainMenu extends javax.swing.JFrame {

    private int x;
    private int y;
    
    // Attributes for current logged in account
    private String accfname;
    private String acclname;
    private String accuname;
    private String accpass;
    private String accemail;
    private String acccoins; // This value should be changed to int when making calculations
    private String accicon;
    
    CardLayout cardLayout;
    
    
    public LearnerMainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        cardLayout = (CardLayout)(LearnerPanelCards.getLayout());
        LearnerPanelCards.add(AccessCoursesPanel, "AccessCoursesPanel");
        LearnerPanelCards.add(ShopPanel, "ShopPanel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LearnerMainMenuTop = new javax.swing.JPanel();
        CloseApplication = new javax.swing.JLabel();
        LearnerMainBody = new javax.swing.JSplitPane();
        ButtonSideBody = new javax.swing.JPanel();
        AccessCoursesButton = new javax.swing.JButton();
        ShopButton = new javax.swing.JButton();
        ProfileIcon = new javax.swing.JLabel();
        CurrentLoginName = new javax.swing.JTextField();
        CurrentCoins = new javax.swing.JTextField();
        CurrentLoginUsername = new javax.swing.JTextField();
        EditProfileButton = new javax.swing.JButton();
        LearnerPanelCards = new javax.swing.JPanel();
        ShopPanel = new javax.swing.JPanel();
        ShopTitle = new javax.swing.JLabel();
        ChemistryIconShop = new javax.swing.JLabel();
        MathsIconShop = new javax.swing.JLabel();
        PhysicsIconShop = new javax.swing.JLabel();
        PlanetIconShop = new javax.swing.JLabel();
        BuyChemistryIcon = new javax.swing.JButton();
        ChemistIcon = new javax.swing.JLabel();
        ChemistIcon1 = new javax.swing.JLabel();
        ChemistIcon2 = new javax.swing.JLabel();
        ChemistIcon3 = new javax.swing.JLabel();
        BuyPhysicsIcon = new javax.swing.JButton();
        BuyMathsIcon = new javax.swing.JButton();
        BuyPlanetIcon = new javax.swing.JButton();
        ChemistryIconShop1 = new javax.swing.JLabel();
        ChemistIcon4 = new javax.swing.JLabel();
        ChemistIcon5 = new javax.swing.JLabel();
        ChemistIcon6 = new javax.swing.JLabel();
        ChemistIcon7 = new javax.swing.JLabel();
        ChemistIcon8 = new javax.swing.JLabel();
        AccessCoursesPanel = new javax.swing.JPanel();
        AccessCoursesTitle = new javax.swing.JLabel();
        MathCoursesButton = new javax.swing.JButton();
        EnglishCoursesButton = new javax.swing.JButton();
        ChemCoursesButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PhyCoursesButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BioCoursesButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(8, 14, 44));
        setMinimumSize(new java.awt.Dimension(1300, 900));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LearnerMainMenuTop.setBackground(new java.awt.Color(85, 143, 127));
        LearnerMainMenuTop.setForeground(new java.awt.Color(85, 143, 127));
        LearnerMainMenuTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LearnerMainMenuTopMouseDragged(evt);
            }
        });
        LearnerMainMenuTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LearnerMainMenuTopMousePressed(evt);
            }
        });

        CloseApplication.setBackground(new java.awt.Color(242, 0, 0));
        CloseApplication.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        CloseApplication.setForeground(new java.awt.Color(255, 255, 255));
        CloseApplication.setText("x");
        CloseApplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CloseApplicationMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout LearnerMainMenuTopLayout = new javax.swing.GroupLayout(LearnerMainMenuTop);
        LearnerMainMenuTop.setLayout(LearnerMainMenuTopLayout);
        LearnerMainMenuTopLayout.setHorizontalGroup(
            LearnerMainMenuTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LearnerMainMenuTopLayout.createSequentialGroup()
                .addContainerGap(1256, Short.MAX_VALUE)
                .addComponent(CloseApplication)
                .addGap(16, 16, 16))
        );
        LearnerMainMenuTopLayout.setVerticalGroup(
            LearnerMainMenuTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LearnerMainMenuTopLayout.createSequentialGroup()
                .addComponent(CloseApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        getContentPane().add(LearnerMainMenuTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1302, -1));

        LearnerMainBody.setBackground(new java.awt.Color(13, 21, 61));
        LearnerMainBody.setDividerLocation(-10);
        LearnerMainBody.setDividerSize(0);
        LearnerMainBody.setForeground(new java.awt.Color(8, 14, 44));
        LearnerMainBody.setOpaque(false);

        ButtonSideBody.setBackground(new java.awt.Color(27, 47, 51));
        ButtonSideBody.setMinimumSize(new java.awt.Dimension(200, 0));
        ButtonSideBody.setPreferredSize(new java.awt.Dimension(200, 160));

        AccessCoursesButton.setBackground(new java.awt.Color(84, 129, 118));
        AccessCoursesButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        AccessCoursesButton.setForeground(new java.awt.Color(255, 255, 255));
        AccessCoursesButton.setText("<html><center>Access<br>Courses</center></html>");
        AccessCoursesButton.setBorder(null);
        AccessCoursesButton.setBorderPainted(false);
        AccessCoursesButton.setMinimumSize(new java.awt.Dimension(60, 40));
        AccessCoursesButton.setPreferredSize(new java.awt.Dimension(160, 80));
        AccessCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccessCoursesButtonActionPerformed(evt);
            }
        });

        ShopButton.setBackground(new java.awt.Color(84, 129, 118));
        ShopButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        ShopButton.setForeground(new java.awt.Color(255, 255, 255));
        ShopButton.setText("Shop");
        ShopButton.setBorder(null);
        ShopButton.setBorderPainted(false);
        ShopButton.setPreferredSize(new java.awt.Dimension(160, 80));
        ShopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShopButtonActionPerformed(evt);
            }
        });

        ProfileIcon.setBackground(new java.awt.Color(27, 47, 51));
        ProfileIcon.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ProfileIcon.setForeground(new java.awt.Color(255, 255, 255));
        ProfileIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DefaultIcon1.png"))); // NOI18N
        ProfileIcon.setText("\n");
        ProfileIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        CurrentLoginName.setEditable(false);
        CurrentLoginName.setBackground(new java.awt.Color(27, 47, 51));
        CurrentLoginName.setFont(new java.awt.Font("Bahnschrift", 0, 17)); // NOI18N
        CurrentLoginName.setForeground(new java.awt.Color(255, 255, 255));
        CurrentLoginName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CurrentLoginName.setText("Test User");
        CurrentLoginName.setBorder(null);

        CurrentCoins.setEditable(false);
        CurrentCoins.setBackground(new java.awt.Color(27, 47, 51));
        CurrentCoins.setFont(new java.awt.Font("Bahnschrift", 0, 17)); // NOI18N
        CurrentCoins.setForeground(new java.awt.Color(255, 255, 153));
        CurrentCoins.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CurrentCoins.setText("Coins");
        CurrentCoins.setBorder(null);

        CurrentLoginUsername.setEditable(false);
        CurrentLoginUsername.setBackground(new java.awt.Color(27, 47, 51));
        CurrentLoginUsername.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        CurrentLoginUsername.setForeground(new java.awt.Color(255, 255, 255));
        CurrentLoginUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CurrentLoginUsername.setText("TestUser");
        CurrentLoginUsername.setBorder(null);

        EditProfileButton.setBackground(new java.awt.Color(58, 89, 81));
        EditProfileButton.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        EditProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        EditProfileButton.setText("Edit Profile\n");
        EditProfileButton.setBorder(null);
        EditProfileButton.setBorderPainted(false);
        EditProfileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditProfileButton.setPreferredSize(new java.awt.Dimension(160, 80));
        EditProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonSideBodyLayout = new javax.swing.GroupLayout(ButtonSideBody);
        ButtonSideBody.setLayout(ButtonSideBodyLayout);
        ButtonSideBodyLayout.setHorizontalGroup(
            ButtonSideBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CurrentLoginName)
            .addComponent(CurrentCoins, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(ProfileIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CurrentLoginUsername, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(ButtonSideBodyLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(ButtonSideBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ShopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AccessCoursesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonSideBodyLayout.createSequentialGroup()
                        .addComponent(EditProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        ButtonSideBodyLayout.setVerticalGroup(
            ButtonSideBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonSideBodyLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ProfileIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CurrentLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(CurrentLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CurrentCoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(AccessCoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShopButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );

        LearnerMainBody.setLeftComponent(ButtonSideBody);

        LearnerPanelCards.setBackground(new java.awt.Color(8, 14, 44));
        LearnerPanelCards.setOpaque(false);
        LearnerPanelCards.setLayout(new java.awt.CardLayout());

        ShopPanel.setBackground(new java.awt.Color(35, 64, 69));
        ShopPanel.setPreferredSize(new java.awt.Dimension(1300, 900));

        ShopTitle.setFont(new java.awt.Font("Fredoka Medium", 0, 48)); // NOI18N
        ShopTitle.setForeground(new java.awt.Color(255, 255, 255));
        ShopTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShopTitle.setText("Welcome to the Shop!");

        ChemistryIconShop.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ChemistryIconShop.setForeground(new java.awt.Color(255, 255, 255));
        ChemistryIconShop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChemistryIconShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ChemistryIcon.png"))); // NOI18N
        ChemistryIconShop.setText("\n");
        ChemistryIconShop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        MathsIconShop.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        MathsIconShop.setForeground(new java.awt.Color(255, 255, 255));
        MathsIconShop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MathsIconShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MathsIcon.png"))); // NOI18N
        MathsIconShop.setText("\n");
        MathsIconShop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        PhysicsIconShop.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        PhysicsIconShop.setForeground(new java.awt.Color(255, 255, 255));
        PhysicsIconShop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PhysicsIconShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PhysicsIcon.png"))); // NOI18N
        PhysicsIconShop.setText("\n");
        PhysicsIconShop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        PlanetIconShop.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        PlanetIconShop.setForeground(new java.awt.Color(255, 255, 255));
        PlanetIconShop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlanetIconShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PlanetIcon.png"))); // NOI18N
        PlanetIconShop.setText("\n");
        PlanetIconShop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BuyChemistryIcon.setBackground(new java.awt.Color(98, 154, 140));
        BuyChemistryIcon.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        BuyChemistryIcon.setForeground(new java.awt.Color(255, 255, 255));
        BuyChemistryIcon.setText("Buy");
        BuyChemistryIcon.setBorder(null);
        BuyChemistryIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyChemistryIconActionPerformed(evt);
            }
        });

        ChemistIcon.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ChemistIcon.setForeground(new java.awt.Color(255, 255, 255));
        ChemistIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChemistIcon.setText("Chemistry Icon");

        ChemistIcon1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ChemistIcon1.setForeground(new java.awt.Color(255, 255, 255));
        ChemistIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChemistIcon1.setText("Physics Icon");

        ChemistIcon2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ChemistIcon2.setForeground(new java.awt.Color(255, 255, 255));
        ChemistIcon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChemistIcon2.setText("Maths Icon");

        ChemistIcon3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ChemistIcon3.setForeground(new java.awt.Color(255, 255, 255));
        ChemistIcon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChemistIcon3.setText("Planet Icon");

        BuyPhysicsIcon.setBackground(new java.awt.Color(98, 154, 140));
        BuyPhysicsIcon.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        BuyPhysicsIcon.setForeground(new java.awt.Color(255, 255, 255));
        BuyPhysicsIcon.setText("Buy");
        BuyPhysicsIcon.setBorder(null);
        BuyPhysicsIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyPhysicsIconActionPerformed(evt);
            }
        });

        BuyMathsIcon.setBackground(new java.awt.Color(98, 154, 140));
        BuyMathsIcon.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        BuyMathsIcon.setForeground(new java.awt.Color(255, 255, 255));
        BuyMathsIcon.setText("Buy");
        BuyMathsIcon.setBorder(null);
        BuyMathsIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyMathsIconActionPerformed(evt);
            }
        });

        BuyPlanetIcon.setBackground(new java.awt.Color(98, 154, 140));
        BuyPlanetIcon.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        BuyPlanetIcon.setForeground(new java.awt.Color(255, 255, 255));
        BuyPlanetIcon.setText("Buy");
        BuyPlanetIcon.setBorder(null);
        BuyPlanetIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyPlanetIconActionPerformed(evt);
            }
        });

        ChemistryIconShop1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ChemistryIconShop1.setForeground(new java.awt.Color(255, 255, 255));
        ChemistryIconShop1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChemistryIconShop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MoreComingSoon.png"))); // NOI18N
        ChemistryIconShop1.setText("\n");
        ChemistryIconShop1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ChemistIcon4.setFont(new java.awt.Font("Fredoka Medium", 0, 14)); // NOI18N
        ChemistIcon4.setForeground(new java.awt.Color(255, 255, 255));
        ChemistIcon4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChemistIcon4.setText("Coming Soon");

        ChemistIcon5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ChemistIcon5.setForeground(new java.awt.Color(255, 255, 102));
        ChemistIcon5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChemistIcon5.setText("200g");

        ChemistIcon6.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ChemistIcon6.setForeground(new java.awt.Color(255, 255, 102));
        ChemistIcon6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChemistIcon6.setText("300g");

        ChemistIcon7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ChemistIcon7.setForeground(new java.awt.Color(255, 255, 102));
        ChemistIcon7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChemistIcon7.setText("600g");

        ChemistIcon8.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ChemistIcon8.setForeground(new java.awt.Color(255, 255, 102));
        ChemistIcon8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChemistIcon8.setText("900g");

        javax.swing.GroupLayout ShopPanelLayout = new javax.swing.GroupLayout(ShopPanel);
        ShopPanel.setLayout(ShopPanelLayout);
        ShopPanelLayout.setHorizontalGroup(
            ShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ShopTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ShopPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(ShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChemistIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuyChemistryIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChemistryIconShop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChemistryIconShop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChemistIcon4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChemistIcon5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(157, 157, 157)
                .addGroup(ShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChemistIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MathsIconShop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuyPhysicsIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChemistIcon6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(191, 191, 191)
                .addGroup(ShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChemistIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PhysicsIconShop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuyMathsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChemistIcon7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(ShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PlanetIconShop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChemistIcon3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuyPlanetIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChemistIcon8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100))
        );
        ShopPanelLayout.setVerticalGroup(
            ShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ShopTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(ShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChemistryIconShop)
                    .addComponent(MathsIconShop)
                    .addComponent(PhysicsIconShop)
                    .addComponent(PlanetIconShop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChemistIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChemistIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChemistIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChemistIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(ShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(ChemistIcon6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChemistIcon7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChemistIcon8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChemistIcon5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(ShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShopPanelLayout.createSequentialGroup()
                        .addGroup(ShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BuyPhysicsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuyChemistryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(ChemistryIconShop1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChemistIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BuyPlanetIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BuyMathsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(306, Short.MAX_VALUE))
        );

        LearnerPanelCards.add(ShopPanel, "card2");

        AccessCoursesPanel.setBackground(new java.awt.Color(35, 64, 69));
        AccessCoursesPanel.setMaximumSize(new java.awt.Dimension(1100, 860));
        AccessCoursesPanel.setMinimumSize(new java.awt.Dimension(1100, 860));
        AccessCoursesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccessCoursesTitle.setFont(new java.awt.Font("Fredoka Medium", 0, 48)); // NOI18N
        AccessCoursesTitle.setForeground(new java.awt.Color(255, 255, 255));
        AccessCoursesTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessCoursesTitle.setText("Available Courses");
        AccessCoursesPanel.add(AccessCoursesTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1090, 97));

        MathCoursesButton.setBackground(new java.awt.Color(84, 129, 118));
        MathCoursesButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        MathCoursesButton.setForeground(new java.awt.Color(255, 255, 255));
        MathCoursesButton.setText("  Math Courses                                   >>");
        MathCoursesButton.setBorder(null);
        MathCoursesButton.setBorderPainted(false);
        MathCoursesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MathCoursesButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        MathCoursesButton.setMaximumSize(new java.awt.Dimension(320, 45));
        MathCoursesButton.setMinimumSize(new java.awt.Dimension(320, 45));
        MathCoursesButton.setPreferredSize(new java.awt.Dimension(320, 45));
        MathCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MathCoursesButtonActionPerformed(evt);
            }
        });
        AccessCoursesPanel.add(MathCoursesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 134, -1, -1));

        EnglishCoursesButton.setBackground(new java.awt.Color(84, 129, 118));
        EnglishCoursesButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        EnglishCoursesButton.setForeground(new java.awt.Color(255, 255, 255));
        EnglishCoursesButton.setText("  English Courses                               >>");
        EnglishCoursesButton.setBorder(null);
        EnglishCoursesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EnglishCoursesButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        EnglishCoursesButton.setMaximumSize(new java.awt.Dimension(320, 45));
        EnglishCoursesButton.setMinimumSize(new java.awt.Dimension(320, 45));
        EnglishCoursesButton.setPreferredSize(new java.awt.Dimension(320, 45));
        EnglishCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnglishCoursesButtonActionPerformed(evt);
            }
        });
        AccessCoursesPanel.add(EnglishCoursesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 134, -1, -1));

        ChemCoursesButton.setBackground(new java.awt.Color(84, 129, 118));
        ChemCoursesButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        ChemCoursesButton.setForeground(new java.awt.Color(255, 255, 255));
        ChemCoursesButton.setText("  Chemistry Courses                         >>");
        ChemCoursesButton.setBorder(null);
        ChemCoursesButton.setBorderPainted(false);
        ChemCoursesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ChemCoursesButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        ChemCoursesButton.setMaximumSize(new java.awt.Dimension(320, 45));
        ChemCoursesButton.setMinimumSize(new java.awt.Dimension(320, 45));
        ChemCoursesButton.setPreferredSize(new java.awt.Dimension(320, 45));
        ChemCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChemCoursesButtonActionPerformed(evt);
            }
        });
        AccessCoursesPanel.add(ChemCoursesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 134, -1, -1));

        jLabel2.setFont(new java.awt.Font("Fredoka", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Integers and Rational Numbers");
        AccessCoursesPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 242, 314, 45));

        jLabel4.setFont(new java.awt.Font("Fredoka", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Algebraic Equations");
        AccessCoursesPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 314, 40));

        jLabel5.setFont(new java.awt.Font("Fredoka", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Forces and Motion");
        AccessCoursesPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 310, 45));

        PhyCoursesButton.setBackground(new java.awt.Color(84, 129, 118));
        PhyCoursesButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        PhyCoursesButton.setForeground(new java.awt.Color(255, 255, 255));
        PhyCoursesButton.setText("  Physics Courses                              >>");
        PhyCoursesButton.setBorder(null);
        PhyCoursesButton.setBorderPainted(false);
        PhyCoursesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PhyCoursesButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        PhyCoursesButton.setMaximumSize(new java.awt.Dimension(320, 45));
        PhyCoursesButton.setMinimumSize(new java.awt.Dimension(320, 45));
        PhyCoursesButton.setPreferredSize(new java.awt.Dimension(320, 45));
        PhyCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhyCoursesButtonActionPerformed(evt);
            }
        });
        AccessCoursesPanel.add(PhyCoursesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel6.setFont(new java.awt.Font("Fredoka", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Arithmatic Fundamentals");
        AccessCoursesPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 191, 314, 45));

        jLabel8.setFont(new java.awt.Font("Fredoka", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Learning New Vocabularies");
        AccessCoursesPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 240, 310, 45));

        jLabel9.setFont(new java.awt.Font("Fredoka", 2, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("More Coming Soon...!");
        AccessCoursesPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 290, 310, 45));

        jLabel10.setFont(new java.awt.Font("Fredoka", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Basic Punctuation");
        AccessCoursesPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 191, 314, 45));

        jLabel11.setFont(new java.awt.Font("Fredoka", 2, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("More Coming Soon...!");
        AccessCoursesPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 314, 40));

        jLabel12.setFont(new java.awt.Font("Fredoka", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Energy");
        AccessCoursesPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 310, 45));

        jLabel13.setFont(new java.awt.Font("Fredoka", 2, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("More Coming Soon...!");
        AccessCoursesPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 310, 45));

        BioCoursesButton.setBackground(new java.awt.Color(84, 129, 118));
        BioCoursesButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        BioCoursesButton.setForeground(new java.awt.Color(255, 255, 255));
        BioCoursesButton.setText("  Biology Courses                              >>");
        BioCoursesButton.setBorder(null);
        BioCoursesButton.setBorderPainted(false);
        BioCoursesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BioCoursesButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BioCoursesButton.setMaximumSize(new java.awt.Dimension(320, 45));
        BioCoursesButton.setMinimumSize(new java.awt.Dimension(320, 45));
        BioCoursesButton.setPreferredSize(new java.awt.Dimension(320, 45));
        BioCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BioCoursesButtonActionPerformed(evt);
            }
        });
        AccessCoursesPanel.add(BioCoursesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, -1, -1));

        jLabel14.setFont(new java.awt.Font("Fredoka", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("States Of Matter");
        AccessCoursesPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 310, 45));

        jLabel16.setFont(new java.awt.Font("Fredoka", 2, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("More Coming Soon...!");
        AccessCoursesPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 310, 45));

        jLabel17.setFont(new java.awt.Font("Fredoka", 2, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("More Coming Soon...!");
        AccessCoursesPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 630, 310, 45));

        jLabel18.setFont(new java.awt.Font("Fredoka", 0, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Parts of a Plant");
        AccessCoursesPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, 310, 45));

        jLabel19.setFont(new java.awt.Font("Fredoka", 0, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Animals and Classification");
        AccessCoursesPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 310, 45));

        LearnerPanelCards.add(AccessCoursesPanel, "card3");

        LearnerMainBody.setRightComponent(LearnerPanelCards);

        getContentPane().add(LearnerMainBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1302, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseApplicationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseApplicationMouseReleased
        System.exit(0);
    }//GEN-LAST:event_CloseApplicationMouseReleased

    private void LearnerMainMenuTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnerMainMenuTopMouseDragged
        // Moves application based on cursor location
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();

        this.setLocation(x1- x, y1 - y);
    }//GEN-LAST:event_LearnerMainMenuTopMouseDragged

    private void LearnerMainMenuTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnerMainMenuTopMousePressed
        // Get current cursor location upon clicking Top
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_LearnerMainMenuTopMousePressed

    private void AccessCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccessCoursesButtonActionPerformed
        cardLayout.show(LearnerPanelCards,"AccessCoursesPanel");
        System.out.println("Panel Changed to Access Courses");
    }//GEN-LAST:event_AccessCoursesButtonActionPerformed

    private void ShopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShopButtonActionPerformed
        cardLayout.show(LearnerPanelCards,"ShopPanel");
        System.out.println("panel changed to Shop");
    }//GEN-LAST:event_ShopButtonActionPerformed

    private void BuyChemistryIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyChemistryIconActionPerformed
        buyFromShop(Integer.parseInt(this.acccoins), 200, "ChemistryIcon.png");
    }//GEN-LAST:event_BuyChemistryIconActionPerformed

    private void BuyPhysicsIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyPhysicsIconActionPerformed
        buyFromShop(Integer.parseInt(this.acccoins), 300, "PhysicsIcon.png");
    }//GEN-LAST:event_BuyPhysicsIconActionPerformed

    private void BuyMathsIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyMathsIconActionPerformed
        buyFromShop(Integer.parseInt(this.acccoins),600, "MathsIcon.png");
    }//GEN-LAST:event_BuyMathsIconActionPerformed

    private void BuyPlanetIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyPlanetIconActionPerformed
        buyFromShop(Integer.parseInt(this.acccoins), 900, "PlanetIcon.png");
    }//GEN-LAST:event_BuyPlanetIconActionPerformed

    private void EditProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileButtonActionPerformed
        // Create a new EditProfileLearner Object
        EditProfileLearner epl = new EditProfileLearner();
        epl.setVisible(true);
        epl.pack();
        epl.setLocationRelativeTo(null);
        
        epl.setTempProfile(accfname, accemail, accuname, accpass, accicon);
    }//GEN-LAST:event_EditProfileButtonActionPerformed

    private void BioCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BioCoursesButtonActionPerformed
        coursewip();
    }//GEN-LAST:event_BioCoursesButtonActionPerformed

    private void PhyCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhyCoursesButtonActionPerformed
        coursewip();
    }//GEN-LAST:event_PhyCoursesButtonActionPerformed

    private void ChemCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChemCoursesButtonActionPerformed
        ChemistryCourse cc = new ChemistryCourse();
        cc.setVisible(true);
    }//GEN-LAST:event_ChemCoursesButtonActionPerformed

    private void EnglishCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnglishCoursesButtonActionPerformed
        EnglishCourse ec = new EnglishCourse();
        ec.setVisible(true);
        ec.setname(this.accuname,this.accfname);
    }//GEN-LAST:event_EnglishCoursesButtonActionPerformed

    private void MathCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MathCoursesButtonActionPerformed
        MathsCourse mc = new MathsCourse();
        mc.setVisible(true);
        mc.setname(this.accuname, this.accfname);
    }//GEN-LAST:event_MathCoursesButtonActionPerformed

    private void currentAccount (String fname, String uname, String pass, String email, String coins, String icon){
        this.accfname = fname;
        this.accuname = uname;
        this.accpass = pass;
        this.accemail = email;
        this.acccoins = coins;
        this.accicon = icon;
        
        // Display the values on the Account Panel
        setDisplayName(fname, uname, coins, icon);
    }
    
    public void setCurrentAccount (String fname, String uname, String pass, String email, String coins, String icon){
        currentAccount(fname, uname, pass, email, coins, icon);
        
    }
    
    private void setDisplayName (String fname, String uname, String coins, String icon){
        CurrentLoginName.setText(fname);
        CurrentLoginUsername.setText(uname);
        CurrentCoins.setText(coins + "g");
        String iconPath = "src/img/" + icon + ".png";
        ProfileIcon.setIcon(new ImageIcon(iconPath));
    }
    
    private void buyFromShop(int userCoins, int price, String itemNamepng){
        userCoins = Integer.parseInt(this.acccoins);
        File inventoryFilePath = new File("Learner/" + this.accuname + "/inventory.csv");
        String item = itemNamepng.substring(0, itemNamepng.length() -4); // Name of the item
        boolean itemExists = false;
        
        // Checks if coins are enough
        if (userCoins >= price) {
            // If coins are enough, checks if item already exists
            try {
                BufferedReader br = new BufferedReader(new FileReader(inventoryFilePath));
                String line;

                while ((line = br.readLine()) != null) {
                    if (line.trim().equalsIgnoreCase(item)) {
                        itemExists = true;
                        System.out.println("Item Exists...\n"); // Debug
                        break; // Breaks if item exists
                    }
                }
                br.close();
                
                } catch (IOException e) {
                    System.out.println("Error with file path...");
                    e.printStackTrace();
                }
            
            // If item does not exist, adds it to inventory
            if (!itemExists) {
                try {
                    BufferedWriter bw = new BufferedWriter(new FileWriter(inventoryFilePath, true));
                    bw.write(item);
                    bw.newLine();
                    bw.close();
                    System.out.println("Item added to inventory: " + item); // Debug
                    
                    // After buying the item, submit coins
                    int temp = userCoins - price;
                    this.acccoins = String.valueOf(temp); // Sets new current coins
                    CurrentCoins.setText(this.acccoins + "g");
                    
                    // Updates the accountDetails file
                    try {
                        File accountDetailsFilePath = new File("Learner/" + this.accuname + "/accountDetails.csv");
                        File tempFile = new File("Learner/" + this.accuname + "/temp.csv");

                        BufferedReader accountReader = new BufferedReader(new FileReader(accountDetailsFilePath));
                        BufferedWriter tempWriter = new BufferedWriter(new FileWriter(tempFile));

                        String line;
                        int lineCount = 1;

                        while ((line = accountReader.readLine()) != null) {
                            if (lineCount == 5) {
                                tempWriter.write(this.acccoins);
                                System.out.println("Coins updated...");
                            } else {
                                tempWriter.write(line);
                            }
                            tempWriter.newLine();
                            lineCount++;
                        }

                        accountReader.close();
                        tempWriter.close();

                        // Replace old CSV file with new CSV file
                        if (accountDetailsFilePath.delete()) {
                            tempFile.renameTo(accountDetailsFilePath);
                        }
                        
                        PopupWindow successPurchase = new PopupWindow();
                        successPurchase.setVisible(true);
                        successPurchase.setMessages("Purchase Successful!","Equip your icon from your profile menu!");

                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    
                } catch (IOException e) {
                    System.out.println("Error with file path...");
                    e.printStackTrace();
                }
            } else {
                System.out.println("Item already exists in inventory: " + item);
                
                PopupWindow itmExists = new PopupWindow();
                itmExists.setVisible(true);
                itmExists.setMessages("Item owned!","You have already obtained this item!");
            }

        } else {
            System.out.println("Not enough coins to buy " + item + "!");
            
            PopupWindow notEnoughCoins = new PopupWindow();
            notEnoughCoins.setVisible(true);
            notEnoughCoins.setMessages("Insufficient Coins","Play more games to obtain more coins!");
        }
    }
    
    // Popup Methods
    private void coursewip(){
        PopupWindow cwip = new PopupWindow();
        cwip.setVisible(true);
        cwip.setMessages("Course under development!","Stay tuned and check back later to continue learning!");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearnerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearnerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearnerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearnerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearnerMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccessCoursesButton;
    private javax.swing.JPanel AccessCoursesPanel;
    private javax.swing.JLabel AccessCoursesTitle;
    private javax.swing.JButton BioCoursesButton;
    private javax.swing.JPanel ButtonSideBody;
    private javax.swing.JButton BuyChemistryIcon;
    private javax.swing.JButton BuyMathsIcon;
    private javax.swing.JButton BuyPhysicsIcon;
    private javax.swing.JButton BuyPlanetIcon;
    private javax.swing.JButton ChemCoursesButton;
    private javax.swing.JLabel ChemistIcon;
    private javax.swing.JLabel ChemistIcon1;
    private javax.swing.JLabel ChemistIcon2;
    private javax.swing.JLabel ChemistIcon3;
    private javax.swing.JLabel ChemistIcon4;
    private javax.swing.JLabel ChemistIcon5;
    private javax.swing.JLabel ChemistIcon6;
    private javax.swing.JLabel ChemistIcon7;
    private javax.swing.JLabel ChemistIcon8;
    private javax.swing.JLabel ChemistryIconShop;
    private javax.swing.JLabel ChemistryIconShop1;
    private javax.swing.JLabel CloseApplication;
    private javax.swing.JTextField CurrentCoins;
    private javax.swing.JTextField CurrentLoginName;
    private javax.swing.JTextField CurrentLoginUsername;
    private javax.swing.JButton EditProfileButton;
    private javax.swing.JButton EnglishCoursesButton;
    private javax.swing.JSplitPane LearnerMainBody;
    private javax.swing.JPanel LearnerMainMenuTop;
    private javax.swing.JPanel LearnerPanelCards;
    private javax.swing.JButton MathCoursesButton;
    private javax.swing.JLabel MathsIconShop;
    private javax.swing.JButton PhyCoursesButton;
    private javax.swing.JLabel PhysicsIconShop;
    private javax.swing.JLabel PlanetIconShop;
    private javax.swing.JLabel ProfileIcon;
    private javax.swing.JButton ShopButton;
    private javax.swing.JPanel ShopPanel;
    private javax.swing.JLabel ShopTitle;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
