package QuickQuirkGameLab;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFrame;

public class LoginPage extends javax.swing.JFrame {

    private int x; // Needed to make application draggable
    private int y; // Needed to make application draggable
    public LoginPage() {
        initComponents();
        this.setLocationRelativeTo(null); // Puts the application in the center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminLoginTop = new javax.swing.JPanel();
        CloseApplication = new javax.swing.JLabel();
        AdminLoginBody = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        LoginUsernameInput = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        RegistrationButton = new javax.swing.JButton();
        LoginPasswordInput = new javax.swing.JPasswordField();
        LoginFeedbackOutput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(8, 14, 44));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 0));
        setUndecorated(true);

        AdminLoginTop.setBackground(new java.awt.Color(85, 143, 127));
        AdminLoginTop.setForeground(new java.awt.Color(85, 143, 127));
        AdminLoginTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                AdminLoginTopMouseDragged(evt);
            }
        });
        AdminLoginTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AdminLoginTopMousePressed(evt);
            }
        });

        CloseApplication.setBackground(new java.awt.Color(242, 0, 0));
        CloseApplication.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        CloseApplication.setForeground(new java.awt.Color(255, 255, 255));
        CloseApplication.setText("x");
        CloseApplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CloseApplicationMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout AdminLoginTopLayout = new javax.swing.GroupLayout(AdminLoginTop);
        AdminLoginTop.setLayout(AdminLoginTopLayout);
        AdminLoginTopLayout.setHorizontalGroup(
            AdminLoginTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminLoginTopLayout.createSequentialGroup()
                .addContainerGap(767, Short.MAX_VALUE)
                .addComponent(CloseApplication)
                .addGap(16, 16, 16))
        );
        AdminLoginTopLayout.setVerticalGroup(
            AdminLoginTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLoginTopLayout.createSequentialGroup()
                .addComponent(CloseApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        AdminLoginBody.setBackground(new java.awt.Color(35, 64, 69));

        WelcomeLabel.setFont(new java.awt.Font("Feather Bold", 1, 36)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeLabel.setText("QuickQuirk GameLab!");

        PasswordLabel.setFont(new java.awt.Font("Fredoka", 0, 24)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(242, 242, 242));
        PasswordLabel.setText("Password:");

        UsernameLabel.setFont(new java.awt.Font("Fredoka", 0, 24)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(242, 242, 242));
        UsernameLabel.setText("Username:");

        LoginUsernameInput.setBackground(new java.awt.Color(35, 64, 69));
        LoginUsernameInput.setFont(new java.awt.Font("Fredoka", 0, 24)); // NOI18N
        LoginUsernameInput.setForeground(new java.awt.Color(255, 255, 255));
        LoginUsernameInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(244, 244, 244)));
        LoginUsernameInput.setCaretColor(new java.awt.Color(255, 255, 255));
        LoginUsernameInput.setMargin(new java.awt.Insets(0, 0, 2, 0));

        LoginButton.setBackground(new java.awt.Color(84, 129, 118));
        LoginButton.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.setBorder(null);
        LoginButton.setBorderPainted(false);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        RegistrationButton.setBackground(new java.awt.Color(84, 129, 118));
        RegistrationButton.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        RegistrationButton.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationButton.setText("Create a Free Learner Account");
        RegistrationButton.setBorder(null);
        RegistrationButton.setBorderPainted(false);
        RegistrationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RegistrationButtonMouseReleased(evt);
            }
        });

        LoginPasswordInput.setBackground(new java.awt.Color(35, 64, 69));
        LoginPasswordInput.setFont(new java.awt.Font("Fredoka", 0, 24)); // NOI18N
        LoginPasswordInput.setForeground(new java.awt.Color(255, 255, 255));
        LoginPasswordInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        LoginPasswordInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginPasswordInputKeyPressed(evt);
            }
        });

        LoginFeedbackOutput.setBackground(new java.awt.Color(35, 64, 69));
        LoginFeedbackOutput.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LoginFeedbackOutput.setForeground(new java.awt.Color(255, 255, 102));
        LoginFeedbackOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LoginFeedbackOutput.setBorder(null);
        LoginFeedbackOutput.setCaretColor(new java.awt.Color(255, 255, 255));
        LoginFeedbackOutput.setMargin(new java.awt.Insets(0, 0, 2, 0));

        javax.swing.GroupLayout AdminLoginBodyLayout = new javax.swing.GroupLayout(AdminLoginBody);
        AdminLoginBody.setLayout(AdminLoginBodyLayout);
        AdminLoginBodyLayout.setHorizontalGroup(
            AdminLoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WelcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LoginFeedbackOutput, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(AdminLoginBodyLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(AdminLoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AdminLoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LoginPasswordInput, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(LoginUsernameInput))
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(AdminLoginBodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AdminLoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegistrationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdminLoginBodyLayout.setVerticalGroup(
            AdminLoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLoginBodyLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(AdminLoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel)
                    .addComponent(LoginUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdminLoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoginPasswordInput))
                .addGap(32, 32, 32)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginFeedbackOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminLoginTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AdminLoginBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AdminLoginTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AdminLoginBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void AdminLoginTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLoginTopMouseDragged
        // Moves application based on cursor location
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();
        
        this.setLocation(x1- x, y1 - y);
    }//GEN-LAST:event_AdminLoginTopMouseDragged

    private void CloseApplicationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseApplicationMouseReleased
        System.exit(0);
    }//GEN-LAST:event_CloseApplicationMouseReleased

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        login();
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void RegistrationButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrationButtonMouseReleased
        RegistrationPage1 reg = new RegistrationPage1();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_RegistrationButtonMouseReleased

    private void AdminLoginTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLoginTopMousePressed
        // Get current cursor location upon clicking Top
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_AdminLoginTopMousePressed

    private void LoginPasswordInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginPasswordInputKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_LoginPasswordInputKeyPressed
    
    public void setFeedbackOutput(String text){
        LoginFeedbackOutput.setText(text);
    }
    
    private void login(){
        String username = LoginUsernameInput.getText();
        String password = new String(LoginPasswordInput.getPassword());

        String filepath = "usermasterlist.csv";
        // Format: Full name, Username, Password, Email, Role
        boolean found = false;

        try (BufferedReader br = new BufferedReader(new FileReader(filepath))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] values = line.split(",");

                if (values.length >= 5) {
                    String csvUsername = values[1].replace("\"", "").trim();
                    String csvPassword = values[2].replace("\"", "").trim();
                    String role = values[4];

                    if (csvUsername.equals(username) && csvPassword.equals(password)) {
                        found = true;
                        if (role.equalsIgnoreCase("Educator")) {
                            
                            System.out.println("Logging in as Educator"); // Debug
                            
                            // Call Educator menu
                            EducatorMainMenu emm = new EducatorMainMenu();
                            emm.setVisible(true);
                            emm.setDefaultCloseOperation(EXIT_ON_CLOSE);
                            this.dispose();
                            
                            File accountDetails = new File("Educator/" + username + "/accountDetails.csv");

                            try {
                                BufferedReader reader = new BufferedReader(new FileReader(accountDetails));

                                // Read each line one by one
                                String fname = reader.readLine();
                                String uname = reader.readLine();
                                String pass = reader.readLine();
                                String email = reader.readLine();
                                
                                reader.close();

                                System.out.println("Loaded account details successfully!"); // Debug
                                System.out.println("First Name: " + fname);
                                System.out.println("Username: " + uname);
                                System.out.println("Password: " + pass);
                                System.out.println("Email: " + email);
                                
                                // Set the account details on the main menu
                                emm.setCurrentAccount(fname, uname, pass, email);

                            } catch (IOException e) {
                                e.printStackTrace();
                            }
                            
                            
                        } else if (role.equalsIgnoreCase("Learner")) {
                            
                            System.out.println("Logging in as Learner"); // Debug
                           
                            // Call Learner Menu here
                            LearnerMainMenu lmm = new LearnerMainMenu();
                            lmm.setVisible(true);
                            //lmm.pack();
                            lmm.setDefaultCloseOperation(EXIT_ON_CLOSE);
                            this.dispose();
                            
                            File accountDetails = new File("Learner/" + username + "/accountDetails.csv");

                            try {
                                BufferedReader reader = new BufferedReader(new FileReader(accountDetails));

                                // Read each line one by one
                                String fname = reader.readLine();
                                String uname = reader.readLine();
                                String pass = reader.readLine();
                                String email = reader.readLine();
                                String coins = reader.readLine(); // This is in string format
                                String icon = reader.readLine();

                                reader.close();

                                System.out.println("Loaded account details successfully!"); // Debug
                                System.out.println("First Name: " + fname);
                                System.out.println("Username: " + uname);
                                System.out.println("Password: " + pass);
                                System.out.println("Email: " + email);
                                System.out.println("Coins: " + coins); // Note: This is in string format
                                System.out.println("Current Icon: " + icon);
                                
                                // Set the account details on the main menu
                                lmm.setCurrentAccount(fname, uname, pass, email, coins, icon);

                            } catch (IOException e) {
                                e.printStackTrace();
                            }
                            
                            
                        } else {
                            // Not supposed to happen, debug
                            System.out.println("Logging into " + role);
                        }
                        break;
                    }
                }
            }
            if (!found) {
                System.out.println("Invalid username or password.");
                LoginFeedbackOutput.setText("Invalid username or password");
                PopupWindow invUnamePass = new PopupWindow();
                invUnamePass.setVisible(true);
                invUnamePass.setMessages("Invalid username or password","Please check your credentials and try again");
            }
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("Error reading CSV file.");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminLoginBody;
    private javax.swing.JPanel AdminLoginTop;
    private javax.swing.JLabel CloseApplication;
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextField LoginFeedbackOutput;
    private javax.swing.JPasswordField LoginPasswordInput;
    private javax.swing.JTextField LoginUsernameInput;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton RegistrationButton;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables
}
