package QuickQuirkGameLab;

import java.awt.CardLayout;

public class MathsCourse extends javax.swing.JFrame {

    private int x;
    private int y;
    private String uname; // This needs to be passed on to the game
    private String fname;
    
    CardLayout cardlayout;
    
    public MathsCourse() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        cardlayout = (CardLayout)(SelectedCourseCards.getLayout());
        SelectedCourseCards.add(Welcome, "Welcome");
        SelectedCourseCards.add(Lesson1, "Lesson1");
        SelectedCourseCards.add(Lesson2, "Lesson2");
        SelectedCourseCards.add(Lesson3, "Lesson3");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopupWindowTop = new javax.swing.JPanel();
        ClosePopup = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        CourseMainBody = new javax.swing.JSplitPane();
        CourseSelector = new javax.swing.JPanel();
        WelcomeButton = new javax.swing.JButton();
        PlayGameButton = new javax.swing.JButton();
        Lesson1Button = new javax.swing.JButton();
        Lesson2Button = new javax.swing.JButton();
        Lesson3Button = new javax.swing.JButton();
        SelectedCourseCards = new javax.swing.JPanel();
        Welcome = new javax.swing.JPanel();
        AccessCoursesTitle = new javax.swing.JLabel();
        WelcomeMessage = new javax.swing.JLabel();
        Instruction = new javax.swing.JLabel();
        Design = new javax.swing.JLabel();
        Lesson1 = new javax.swing.JPanel();
        AccessCoursesTitle1 = new javax.swing.JLabel();
        AdditionPanel = new javax.swing.JPanel();
        AdditionSubtitle = new javax.swing.JLabel();
        AdditionSubtitle1 = new javax.swing.JLabel();
        SubtractionPanel = new javax.swing.JPanel();
        SubstractSubtitle = new javax.swing.JLabel();
        AdditionSubtitle3 = new javax.swing.JLabel();
        MultiplicationPanel = new javax.swing.JPanel();
        SubstractSubtitle1 = new javax.swing.JLabel();
        AdditionSubtitle4 = new javax.swing.JLabel();
        DivisionPanel = new javax.swing.JPanel();
        SubstractSubtitle2 = new javax.swing.JLabel();
        AdditionSubtitle5 = new javax.swing.JLabel();
        ArithmeticImg = new javax.swing.JLabel();
        ArithmeticImg1 = new javax.swing.JLabel();
        ArithmeticImg2 = new javax.swing.JLabel();
        ArithmeticImg3 = new javax.swing.JLabel();
        Lesson2 = new javax.swing.JPanel();
        IaRTitle = new javax.swing.JLabel();
        IntegersPanel = new javax.swing.JPanel();
        AdditionSubtitle2 = new javax.swing.JLabel();
        AdditionSubtitle6 = new javax.swing.JLabel();
        IntegersPanel1 = new javax.swing.JPanel();
        AdditionSubtitle7 = new javax.swing.JLabel();
        AdditionSubtitle8 = new javax.swing.JLabel();
        IntegersPanel2 = new javax.swing.JPanel();
        AdditionSubtitle9 = new javax.swing.JLabel();
        AdditionSubtitle10 = new javax.swing.JLabel();
        ThermometerImage = new javax.swing.JLabel();
        IntegersPanel3 = new javax.swing.JPanel();
        AdditionSubtitle11 = new javax.swing.JLabel();
        AdditionSubtitle12 = new javax.swing.JLabel();
        Lesson3 = new javax.swing.JPanel();
        IaRTitle1 = new javax.swing.JLabel();
        EquationFramework = new javax.swing.JLabel();
        IntegersPanel5 = new javax.swing.JPanel();
        AdditionSubtitle15 = new javax.swing.JLabel();
        AdditionSubtitle16 = new javax.swing.JLabel();
        AdditionPanel1 = new javax.swing.JPanel();
        AdditionSubtitle18 = new javax.swing.JLabel();
        AdditionPanel2 = new javax.swing.JPanel();
        AdditionSubtitle19 = new javax.swing.JLabel();
        AdditionPanel3 = new javax.swing.JPanel();
        AdditionSubtitle20 = new javax.swing.JLabel();
        IntegersPanel6 = new javax.swing.JPanel();
        AdditionSubtitle17 = new javax.swing.JLabel();
        AdditionSubtitle21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);

        PopupWindowTop.setBackground(new java.awt.Color(85, 143, 127));
        PopupWindowTop.setForeground(new java.awt.Color(85, 143, 127));
        PopupWindowTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PopupWindowTopMouseDragged(evt);
            }
        });
        PopupWindowTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PopupWindowTopMousePressed(evt);
            }
        });

        ClosePopup.setBackground(new java.awt.Color(242, 0, 0));
        ClosePopup.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        ClosePopup.setForeground(new java.awt.Color(255, 255, 255));
        ClosePopup.setText("x");
        ClosePopup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ClosePopupMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout PopupWindowTopLayout = new javax.swing.GroupLayout(PopupWindowTop);
        PopupWindowTop.setLayout(PopupWindowTopLayout);
        PopupWindowTopLayout.setHorizontalGroup(
            PopupWindowTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PopupWindowTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ClosePopup)
                .addGap(16, 16, 16))
        );
        PopupWindowTopLayout.setVerticalGroup(
            PopupWindowTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopupWindowTopLayout.createSequentialGroup()
                .addComponent(ClosePopup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        Background.setBackground(new java.awt.Color(230, 241, 231));

        CourseMainBody.setDividerLocation(-10);
        CourseMainBody.setDividerSize(0);

        CourseSelector.setBackground(new java.awt.Color(27, 47, 51));
        CourseSelector.setMaximumSize(new java.awt.Dimension(200, 538));
        CourseSelector.setMinimumSize(new java.awt.Dimension(200, 538));
        CourseSelector.setPreferredSize(new java.awt.Dimension(200, 538));

        WelcomeButton.setBackground(new java.awt.Color(84, 129, 118));
        WelcomeButton.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        WelcomeButton.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeButton.setText("Welcome to Maths!");
        WelcomeButton.setBorder(null);
        WelcomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WelcomeButtonActionPerformed(evt);
            }
        });

        PlayGameButton.setBackground(new java.awt.Color(255, 255, 102));
        PlayGameButton.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        PlayGameButton.setText("Play Game!\n");
        PlayGameButton.setBorder(null);
        PlayGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayGameButtonActionPerformed(evt);
            }
        });

        Lesson1Button.setBackground(new java.awt.Color(84, 129, 118));
        Lesson1Button.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        Lesson1Button.setForeground(new java.awt.Color(255, 255, 255));
        Lesson1Button.setText("Arthmetic Fundamentals");
        Lesson1Button.setBorder(null);
        Lesson1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson1ButtonActionPerformed(evt);
            }
        });

        Lesson2Button.setBackground(new java.awt.Color(84, 129, 118));
        Lesson2Button.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        Lesson2Button.setForeground(new java.awt.Color(255, 255, 255));
        Lesson2Button.setText("<html><center>Integers and Rational Numbers</center></html>");
        Lesson2Button.setBorder(null);
        Lesson2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson2ButtonActionPerformed(evt);
            }
        });

        Lesson3Button.setBackground(new java.awt.Color(84, 129, 118));
        Lesson3Button.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        Lesson3Button.setForeground(new java.awt.Color(255, 255, 255));
        Lesson3Button.setText("<html><center>Algebraic Equations</center></html>");
        Lesson3Button.setBorder(null);
        Lesson3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson3ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CourseSelectorLayout = new javax.swing.GroupLayout(CourseSelector);
        CourseSelector.setLayout(CourseSelectorLayout);
        CourseSelectorLayout.setHorizontalGroup(
            CourseSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CourseSelectorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(CourseSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lesson3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lesson2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lesson1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlayGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WelcomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        CourseSelectorLayout.setVerticalGroup(
            CourseSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CourseSelectorLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(WelcomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lesson1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lesson2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lesson3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(PlayGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        CourseMainBody.setLeftComponent(CourseSelector);

        SelectedCourseCards.setBackground(new java.awt.Color(230, 241, 231));
        SelectedCourseCards.setLayout(new java.awt.CardLayout());

        Welcome.setBackground(new java.awt.Color(230, 241, 231));
        Welcome.setMaximumSize(new java.awt.Dimension(600, 538));
        Welcome.setMinimumSize(new java.awt.Dimension(600, 538));
        Welcome.setPreferredSize(new java.awt.Dimension(600, 538));

        AccessCoursesTitle.setFont(new java.awt.Font("Fredoka Medium", 1, 24)); // NOI18N
        AccessCoursesTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessCoursesTitle.setText("Welcome to the world of numbers and logic!");

        WelcomeMessage.setBackground(new java.awt.Color(235, 246, 236));
        WelcomeMessage.setFont(new java.awt.Font("Fredoka", 0, 18)); // NOI18N
        WelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeMessage.setText("<html><center>In this course, you'll learn to master the basics of math, play with numbers, and solve puzzles that sharpen your brain.<br>Get ready to explore the magic of math in everyday life!</center></html>");

        Instruction.setBackground(new java.awt.Color(235, 246, 236));
        Instruction.setFont(new java.awt.Font("Fredoka", 0, 18)); // NOI18N
        Instruction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Instruction.setText("<html><center>Cick on a course on the left to start learning!</center></html>");

        Design.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DesignMath1.png"))); // NOI18N

        javax.swing.GroupLayout WelcomeLayout = new javax.swing.GroupLayout(Welcome);
        Welcome.setLayout(WelcomeLayout);
        WelcomeLayout.setHorizontalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccessCoursesTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
            .addComponent(WelcomeMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(Design, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Instruction)
                .addContainerGap())
        );
        WelcomeLayout.setVerticalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(AccessCoursesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Instruction, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Design, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SelectedCourseCards.add(Welcome, "card2");

        Lesson1.setBackground(new java.awt.Color(230, 241, 231));
        Lesson1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccessCoursesTitle1.setFont(new java.awt.Font("Fredoka Medium", 1, 24)); // NOI18N
        AccessCoursesTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessCoursesTitle1.setText("Arithmetic Fundamentals");
        Lesson1.add(AccessCoursesTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 590, 70));

        AdditionPanel.setBackground(new java.awt.Color(255, 255, 255));
        AdditionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        AdditionSubtitle.setText("Addition (+)");
        AdditionPanel.add(AdditionSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        AdditionSubtitle1.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle1.setText("<html>Addition is when you put things together to find out how many you have in total.</html>");
        AdditionPanel.add(AdditionSubtitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 60));

        Lesson1.add(AdditionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, 110));

        SubtractionPanel.setBackground(new java.awt.Color(255, 255, 255));
        SubtractionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubstractSubtitle.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        SubstractSubtitle.setText("Division (÷)");
        SubtractionPanel.add(SubstractSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        AdditionSubtitle3.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle3.setText("<html>Division is just a way of sharing or splitting things equally</html>");
        SubtractionPanel.add(AdditionSubtitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 50));

        Lesson1.add(SubtractionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 220, 100));

        MultiplicationPanel.setBackground(new java.awt.Color(255, 255, 255));
        MultiplicationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubstractSubtitle1.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        SubstractSubtitle1.setText("Substract (-)");
        MultiplicationPanel.add(SubstractSubtitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        AdditionSubtitle4.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle4.setText("<html>Subtraction is just taking away something from something else</html>");
        MultiplicationPanel.add(AdditionSubtitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 40));

        Lesson1.add(MultiplicationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 220, 100));

        DivisionPanel.setBackground(new java.awt.Color(255, 255, 255));
        DivisionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubstractSubtitle2.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        SubstractSubtitle2.setText("Multiplication (x)");
        DivisionPanel.add(SubstractSubtitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        AdditionSubtitle5.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle5.setText("<html>Multiplication is just a faster way of adding the same number over and over</html>");
        DivisionPanel.add(AdditionSubtitle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 60));

        Lesson1.add(DivisionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 220, 100));

        ArithmeticImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AdditionExample.png"))); // NOI18N
        Lesson1.add(ArithmeticImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 280, 110));

        ArithmeticImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SubstractionExample.png"))); // NOI18N
        Lesson1.add(ArithmeticImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 280, 100));

        ArithmeticImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MultiplicationExample.png"))); // NOI18N
        Lesson1.add(ArithmeticImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 280, 100));

        ArithmeticImg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DivisionExample.png"))); // NOI18N
        Lesson1.add(ArithmeticImg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 280, 100));

        SelectedCourseCards.add(Lesson1, "card3");

        Lesson2.setBackground(new java.awt.Color(230, 241, 231));

        IaRTitle.setFont(new java.awt.Font("Fredoka Medium", 1, 24)); // NOI18N
        IaRTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IaRTitle.setText("Integers and Rational Numbers");

        IntegersPanel.setBackground(new java.awt.Color(255, 255, 255));
        IntegersPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle2.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        AdditionSubtitle2.setText("Rational Numbers");
        IntegersPanel.add(AdditionSubtitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        AdditionSubtitle6.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle6.setText("<html>These are any numbers that can be written as a fraction, such as ½, or ¾.</html>");
        IntegersPanel.add(AdditionSubtitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 60));

        IntegersPanel1.setBackground(new java.awt.Color(255, 255, 255));
        IntegersPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle7.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        AdditionSubtitle7.setText("Whole Numbers");
        IntegersPanel1.add(AdditionSubtitle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        AdditionSubtitle8.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle8.setText("<html>Whole numbers are non-decimal and positive numbers.</html>");
        IntegersPanel1.add(AdditionSubtitle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 60));

        IntegersPanel2.setBackground(new java.awt.Color(255, 255, 255));
        IntegersPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle9.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        AdditionSubtitle9.setText("Irrational Numbers");
        IntegersPanel2.add(AdditionSubtitle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 20));

        AdditionSubtitle10.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle10.setText("<html>These are numbers that can be written as fractions but the decimal counterpart does not end.</html>");
        IntegersPanel2.add(AdditionSubtitle10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 70));

        ThermometerImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Thermometer.png"))); // NOI18N

        IntegersPanel3.setBackground(new java.awt.Color(255, 255, 255));
        IntegersPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle11.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        AdditionSubtitle11.setText("Integers");
        IntegersPanel3.add(AdditionSubtitle11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        AdditionSubtitle12.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle12.setText("<html>Integers are any numbers <b> without </b> decimals that can be positive, negative or zero.</html>");
        IntegersPanel3.add(AdditionSubtitle12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 60));

        javax.swing.GroupLayout Lesson2Layout = new javax.swing.GroupLayout(Lesson2);
        Lesson2.setLayout(Lesson2Layout);
        Lesson2Layout.setHorizontalGroup(
            Lesson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lesson2Layout.createSequentialGroup()
                .addGroup(Lesson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Lesson2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(IaRTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Lesson2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(IntegersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(IntegersPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Lesson2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(IntegersPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(IntegersPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Lesson2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(ThermometerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4))
        );
        Lesson2Layout.setVerticalGroup(
            Lesson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lesson2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(IaRTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(Lesson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IntegersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IntegersPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(Lesson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IntegersPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IntegersPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(ThermometerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        SelectedCourseCards.add(Lesson2, "card4");

        Lesson3.setBackground(new java.awt.Color(230, 241, 231));
        Lesson3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IaRTitle1.setFont(new java.awt.Font("Fredoka Medium", 1, 24)); // NOI18N
        IaRTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IaRTitle1.setText("Algebraic Equations");
        Lesson3.add(IaRTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 590, 70));

        EquationFramework.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ALGE.png"))); // NOI18N
        EquationFramework.setPreferredSize(new java.awt.Dimension(40, 16));
        Lesson3.add(EquationFramework, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 260, 60));

        IntegersPanel5.setBackground(new java.awt.Color(255, 255, 255));
        IntegersPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle15.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        AdditionSubtitle15.setText("How to find x");
        IntegersPanel5.add(AdditionSubtitle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        AdditionSubtitle16.setFont(new java.awt.Font("Fredoka", 0, 12)); // NOI18N
        AdditionSubtitle16.setText("<html>Isolate the variable x. To do this, put all numbers on one side and x by itself on the other side.<br><br>\nRule 1: When putting a number with plus or minus on the right hand side, change the plus sign to be minus sign (or vice versa), so your equation becomes:<br><br>\n3x = 16 <b>- 4</b> which is 3x = 12<br><br> \nRule 2: When putting a number that is multiplying or dividing by a variable to the other side, change the multiplication sign to division Oor vice versa), so your equation becomes:<br><br>\nx = 12/3 which is x = 4<br><br> \nSo for this equation, <b> x stands for 4</b></html>");
        IntegersPanel5.add(AdditionSubtitle16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 530, 210));

        Lesson3.add(IntegersPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 550, 250));

        AdditionPanel1.setBackground(new java.awt.Color(255, 255, 255));
        AdditionPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle18.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle18.setText("<html><b>Plus</b> 4.</html>");
        AdditionPanel1.add(AdditionSubtitle18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        Lesson3.add(AdditionPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 60, 70));

        AdditionPanel2.setBackground(new java.awt.Color(255, 255, 255));
        AdditionPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle19.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle19.setText("<html>Gives 16</html>");
        AdditionPanel2.add(AdditionSubtitle19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        Lesson3.add(AdditionPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 70, 70));

        AdditionPanel3.setBackground(new java.awt.Color(255, 255, 255));
        AdditionPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle20.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle20.setText("<html><b>3x</b> means 3 <b>multiplied<br>by</b> x.</html>");
        AdditionPanel3.add(AdditionSubtitle20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 50));

        Lesson3.add(AdditionPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 100, 70));

        IntegersPanel6.setBackground(new java.awt.Color(255, 255, 255));
        IntegersPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle17.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        AdditionSubtitle17.setText("What is it?");
        IntegersPanel6.add(AdditionSubtitle17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        AdditionSubtitle21.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle21.setText("<html>These are math sentences that contain<br><br>\n- Equal Sign (=) <br>\n- Numbers <br>\n- Letters (called variables) <br><br>\nYour job is to find out what the letter stands for!</html>");
        IntegersPanel6.add(AdditionSubtitle21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 170));

        Lesson3.add(IntegersPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, 210));

        SelectedCourseCards.add(Lesson3, "card5");

        CourseMainBody.setRightComponent(SelectedCourseCards);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CourseMainBody)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CourseMainBody)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PopupWindowTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PopupWindowTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClosePopupMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosePopupMouseReleased
        this.dispose();
    }//GEN-LAST:event_ClosePopupMouseReleased

    private void PopupWindowTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopupWindowTopMouseDragged
        // Moves application based on cursor location
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();

        this.setLocation(x1- x, y1 - y);
    }//GEN-LAST:event_PopupWindowTopMouseDragged

    private void PopupWindowTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopupWindowTopMousePressed
        // Get current cursor location upon clicking Top
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_PopupWindowTopMousePressed

    private void WelcomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WelcomeButtonActionPerformed
        cardlayout.show(SelectedCourseCards, "Welcome");
        System.out.println("Panel Changed to Welcome");
    }//GEN-LAST:event_WelcomeButtonActionPerformed

    private void Lesson1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson1ButtonActionPerformed
        cardlayout.show(SelectedCourseCards, "Lesson1");
        System.out.println("Panel Changed to L1");
    }//GEN-LAST:event_Lesson1ButtonActionPerformed

    private void Lesson2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson2ButtonActionPerformed
        cardlayout.show(SelectedCourseCards, "Lesson2");
        System.out.println("Panel Changed to L2");
    }//GEN-LAST:event_Lesson2ButtonActionPerformed

    private void Lesson3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson3ButtonActionPerformed
        cardlayout.show(SelectedCourseCards, "Lesson3");
        System.out.println("Panel Changed to L3");
    }//GEN-LAST:event_Lesson3ButtonActionPerformed

    private void PlayGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayGameButtonActionPerformed
        this.dispose();
        MathGame mg = new MathGame();
        mg.setname(this.uname, this.fname);
        mg.setVisible(true);
    }//GEN-LAST:event_PlayGameButtonActionPerformed

    public void setname(String uname, String fname){
        this.uname = uname;
        this.fname = fname;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathsCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathsCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathsCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathsCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathsCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccessCoursesTitle;
    private javax.swing.JLabel AccessCoursesTitle1;
    private javax.swing.JPanel AdditionPanel;
    private javax.swing.JPanel AdditionPanel1;
    private javax.swing.JPanel AdditionPanel2;
    private javax.swing.JPanel AdditionPanel3;
    private javax.swing.JLabel AdditionSubtitle;
    private javax.swing.JLabel AdditionSubtitle1;
    private javax.swing.JLabel AdditionSubtitle10;
    private javax.swing.JLabel AdditionSubtitle11;
    private javax.swing.JLabel AdditionSubtitle12;
    private javax.swing.JLabel AdditionSubtitle15;
    private javax.swing.JLabel AdditionSubtitle16;
    private javax.swing.JLabel AdditionSubtitle17;
    private javax.swing.JLabel AdditionSubtitle18;
    private javax.swing.JLabel AdditionSubtitle19;
    private javax.swing.JLabel AdditionSubtitle2;
    private javax.swing.JLabel AdditionSubtitle20;
    private javax.swing.JLabel AdditionSubtitle21;
    private javax.swing.JLabel AdditionSubtitle3;
    private javax.swing.JLabel AdditionSubtitle4;
    private javax.swing.JLabel AdditionSubtitle5;
    private javax.swing.JLabel AdditionSubtitle6;
    private javax.swing.JLabel AdditionSubtitle7;
    private javax.swing.JLabel AdditionSubtitle8;
    private javax.swing.JLabel AdditionSubtitle9;
    private javax.swing.JLabel ArithmeticImg;
    private javax.swing.JLabel ArithmeticImg1;
    private javax.swing.JLabel ArithmeticImg2;
    private javax.swing.JLabel ArithmeticImg3;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel ClosePopup;
    private javax.swing.JSplitPane CourseMainBody;
    private javax.swing.JPanel CourseSelector;
    private javax.swing.JLabel Design;
    private javax.swing.JPanel DivisionPanel;
    private javax.swing.JLabel EquationFramework;
    private javax.swing.JLabel IaRTitle;
    private javax.swing.JLabel IaRTitle1;
    private javax.swing.JLabel Instruction;
    private javax.swing.JPanel IntegersPanel;
    private javax.swing.JPanel IntegersPanel1;
    private javax.swing.JPanel IntegersPanel2;
    private javax.swing.JPanel IntegersPanel3;
    private javax.swing.JPanel IntegersPanel5;
    private javax.swing.JPanel IntegersPanel6;
    private javax.swing.JPanel Lesson1;
    private javax.swing.JButton Lesson1Button;
    private javax.swing.JPanel Lesson2;
    private javax.swing.JButton Lesson2Button;
    private javax.swing.JPanel Lesson3;
    private javax.swing.JButton Lesson3Button;
    private javax.swing.JPanel MultiplicationPanel;
    private javax.swing.JButton PlayGameButton;
    private javax.swing.JPanel PopupWindowTop;
    private javax.swing.JPanel SelectedCourseCards;
    private javax.swing.JLabel SubstractSubtitle;
    private javax.swing.JLabel SubstractSubtitle1;
    private javax.swing.JLabel SubstractSubtitle2;
    private javax.swing.JPanel SubtractionPanel;
    private javax.swing.JLabel ThermometerImage;
    private javax.swing.JPanel Welcome;
    private javax.swing.JButton WelcomeButton;
    private javax.swing.JLabel WelcomeMessage;
    // End of variables declaration//GEN-END:variables
}
