
package QuickQuirkGameLab;

import java.awt.CardLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import javax.swing.table.DefaultTableModel;


public class MathGame extends javax.swing.JFrame {
    
    private String uname;
    private String fname;
    private int rank;
    
    // User input for game
    private String n1 = "";
    private String n2 = "";
    private boolean minus; // Negative answer
    private String answer; // Concatenation of n1 + n2
    private String corrAns; // Answer of the question
    
    // Scoring
    int score = 0, corrAnsCount = 0, wroAnsCount = 0;
    int coins;
    String strscore, strcorrAnsCount, strwroAnsCount, strcoins;
    
    // Question Counting
    int questioncount = 0;
    
    // User Answer
    String inputAnswer;
        
    
    CardLayout cardlayout;
    
    public MathGame() {
        initComponents();
        // Force the table to follow column width
        Leaderboard1.getColumnModel().getColumn(0).setPreferredWidth(10);   // Rank
        Leaderboard1.getColumnModel().getColumn(1).setPreferredWidth(100);  // Username
        Leaderboard1.getColumnModel().getColumn(2).setPreferredWidth(200);  // Full Name
        Leaderboard1.getColumnModel().getColumn(3).setPreferredWidth(15);  
        
        this.setLocationRelativeTo(null);
        
        cardlayout = (CardLayout)(GamePanelCards.getLayout());
        GamePanelCards.add(Instruction, "Instruction");
        GamePanelCards.add(MainGame, "MainGame");
        GamePanelCards.add(GameEnd, "GameEnd");
        GamePanelCards.add(LeaderboardPanelFromInstruction, "LeaderboardPanelFromInstruction");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GamePanelCards = new javax.swing.JPanel();
        MainGame = new javax.swing.JPanel();
        ScreenPanel = new javax.swing.JPanel();
        AnsCorrect = new javax.swing.JLabel();
        AnsCorrCount = new javax.swing.JLabel();
        ScoreCount = new javax.swing.JLabel();
        QuestionOutput = new javax.swing.JTextField();
        AnswerInput = new javax.swing.JTextField();
        AnswerLabel = new javax.swing.JTextField();
        AnsWrong = new javax.swing.JLabel();
        AnsWrongCount = new javax.swing.JLabel();
        AnsWrong4 = new javax.swing.JLabel();
        ButtonNum9 = new javax.swing.JButton();
        ButtonNum7 = new javax.swing.JButton();
        ButtonNum8 = new javax.swing.JButton();
        ButtonNum4 = new javax.swing.JButton();
        ButtonNum5 = new javax.swing.JButton();
        ButtonNum6 = new javax.swing.JButton();
        ButtonMinus = new javax.swing.JButton();
        ButtonNum1 = new javax.swing.JButton();
        ButtonNum3 = new javax.swing.JButton();
        ButtonNum2 = new javax.swing.JButton();
        ButtonNum0 = new javax.swing.JButton();
        ButtonEnter = new javax.swing.JButton();
        QuitButton1 = new javax.swing.JButton();
        Instruction = new javax.swing.JPanel();
        InstructionPanel1 = new javax.swing.JPanel();
        AdditionSubtitle21 = new javax.swing.JLabel();
        AdditionSubtitle17 = new javax.swing.JLabel();
        ScreenPanelSample = new javax.swing.JPanel();
        AnsCorrect1 = new javax.swing.JLabel();
        AnsWrong2 = new javax.swing.JLabel();
        AnsWrong3 = new javax.swing.JLabel();
        QuestionOutput1 = new javax.swing.JTextField();
        QuestionOutput2 = new javax.swing.JTextField();
        QuestionOutput3 = new javax.swing.JTextField();
        InstructionPanel2 = new javax.swing.JPanel();
        AdditionSubtitle22 = new javax.swing.JLabel();
        InstructionPanel3 = new javax.swing.JPanel();
        AdditionSubtitle23 = new javax.swing.JLabel();
        QuitButton = new javax.swing.JButton();
        StartButton = new javax.swing.JButton();
        Leaderboard2 = new javax.swing.JButton();
        GameEnd = new javax.swing.JPanel();
        AdditionSubtitle18 = new javax.swing.JLabel();
        ScreenPanelSample1 = new javax.swing.JPanel();
        FinalCorrectAnswers = new javax.swing.JTextField();
        FinalCorrectAnswersOutput = new javax.swing.JTextField();
        FinalWrongAnswersOutput = new javax.swing.JTextField();
        FinalWrongAnswers = new javax.swing.JTextField();
        FinalScore = new javax.swing.JTextField();
        FinalScoreOutput = new javax.swing.JTextField();
        CoinsGetOutput = new javax.swing.JTextField();
        CoinsGet = new javax.swing.JTextField();
        InstructionPanel6 = new javax.swing.JPanel();
        AdditionSubtitle26 = new javax.swing.JLabel();
        Leaderboard = new javax.swing.JButton();
        RestartButton = new javax.swing.JButton();
        QuitButton3 = new javax.swing.JButton();
        LeaderboardPanelFromInstruction = new javax.swing.JPanel();
        AdditionSubtitle19 = new javax.swing.JLabel();
        BacktoInstructionButton = new javax.swing.JButton();
        QuitButton4 = new javax.swing.JButton();
        LeaderboardScrollPanel1 = new javax.swing.JScrollPane();
        Leaderboard1 = new javax.swing.JTable();
        QuestionOutput4 = new javax.swing.JTextField();
        RankOutput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(510, 830));
        setMinimumSize(new java.awt.Dimension(510, 830));
        setUndecorated(true);
        setResizable(false);

        GamePanelCards.setMaximumSize(new java.awt.Dimension(510, 830));
        GamePanelCards.setMinimumSize(new java.awt.Dimension(510, 830));
        GamePanelCards.setPreferredSize(new java.awt.Dimension(510, 830));
        GamePanelCards.setLayout(new java.awt.CardLayout());

        MainGame.setBackground(new java.awt.Color(230, 241, 231));
        MainGame.setMaximumSize(new java.awt.Dimension(510, 830));
        MainGame.setMinimumSize(new java.awt.Dimension(510, 830));
        MainGame.setPreferredSize(new java.awt.Dimension(510, 830));
        MainGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScreenPanel.setBackground(new java.awt.Color(255, 255, 255));
        ScreenPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AnsCorrect.setBackground(new java.awt.Color(255, 255, 255));
        AnsCorrect.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AnsCorrect.setForeground(new java.awt.Color(0, 102, 0));
        AnsCorrect.setText("Correct Answers: ");
        ScreenPanel.add(AnsCorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, -1));

        AnsCorrCount.setBackground(new java.awt.Color(255, 255, 255));
        AnsCorrCount.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AnsCorrCount.setForeground(new java.awt.Color(0, 102, 0));
        AnsCorrCount.setText("0");
        ScreenPanel.add(AnsCorrCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, -1));

        ScoreCount.setBackground(new java.awt.Color(255, 255, 255));
        ScoreCount.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        ScoreCount.setText("0");
        ScreenPanel.add(ScoreCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 80, -1));

        QuestionOutput.setEditable(false);
        QuestionOutput.setBackground(new java.awt.Color(255, 255, 255));
        QuestionOutput.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        QuestionOutput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        QuestionOutput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanel.add(QuestionOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 440, 30));

        AnswerInput.setEditable(false);
        AnswerInput.setBackground(new java.awt.Color(255, 255, 255));
        AnswerInput.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        AnswerInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        AnswerInput.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(204, 204, 204)));
        ScreenPanel.add(AnswerInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 180, 60));

        AnswerLabel.setEditable(false);
        AnswerLabel.setBackground(new java.awt.Color(255, 255, 255));
        AnswerLabel.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        AnswerLabel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        AnswerLabel.setText(" ANSWER:");
        AnswerLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanel.add(AnswerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 260, 60));

        AnsWrong.setBackground(new java.awt.Color(255, 255, 255));
        AnsWrong.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AnsWrong.setForeground(new java.awt.Color(153, 0, 0));
        AnsWrong.setText("Wrong Answers: ");
        ScreenPanel.add(AnsWrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, -1));

        AnsWrongCount.setBackground(new java.awt.Color(255, 255, 255));
        AnsWrongCount.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AnsWrongCount.setForeground(new java.awt.Color(153, 0, 0));
        AnsWrongCount.setText("0");
        ScreenPanel.add(AnsWrongCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 28, 30, 20));

        AnsWrong4.setBackground(new java.awt.Color(255, 255, 255));
        AnsWrong4.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AnsWrong4.setText("Score:");
        ScreenPanel.add(AnsWrong4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 50, -1));

        MainGame.add(ScreenPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 170));

        ButtonNum9.setFont(new java.awt.Font("Fredoka Medium", 0, 36)); // NOI18N
        ButtonNum9.setText("9");
        ButtonNum9.setBorder(null);
        ButtonNum9.setPreferredSize(new java.awt.Dimension(120, 120));
        ButtonNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNum9ActionPerformed(evt);
            }
        });
        MainGame.add(ButtonNum9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 120, 120));

        ButtonNum7.setFont(new java.awt.Font("Fredoka Medium", 0, 36)); // NOI18N
        ButtonNum7.setText("7");
        ButtonNum7.setBorder(null);
        ButtonNum7.setMaximumSize(new java.awt.Dimension(120, 120));
        ButtonNum7.setMinimumSize(new java.awt.Dimension(120, 120));
        ButtonNum7.setPreferredSize(new java.awt.Dimension(120, 120));
        ButtonNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNum7ActionPerformed(evt);
            }
        });
        MainGame.add(ButtonNum7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 120, 120));

        ButtonNum8.setFont(new java.awt.Font("Fredoka Medium", 0, 36)); // NOI18N
        ButtonNum8.setText("8");
        ButtonNum8.setBorder(null);
        ButtonNum8.setPreferredSize(new java.awt.Dimension(120, 120));
        ButtonNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNum8ActionPerformed(evt);
            }
        });
        MainGame.add(ButtonNum8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 120, 120));

        ButtonNum4.setFont(new java.awt.Font("Fredoka Medium", 0, 36)); // NOI18N
        ButtonNum4.setText("4");
        ButtonNum4.setBorder(null);
        ButtonNum4.setMaximumSize(new java.awt.Dimension(120, 120));
        ButtonNum4.setMinimumSize(new java.awt.Dimension(120, 120));
        ButtonNum4.setPreferredSize(new java.awt.Dimension(120, 120));
        ButtonNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNum4ActionPerformed(evt);
            }
        });
        MainGame.add(ButtonNum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 120, 120));

        ButtonNum5.setFont(new java.awt.Font("Fredoka Medium", 0, 36)); // NOI18N
        ButtonNum5.setText("5");
        ButtonNum5.setBorder(null);
        ButtonNum5.setPreferredSize(new java.awt.Dimension(120, 120));
        ButtonNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNum5ActionPerformed(evt);
            }
        });
        MainGame.add(ButtonNum5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 120, 120));

        ButtonNum6.setFont(new java.awt.Font("Fredoka Medium", 0, 36)); // NOI18N
        ButtonNum6.setText("6");
        ButtonNum6.setBorder(null);
        ButtonNum6.setPreferredSize(new java.awt.Dimension(120, 120));
        ButtonNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNum6ActionPerformed(evt);
            }
        });
        MainGame.add(ButtonNum6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 120, 120));

        ButtonMinus.setFont(new java.awt.Font("Fredoka Medium", 0, 36)); // NOI18N
        ButtonMinus.setText("(-)");
        ButtonMinus.setBorder(null);
        ButtonMinus.setPreferredSize(new java.awt.Dimension(120, 120));
        ButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMinusActionPerformed(evt);
            }
        });
        MainGame.add(ButtonMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 120, 120));

        ButtonNum1.setFont(new java.awt.Font("Fredoka Medium", 0, 36)); // NOI18N
        ButtonNum1.setText("1");
        ButtonNum1.setBorder(null);
        ButtonNum1.setMaximumSize(new java.awt.Dimension(120, 120));
        ButtonNum1.setMinimumSize(new java.awt.Dimension(120, 120));
        ButtonNum1.setPreferredSize(new java.awt.Dimension(120, 120));
        ButtonNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNum1ActionPerformed(evt);
            }
        });
        MainGame.add(ButtonNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 120, 120));

        ButtonNum3.setFont(new java.awt.Font("Fredoka Medium", 0, 36)); // NOI18N
        ButtonNum3.setText("3");
        ButtonNum3.setBorder(null);
        ButtonNum3.setPreferredSize(new java.awt.Dimension(120, 120));
        ButtonNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNum3ActionPerformed(evt);
            }
        });
        MainGame.add(ButtonNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 120, 120));

        ButtonNum2.setFont(new java.awt.Font("Fredoka Medium", 0, 36)); // NOI18N
        ButtonNum2.setText("2");
        ButtonNum2.setBorder(null);
        ButtonNum2.setPreferredSize(new java.awt.Dimension(120, 120));
        ButtonNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNum2ActionPerformed(evt);
            }
        });
        MainGame.add(ButtonNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 120, 120));

        ButtonNum0.setFont(new java.awt.Font("Fredoka Medium", 0, 36)); // NOI18N
        ButtonNum0.setText("0");
        ButtonNum0.setBorder(null);
        ButtonNum0.setPreferredSize(new java.awt.Dimension(120, 120));
        ButtonNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNum0ActionPerformed(evt);
            }
        });
        MainGame.add(ButtonNum0, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 120, 120));

        ButtonEnter.setBackground(new java.awt.Color(0, 102, 0));
        ButtonEnter.setFont(new java.awt.Font("Fredoka Medium", 0, 24)); // NOI18N
        ButtonEnter.setForeground(new java.awt.Color(255, 255, 255));
        ButtonEnter.setText("Enter");
        ButtonEnter.setBorder(null);
        ButtonEnter.setPreferredSize(new java.awt.Dimension(120, 120));
        ButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnterActionPerformed(evt);
            }
        });
        MainGame.add(ButtonEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 120, 120));

        QuitButton1.setBackground(new java.awt.Color(204, 0, 0));
        QuitButton1.setFont(new java.awt.Font("Fredoka Medium", 1, 14)); // NOI18N
        QuitButton1.setForeground(new java.awt.Color(255, 255, 255));
        QuitButton1.setText("Quit Game");
        QuitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButton1ActionPerformed(evt);
            }
        });
        MainGame.add(QuitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 770, 110, 30));

        GamePanelCards.add(MainGame, "card2");

        Instruction.setBackground(new java.awt.Color(230, 241, 231));
        Instruction.setMaximumSize(new java.awt.Dimension(510, 830));
        Instruction.setMinimumSize(new java.awt.Dimension(510, 830));
        Instruction.setPreferredSize(new java.awt.Dimension(510, 830));
        Instruction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InstructionPanel1.setBackground(new java.awt.Color(255, 255, 255));
        InstructionPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle21.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle21.setText("<html><b>Quick Tip: </b>Click on the negative button <b>(-)</b> ot submit a negative answer. You cannot change a number after choosing so choose wisely!</html>");
        InstructionPanel1.add(AdditionSubtitle21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 40));

        Instruction.add(InstructionPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 460, 60));

        AdditionSubtitle17.setFont(new java.awt.Font("Fredoka Medium", 1, 36)); // NOI18N
        AdditionSubtitle17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdditionSubtitle17.setText("Quickquirk Mental Maths!");
        Instruction.add(AdditionSubtitle17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 490, 60));

        ScreenPanelSample.setBackground(new java.awt.Color(255, 255, 255));
        ScreenPanelSample.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AnsCorrect1.setBackground(new java.awt.Color(255, 255, 255));
        AnsCorrect1.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AnsCorrect1.setForeground(new java.awt.Color(0, 102, 0));
        AnsCorrect1.setText("Correct Answers: 3");
        ScreenPanelSample.add(AnsCorrect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 152, -1));

        AnsWrong2.setBackground(new java.awt.Color(255, 255, 255));
        AnsWrong2.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AnsWrong2.setForeground(new java.awt.Color(153, 0, 0));
        AnsWrong2.setText("Wrong Answers: 1");
        ScreenPanelSample.add(AnsWrong2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, 152, -1));

        AnsWrong3.setBackground(new java.awt.Color(255, 255, 255));
        AnsWrong3.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AnsWrong3.setText("Score: 300");
        ScreenPanelSample.add(AnsWrong3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 6, 90, -1));

        QuestionOutput1.setEditable(false);
        QuestionOutput1.setBackground(new java.awt.Color(255, 255, 255));
        QuestionOutput1.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        QuestionOutput1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        QuestionOutput1.setText(" ANSWER:");
        QuestionOutput1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample.add(QuestionOutput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 260, 60));

        QuestionOutput2.setEditable(false);
        QuestionOutput2.setBackground(new java.awt.Color(255, 255, 255));
        QuestionOutput2.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        QuestionOutput2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        QuestionOutput2.setText("2x + 1 = 3");
        QuestionOutput2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample.add(QuestionOutput2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 440, 30));

        QuestionOutput3.setEditable(false);
        QuestionOutput3.setBackground(new java.awt.Color(255, 255, 255));
        QuestionOutput3.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        QuestionOutput3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        QuestionOutput3.setText("1");
        QuestionOutput3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample.add(QuestionOutput3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 180, 60));

        Instruction.add(ScreenPanelSample, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 460, 170));

        InstructionPanel2.setBackground(new java.awt.Color(255, 255, 255));
        InstructionPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle22.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle22.setText("<html>An algebraic equation will be provided </html>");
        InstructionPanel2.add(AdditionSubtitle22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 20));

        Instruction.add(InstructionPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 460, 40));

        InstructionPanel3.setBackground(new java.awt.Color(255, 255, 255));
        InstructionPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle23.setFont(new java.awt.Font("Fredoka", 0, 14)); // NOI18N
        AdditionSubtitle23.setText("<html>Click on the number pad buttons with the right answer and click on \"Enter\" to submit the answer.</html>");
        InstructionPanel3.add(AdditionSubtitle23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 40));

        Instruction.add(InstructionPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 460, 60));

        QuitButton.setBackground(new java.awt.Color(255, 204, 204));
        QuitButton.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        QuitButton.setText("Quit");
        QuitButton.setBorder(null);
        QuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButtonActionPerformed(evt);
            }
        });
        Instruction.add(QuitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 730, 170, 40));

        StartButton.setBackground(new java.awt.Color(255, 255, 102));
        StartButton.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        StartButton.setText("Start!");
        StartButton.setBorder(null);
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });
        Instruction.add(StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 210, 70));

        Leaderboard2.setBackground(new java.awt.Color(204, 204, 255));
        Leaderboard2.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        Leaderboard2.setText("Leaderboard");
        Leaderboard2.setBorder(null);
        Leaderboard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Leaderboard2ActionPerformed(evt);
            }
        });
        Instruction.add(Leaderboard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, 170, 40));

        GamePanelCards.add(Instruction, "card3");

        GameEnd.setBackground(new java.awt.Color(230, 241, 231));
        GameEnd.setMaximumSize(new java.awt.Dimension(510, 830));
        GameEnd.setMinimumSize(new java.awt.Dimension(510, 830));
        GameEnd.setPreferredSize(new java.awt.Dimension(510, 830));
        GameEnd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle18.setFont(new java.awt.Font("Fredoka Medium", 1, 36)); // NOI18N
        AdditionSubtitle18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdditionSubtitle18.setText("Game End!");
        GameEnd.add(AdditionSubtitle18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 490, 60));

        ScreenPanelSample1.setBackground(new java.awt.Color(255, 255, 255));
        ScreenPanelSample1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FinalCorrectAnswers.setEditable(false);
        FinalCorrectAnswers.setBackground(new java.awt.Color(255, 255, 255));
        FinalCorrectAnswers.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        FinalCorrectAnswers.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        FinalCorrectAnswers.setText("Correct Answers:");
        FinalCorrectAnswers.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample1.add(FinalCorrectAnswers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 30));

        FinalCorrectAnswersOutput.setEditable(false);
        FinalCorrectAnswersOutput.setBackground(new java.awt.Color(255, 255, 255));
        FinalCorrectAnswersOutput.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        FinalCorrectAnswersOutput.setForeground(new java.awt.Color(0, 102, 0));
        FinalCorrectAnswersOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FinalCorrectAnswersOutput.setText("0");
        FinalCorrectAnswersOutput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample1.add(FinalCorrectAnswersOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 200, 30));

        FinalWrongAnswersOutput.setEditable(false);
        FinalWrongAnswersOutput.setBackground(new java.awt.Color(255, 255, 255));
        FinalWrongAnswersOutput.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        FinalWrongAnswersOutput.setForeground(new java.awt.Color(153, 0, 0));
        FinalWrongAnswersOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FinalWrongAnswersOutput.setText("0");
        FinalWrongAnswersOutput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample1.add(FinalWrongAnswersOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 200, 30));

        FinalWrongAnswers.setEditable(false);
        FinalWrongAnswers.setBackground(new java.awt.Color(255, 255, 255));
        FinalWrongAnswers.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        FinalWrongAnswers.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        FinalWrongAnswers.setText("Wrong Answers:");
        FinalWrongAnswers.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample1.add(FinalWrongAnswers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 240, 30));

        FinalScore.setEditable(false);
        FinalScore.setBackground(new java.awt.Color(255, 255, 255));
        FinalScore.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        FinalScore.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        FinalScore.setText("Final Score:");
        FinalScore.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample1.add(FinalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 240, 30));

        FinalScoreOutput.setEditable(false);
        FinalScoreOutput.setBackground(new java.awt.Color(255, 255, 255));
        FinalScoreOutput.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        FinalScoreOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FinalScoreOutput.setText("0");
        FinalScoreOutput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample1.add(FinalScoreOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 200, 30));

        CoinsGetOutput.setEditable(false);
        CoinsGetOutput.setBackground(new java.awt.Color(255, 255, 0));
        CoinsGetOutput.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        CoinsGetOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CoinsGetOutput.setText("0");
        CoinsGetOutput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample1.add(CoinsGetOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 200, 40));

        CoinsGet.setEditable(false);
        CoinsGet.setBackground(new java.awt.Color(255, 255, 0));
        CoinsGet.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        CoinsGet.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CoinsGet.setText("Coins Earned:");
        CoinsGet.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        ScreenPanelSample1.add(CoinsGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 240, 40));

        GameEnd.add(ScreenPanelSample1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 460, 200));

        InstructionPanel6.setBackground(new java.awt.Color(255, 255, 255));
        InstructionPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle26.setFont(new java.awt.Font("Fredoka", 0, 18)); // NOI18N
        AdditionSubtitle26.setText("<html>Keep practicing! You are very close to beat your best score!</html>");
        InstructionPanel6.add(AdditionSubtitle26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 40));

        GameEnd.add(InstructionPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 460, 60));

        Leaderboard.setBackground(new java.awt.Color(204, 204, 255));
        Leaderboard.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        Leaderboard.setText("Leaderboard");
        Leaderboard.setBorder(null);
        Leaderboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaderboardActionPerformed(evt);
            }
        });
        GameEnd.add(Leaderboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 220, 70));

        RestartButton.setBackground(new java.awt.Color(255, 255, 102));
        RestartButton.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        RestartButton.setText("Restart!");
        RestartButton.setBorder(null);
        RestartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartButtonActionPerformed(evt);
            }
        });
        GameEnd.add(RestartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 690, 200, 70));

        QuitButton3.setBackground(new java.awt.Color(255, 255, 102));
        QuitButton3.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        QuitButton3.setText("Quit");
        QuitButton3.setBorder(null);
        QuitButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButton3ActionPerformed(evt);
            }
        });
        GameEnd.add(QuitButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 200, 70));

        GamePanelCards.add(GameEnd, "card3");

        LeaderboardPanelFromInstruction.setBackground(new java.awt.Color(230, 241, 231));
        LeaderboardPanelFromInstruction.setMaximumSize(new java.awt.Dimension(510, 830));
        LeaderboardPanelFromInstruction.setMinimumSize(new java.awt.Dimension(510, 830));
        LeaderboardPanelFromInstruction.setPreferredSize(new java.awt.Dimension(510, 830));
        LeaderboardPanelFromInstruction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionSubtitle19.setFont(new java.awt.Font("Fredoka Medium", 1, 36)); // NOI18N
        AdditionSubtitle19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdditionSubtitle19.setText("Leaderboard");
        LeaderboardPanelFromInstruction.add(AdditionSubtitle19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 490, 60));

        BacktoInstructionButton.setBackground(new java.awt.Color(255, 255, 102));
        BacktoInstructionButton.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        BacktoInstructionButton.setText("Go Back");
        BacktoInstructionButton.setBorder(null);
        BacktoInstructionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoInstructionButtonActionPerformed(evt);
            }
        });
        LeaderboardPanelFromInstruction.add(BacktoInstructionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 690, 200, 70));

        QuitButton4.setBackground(new java.awt.Color(255, 204, 204));
        QuitButton4.setFont(new java.awt.Font("Fredoka", 1, 24)); // NOI18N
        QuitButton4.setText("Quit");
        QuitButton4.setBorder(null);
        QuitButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButton4ActionPerformed(evt);
            }
        });
        LeaderboardPanelFromInstruction.add(QuitButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 200, 70));

        LeaderboardScrollPanel1.setBackground(new java.awt.Color(116, 143, 118));
        LeaderboardScrollPanel1.setBorder(null);
        LeaderboardScrollPanel1.setForeground(new java.awt.Color(116, 143, 118));
        LeaderboardScrollPanel1.setMaximumSize(new java.awt.Dimension(452, 402));
        LeaderboardScrollPanel1.setMinimumSize(new java.awt.Dimension(452, 402));

        Leaderboard1.setAutoCreateRowSorter(true);
        Leaderboard1.setBackground(new java.awt.Color(116, 143, 118));
        Leaderboard1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Leaderboard1.setForeground(new java.awt.Color(255, 255, 255));
        Leaderboard1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Rank", "Username", "Full Name", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Leaderboard1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Leaderboard1.setGridColor(new java.awt.Color(210, 224, 212));
        Leaderboard1.setMaximumSize(new java.awt.Dimension(452, 402));
        Leaderboard1.setMinimumSize(new java.awt.Dimension(452, 402));
        Leaderboard1.setPreferredSize(new java.awt.Dimension(452, 402));
        Leaderboard1.setRowHeight(40);
        Leaderboard1.getTableHeader().setResizingAllowed(false);
        Leaderboard1.getTableHeader().setReorderingAllowed(false);
        LeaderboardScrollPanel1.setViewportView(Leaderboard1);
        if (Leaderboard1.getColumnModel().getColumnCount() > 0) {
            Leaderboard1.getColumnModel().getColumn(0).setResizable(false);
            Leaderboard1.getColumnModel().getColumn(0).setPreferredWidth(35);
            Leaderboard1.getColumnModel().getColumn(1).setResizable(false);
            Leaderboard1.getColumnModel().getColumn(1).setPreferredWidth(130);
            Leaderboard1.getColumnModel().getColumn(2).setResizable(false);
            Leaderboard1.getColumnModel().getColumn(2).setPreferredWidth(230);
            Leaderboard1.getColumnModel().getColumn(3).setResizable(false);
            Leaderboard1.getColumnModel().getColumn(3).setPreferredWidth(75);
        }

        LeaderboardPanelFromInstruction.add(LeaderboardScrollPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 460, 440));

        QuestionOutput4.setEditable(false);
        QuestionOutput4.setBackground(new java.awt.Color(255, 255, 255));
        QuestionOutput4.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        QuestionOutput4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        QuestionOutput4.setText("Your rank:");
        QuestionOutput4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(204, 204, 204)));
        LeaderboardPanelFromInstruction.add(QuestionOutput4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 210, 40));

        RankOutput.setEditable(false);
        RankOutput.setBackground(new java.awt.Color(255, 255, 255));
        RankOutput.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        RankOutput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        RankOutput.setText("0");
        RankOutput.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(204, 204, 204)));
        LeaderboardPanelFromInstruction.add(RankOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 230, 40));

        GamePanelCards.add(LeaderboardPanelFromInstruction, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GamePanelCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GamePanelCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButtonActionPerformed
        this.dispose();
        MathsCourse mc = new MathsCourse();
        mc.setVisible(true);
    }//GEN-LAST:event_QuitButtonActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        cardlayout.show(GamePanelCards,"MainGame");
        score = corrAnsCount = wroAnsCount = questioncount = 0;
        this.QuestionBank();
    }//GEN-LAST:event_StartButtonActionPerformed

    private void QuitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButton1ActionPerformed
        this.dispose();
        MathsCourse mc = new MathsCourse();
        mc.setVisible(true);
    }//GEN-LAST:event_QuitButton1ActionPerformed

    private void ButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnterActionPerformed
        if ("0".equals(n1)){
            n1 = "";
        }

        inputAnswer = n1 + n2;

        if (minus == true){
            int temp = Integer.parseInt(inputAnswer);
            temp = temp * -1;
            inputAnswer = Integer.toString(temp);
            minus = false;   
        }

        if (this.corrAns.trim().equals(inputAnswer.trim())){
            // Answer is correct
            corrAnsCount = corrAnsCount + 1;
            score = score + 100;

        } else {
            wroAnsCount = wroAnsCount + 1;

        }
        
        System.out.println("Correct Answer Count: " + corrAnsCount);
        System.out.println("Wrong Answer Count: " + wroAnsCount);
        System.out.println("Score: " + score);
        
        strscore = Integer.toString(score);
        strcorrAnsCount = Integer.toString(corrAnsCount);
        strwroAnsCount = Integer.toString(wroAnsCount);
        
        if (questioncount == 9){
            // Go to end page
            cardlayout.show(GamePanelCards, "GameEnd");
            
            // Coins earned set at score/10
            coins = score/10;
            strcoins = Integer.toString(coins);
            CoinsGetOutput.setText(strcoins);
            updateCoins(coins);
            
            // Update Leaderboard
            AddtoLeaderboard();
            sortLeaderboard();
        }

        ScoreCount.setText(strscore);
        FinalScoreOutput.setText(strscore);
        
        AnsCorrCount.setText(strcorrAnsCount);
        FinalCorrectAnswersOutput.setText(strcorrAnsCount);
        
        AnsWrongCount.setText(strwroAnsCount);
        FinalWrongAnswersOutput.setText(strwroAnsCount);

        n1 = n2 = "";
        this.AnswerInput.setText("");

        if (questioncount != 9){
            System.out.println("\nNext Question:\n");
            questioncount++;
            this.QuestionBank();
        }
        
    }//GEN-LAST:event_ButtonEnterActionPerformed

    private void ButtonNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNum1ActionPerformed
        this.nControl("1");
    }//GEN-LAST:event_ButtonNum1ActionPerformed

    private void ButtonNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNum2ActionPerformed
        this.nControl("2");
    }//GEN-LAST:event_ButtonNum2ActionPerformed

    private void ButtonNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNum3ActionPerformed
        this.nControl("3");
    }//GEN-LAST:event_ButtonNum3ActionPerformed
        
    private void ButtonNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNum4ActionPerformed
        this.nControl("4");
    }//GEN-LAST:event_ButtonNum4ActionPerformed

    private void ButtonNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNum5ActionPerformed
        this.nControl("5");
    }//GEN-LAST:event_ButtonNum5ActionPerformed

    private void ButtonNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNum6ActionPerformed
        this.nControl("6");
    }//GEN-LAST:event_ButtonNum6ActionPerformed

    private void ButtonNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNum7ActionPerformed
        this.nControl("7");
    }//GEN-LAST:event_ButtonNum7ActionPerformed

    private void ButtonNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNum8ActionPerformed
        this.nControl("8");
    }//GEN-LAST:event_ButtonNum8ActionPerformed

    private void ButtonNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNum9ActionPerformed
        this.nControl("9");
    }//GEN-LAST:event_ButtonNum9ActionPerformed

    private void ButtonNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNum0ActionPerformed
        this.nControl("0");
    }//GEN-LAST:event_ButtonNum0ActionPerformed

    private void ButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMinusActionPerformed
        if (minus == false){
            minus = true;
            ButtonMinus.setBackground(new java.awt.Color(255, 255, 0));
        } else {
            minus = false;
            ButtonMinus.setBackground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_ButtonMinusActionPerformed

    private void LeaderboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaderboardActionPerformed
        // Leaderboard Method here
        cardlayout.show(GamePanelCards,"LeaderboardPanelFromInstruction");
        displayLeaderboard();
        
    }//GEN-LAST:event_LeaderboardActionPerformed

    private void RestartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartButtonActionPerformed
        cardlayout.show(GamePanelCards,"MainGame");
        score = corrAnsCount = wroAnsCount = questioncount = 0;
        this.QuestionBank();
    }//GEN-LAST:event_RestartButtonActionPerformed

    private void QuitButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButton3ActionPerformed
        this.dispose();
        MathsCourse mc = new MathsCourse();
        mc.setVisible(true);
    }//GEN-LAST:event_QuitButton3ActionPerformed

    private void BacktoInstructionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktoInstructionButtonActionPerformed
        cardlayout.show(GamePanelCards,"Instruction");
    }//GEN-LAST:event_BacktoInstructionButtonActionPerformed

    private void QuitButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButton4ActionPerformed
        this.dispose();
        MathsCourse mc = new MathsCourse();
        mc.setVisible(true);
    }//GEN-LAST:event_QuitButton4ActionPerformed

    private void Leaderboard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Leaderboard2ActionPerformed
        cardlayout.show(GamePanelCards,"LeaderboardPanelFromInstruction");
        displayLeaderboard();
    }//GEN-LAST:event_Leaderboard2ActionPerformed

    // Setting username to use for leaderboard
    public void setname(String uname, String fname){
        this.uname = uname;
        this.fname = fname;
    }
    
    // Game Logic from this line onwards
    //===============================================================================
    
    // Random Number Generator
    private int rndNum(int maxNum){
        long seed = System.currentTimeMillis();
        Random rnd = new Random(seed);
        
        int rndNum = rnd.nextInt(maxNum) + 1;
        return rndNum;
    }
    
    // Controls the number pads
    private void nControl(String n){
        if ("".equals(n1)){
            n1 = n;
            System.out.println("n1 is now " + n1); // Debug
            this.AnswerInput.setText(n1);
        } else if ("".equals(n2)){
            n2 = n;
            System.out.println("n2 is now " + n2); // Debug
            this.AnswerInput.setText(n1 + n2);
        } else {
            System.out.println("Both slots taken, cannot update number");
        }
    }
    
    // Question Bank
    private void QuestionBank(){
        // Question type
        int questiontype;
        String question;
        
        // Variables
        int a, b, x, r;
        // String variation
        String stra, strb, strx, strr;
        
        // Question Set up
        questiontype = rndNum(8);
        switch (questiontype){
            case 1:
                // Type 1: x + a = r
                a = rndNum(11);
                x = rndNum(20);

                //System.out.println("a = " + a); // Debug
                System.out.println("x = " + x); // Debug

                r = x + a;

                stra = Integer.toString(a);
                strr = Integer.toString(r);
                strx = Integer.toString(x); // result to compare

                question = "x " + "+ " + stra + " = " + strr;
                System.out.println(question); // Debug
                QuestionOutput.setText(question);
                this.corrAns = strx;
                break;

            case 2:
                // Type 2: a + x = r
                a = rndNum(11);
                x = rndNum(20);

                //System.out.println("a = " + a); // Debug
                System.out.println("x = " + x); // Debug

                r = a + x;

                stra = Integer.toString(a);
                strr = Integer.toString(r);
                strx = Integer.toString(x); // result to compare

                question = stra + " + " + "x " + "= " + strr;
                System.out.println(question); // Debug
                QuestionOutput.setText(question);
                this.corrAns = strx;
                break;
                
            case 3:
                // Type 3: x - a = r
                a = rndNum(11);
                x = rndNum(20);

                //System.out.println("a = " + a); // Debug
                System.out.println("x = " + x); // Debug

                r = x - a;

                stra = Integer.toString(a);
                strr = Integer.toString(r);
                strx = Integer.toString(x); // result to compare

                question = "x " + "- " + stra + " = " + strr;
                System.out.println(question); // Debug
                QuestionOutput.setText(question);
                this.corrAns = strx;
                break;
                
            case 4:
                // Type 4: a - x = r
                a = rndNum(11);
                x = rndNum(20);
                
                //System.out.println("a = " + a); // Debug
                System.out.println("x = " + x); // Debug

                r = a - x;

                stra = Integer.toString(a);
                strr = Integer.toString(r);
                strx = Integer.toString(x); // answer to compare

                question = stra + " - " + "x " + "= " + strr;
                System.out.println(question); // Debug
                QuestionOutput.setText(question);
                this.corrAns = strx;
                break;
                
            case 5:
                // Type 5: ax + b = r
                a = rndNum(12);
                b = rndNum(rndNum(30));
                x = rndNum(40);
                r = (a * x) + b;

                //System.out.println("a = " + a); // Debug
                //System.out.println("b = " + b); // Debug
                System.out.println("x = " + x); // Debug
                //System.out.println("r = " + r); // Debug

                stra = Integer.toString(a);
                strb = Integer.toString(b);
                strr = Integer.toString(r);
                strx = Integer.toString(x); // answer to compare

                question = stra + "x" + " + " + strb + " = " + strr;

                System.out.println(question); // Debug
                QuestionOutput.setText(question);
                this.corrAns = strx;
                break;
                
            case 6:
                // Type 6: a + bx = r
                a = rndNum(12);
                b = rndNum(rndNum(30));
                x = rndNum(40);

                r = a + (b * x);

                //System.out.println("a = " + a); // Debug
                //System.out.println("b = " + b); // Debug
                System.out.println("x = " + x); // Debug
                //System.out.println("r = " + r); // Debug

                stra = Integer.toString(a);
                strb = Integer.toString(b);
                strr = Integer.toString(r);
                strx = Integer.toString(x); // answer to compare

                question = stra + " + " + strb + "x" + " = " + strr;

                System.out.println(question); // Debug
                QuestionOutput.setText(question);
                this.corrAns = strx;
                break;
                
            case 7:
                // Type 7: ax - b = r
                a = rndNum(12);
                b = rndNum(rndNum(30));
                x = rndNum(40);

                r = (a * x) - b;

                //System.out.println("a = " + a); // Debug
                //System.out.println("b = " + b); // Debug
                System.out.println("x = " + x); // Debug
                //System.out.println("r = " + r); // Debug

                stra = Integer.toString(a);
                strb = Integer.toString(b);
                strr = Integer.toString(r);
                strx = Integer.toString(x); // answer to compare

                question = stra + "x" + " - " + strb + " = " + strr;

                System.out.println(question); // Debug
                QuestionOutput.setText(question);
                this.corrAns = strx;
                break;
                
            case 8:
                // Type 8: a - bx = r
                a = rndNum(30);
                b = rndNum(rndNum(12));
                x = rndNum(40);

                r = a - (b * x);

                //System.out.println("a = " + a); // Debug
                //System.out.println("b = " + b); // Debug
                System.out.println("x = " + x); // Debug
                //System.out.println("r = " + r); // Debug

                stra = Integer.toString(a);
                strb = Integer.toString(b);
                strr = Integer.toString(r);
                strx = Integer.toString(x); // answer to compare

                question = stra + " - " + strb + "x" + " = " + strr;

                System.out.println(question); // Debug
                QuestionOutput.setText(question);
                this.corrAns = strx;
                break;
                
        }
    }
    
    // Leaderboard
    private void AddtoLeaderboard(){
        boolean unamefound = false;
        try {
            File leaderboardfile = new File("Leaderboard/mathGame.csv");
            File templeaderboardfile = new File("Leaderboard/temp.csv");
            
            System.out.println("\nUsername: " + this.uname); // Debug

            if (!leaderboardfile.exists()) {
                leaderboardfile.createNewFile();
            }
            
            BufferedReader lbreader = new BufferedReader(new FileReader(leaderboardfile));
            BufferedWriter lbwriter = new BufferedWriter(new FileWriter(templeaderboardfile));
            
            String line;
            
            // If the leaderboard has username in it, updates it.
            while((line = lbreader.readLine()) != null){
                String[] parts = line.split(",");
                
                if (parts[1].trim().equals(this.uname.trim())){
                    unamefound = true;
                    System.out.println("\nUsername found: " + unamefound + 
                            "\nUsername: " + parts[1] + 
                            "\nUpdating score only..."); //Debug
                    parts[3] = strscore; // Changes the score to the new score
                }
                
                lbwriter.write(String.join(",", parts));
                lbwriter.newLine();
            }
            
            // If the username is not found, then adds one
            if (unamefound == false){
                String newinput = "" + "," + this.uname + "," + this.fname + "," +
                        score;
                lbwriter.write(newinput);
            }
            
            lbreader.close();
            lbwriter.close();
            
            if (leaderboardfile.delete()) {
                templeaderboardfile.renameTo(leaderboardfile);
            }
            
        } catch (IOException e){
            e.printStackTrace();
        }
        
    }
    
    private void sortLeaderboard(){
        File leaderboardFile = new File("Leaderboard/mathGame.csv");
        File templeaderboardFile = new File("Leaderboard/temp.csv");

        String[][] data = new String[100][4]; // Max 100 rows, 4 columns
        int rowCount = 0;

        // Read file into array [rows][columns]
        try {
            BufferedReader reader = new BufferedReader(new FileReader(leaderboardFile));
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length == 4) {
                    for (int i = 0; i < 4; i++) {
                        data[rowCount][i] = parts[i];
                    }
                    rowCount++;
                }
            }
            
            reader.close();
            
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Insertion sort by score
        for (int i = 1; i < rowCount; i++) {
            String[] key = data[i];
            int keyScore = Integer.parseInt(key[3].trim());

            int j = i - 1;

            // Shift elements that are less than keyScore
            while (j >= 0 && Integer.parseInt(data[j][3].trim()) < keyScore) {
                data[j + 1] = data[j];
                j--;
            }

            data[j + 1] = key;
        }

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(templeaderboardFile))) {
            for (int i = 0; i < rowCount; i++) {
                String rank = Integer.toString(i + 1);
                writer.write(rank + "," + data[i][1] + "," + data[i][2] + "," + data[i][3]);
                writer.newLine();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        // Replace original file with sorted temp file
        if (leaderboardFile.delete()) {
            templeaderboardFile.renameTo(leaderboardFile);
        }
    
    }
    
    private void updateCoins(int coins){
        // Retrieve public information (Name, username)
        File userfile = new File("Learner/" + this.uname + "/accountDetails.csv");
        File tempuserfilePath = new File("Learner/" + this.uname + "/temp.csv");
        try {
            BufferedReader reader = new BufferedReader(new FileReader(userfile));
            BufferedWriter writer = new BufferedWriter(new FileWriter(tempuserfilePath));

            String line;
            int lineNumber = 0;

            while ((line = reader.readLine()) != null) {
                switch (lineNumber) {
                    case 4:
                        int oldcoins = Integer.parseInt(line);
                        int newcoins = oldcoins + coins;
                        String strtotalcoins = Integer.toString(newcoins);
                        writer.write(strtotalcoins); 
                        break; // Update coins
                    case 6:
                        int oldscore = Integer.parseInt(line);
                        if(score > oldscore){
                            String strnewscore = Integer.toString(score);
                            writer.write(strnewscore);
                            break;
                        }
                    default: writer.write(line); break;    // Keep original
                }
                writer.newLine();
                lineNumber++;
            }

            reader.close();
            writer.close();

            if (userfile.delete()) {
                if (tempuserfilePath.renameTo(userfile)) {
                    System.out.println("Updated successfully!"); // Debug
                } else {
                    System.out.println(" Couldn't rename temp file."); // Debug
                }
            } else {
                System.out.println("Couldn't delete original file."); // Debug
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void displayLeaderboard(){
        String[] columnNames = { "Rank", "Username", "Full Name", "Score" };
        String[][] rowData = new String[100][4];
        int rowCount = 0;

        try (BufferedReader reader = new BufferedReader(new FileReader("Leaderboard/mathGame.csv"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length == 4) {
                    for (int i = 0; i < 4; i++) {
                        rowData[rowCount][i] = parts[i];
                    }
                    rowCount++;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Trim the array to actual data size, this will be used for users outside of top 7
        String[][] trimmedData = new String[rowCount][4];
        for (int i = 0; i < rowCount; i++) {
            for (int j = 0; j < 4; j++) {
                trimmedData[i][j] = rowData[i][j];
            }
            
            if (trimmedData[i][1].equals(this.uname)) {
            this.rank = i + 1;
            String strRank = Integer.toString(this.rank);
            RankOutput.setText(strRank);
            } else {
                RankOutput.setText("--");
            }
        }
        
        // Top 7 make it to leaderboard
        int topCount = Math.min(rowCount, 7);
        String[][] topData = new String[topCount][4];

        for (int i = 0; i < topCount; i++) {
            for (int j = 0; j < 4; j++) {
                topData[i][j] = trimmedData[i][j];
            }
        }
        
        DefaultTableModel model = new DefaultTableModel(topData, columnNames);
        Leaderboard1.setModel(model);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdditionSubtitle17;
    private javax.swing.JLabel AdditionSubtitle18;
    private javax.swing.JLabel AdditionSubtitle19;
    private javax.swing.JLabel AdditionSubtitle21;
    private javax.swing.JLabel AdditionSubtitle22;
    private javax.swing.JLabel AdditionSubtitle23;
    private javax.swing.JLabel AdditionSubtitle26;
    private javax.swing.JLabel AnsCorrCount;
    private javax.swing.JLabel AnsCorrect;
    private javax.swing.JLabel AnsCorrect1;
    private javax.swing.JLabel AnsWrong;
    private javax.swing.JLabel AnsWrong2;
    private javax.swing.JLabel AnsWrong3;
    private javax.swing.JLabel AnsWrong4;
    private javax.swing.JLabel AnsWrongCount;
    private javax.swing.JTextField AnswerInput;
    private javax.swing.JTextField AnswerLabel;
    private javax.swing.JButton BacktoInstructionButton;
    private javax.swing.JButton ButtonEnter;
    private javax.swing.JButton ButtonMinus;
    private javax.swing.JButton ButtonNum0;
    private javax.swing.JButton ButtonNum1;
    private javax.swing.JButton ButtonNum2;
    private javax.swing.JButton ButtonNum3;
    private javax.swing.JButton ButtonNum4;
    private javax.swing.JButton ButtonNum5;
    private javax.swing.JButton ButtonNum6;
    private javax.swing.JButton ButtonNum7;
    private javax.swing.JButton ButtonNum8;
    private javax.swing.JButton ButtonNum9;
    private javax.swing.JTextField CoinsGet;
    private javax.swing.JTextField CoinsGetOutput;
    private javax.swing.JTextField FinalCorrectAnswers;
    private javax.swing.JTextField FinalCorrectAnswersOutput;
    private javax.swing.JTextField FinalScore;
    private javax.swing.JTextField FinalScoreOutput;
    private javax.swing.JTextField FinalWrongAnswers;
    private javax.swing.JTextField FinalWrongAnswersOutput;
    private javax.swing.JPanel GameEnd;
    private javax.swing.JPanel GamePanelCards;
    private javax.swing.JPanel Instruction;
    private javax.swing.JPanel InstructionPanel1;
    private javax.swing.JPanel InstructionPanel2;
    private javax.swing.JPanel InstructionPanel3;
    private javax.swing.JPanel InstructionPanel6;
    private javax.swing.JButton Leaderboard;
    private javax.swing.JTable Leaderboard1;
    private javax.swing.JButton Leaderboard2;
    private javax.swing.JPanel LeaderboardPanelFromInstruction;
    private javax.swing.JScrollPane LeaderboardScrollPanel1;
    private javax.swing.JPanel MainGame;
    private javax.swing.JTextField QuestionOutput;
    private javax.swing.JTextField QuestionOutput1;
    private javax.swing.JTextField QuestionOutput2;
    private javax.swing.JTextField QuestionOutput3;
    private javax.swing.JTextField QuestionOutput4;
    private javax.swing.JButton QuitButton;
    private javax.swing.JButton QuitButton1;
    private javax.swing.JButton QuitButton3;
    private javax.swing.JButton QuitButton4;
    private javax.swing.JTextField RankOutput;
    private javax.swing.JButton RestartButton;
    private javax.swing.JLabel ScoreCount;
    private javax.swing.JPanel ScreenPanel;
    private javax.swing.JPanel ScreenPanelSample;
    private javax.swing.JPanel ScreenPanelSample1;
    private javax.swing.JButton StartButton;
    // End of variables declaration//GEN-END:variables
}
