package QuickQuirkGameLab;

public class PopupWindow extends javax.swing.JFrame {

    private int x; // Needed to make application draggable
    private int y; // Needed to make application draggable
    public PopupWindow() {
        initComponents();
        this.setLocationRelativeTo(null); // Puts the application in the center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopupWindowTop = new javax.swing.JPanel();
        ClosePopup = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        SubtitleMessage = new javax.swing.JLabel();
        TitleMessage = new javax.swing.JLabel();
        OkayButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 270));

        PopupWindowTop.setBackground(new java.awt.Color(85, 143, 127));
        PopupWindowTop.setForeground(new java.awt.Color(85, 143, 127));
        PopupWindowTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PopupWindowTopMouseDragged(evt);
            }
        });
        PopupWindowTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PopupWindowTopMousePressed(evt);
            }
        });

        ClosePopup.setBackground(new java.awt.Color(242, 0, 0));
        ClosePopup.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        ClosePopup.setForeground(new java.awt.Color(255, 255, 255));
        ClosePopup.setText("x");
        ClosePopup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ClosePopupMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout PopupWindowTopLayout = new javax.swing.GroupLayout(PopupWindowTop);
        PopupWindowTop.setLayout(PopupWindowTopLayout);
        PopupWindowTopLayout.setHorizontalGroup(
            PopupWindowTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PopupWindowTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ClosePopup)
                .addGap(16, 16, 16))
        );
        PopupWindowTopLayout.setVerticalGroup(
            PopupWindowTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopupWindowTopLayout.createSequentialGroup()
                .addComponent(ClosePopup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        Background.setBackground(new java.awt.Color(25, 47, 51));

        SubtitleMessage.setBackground(new java.awt.Color(255, 255, 255));
        SubtitleMessage.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        SubtitleMessage.setForeground(new java.awt.Color(255, 255, 255));
        SubtitleMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubtitleMessage.setText("Subtitle subtitle subtitle subtitle");

        TitleMessage.setBackground(new java.awt.Color(255, 255, 255));
        TitleMessage.setFont(new java.awt.Font("Nunito", 0, 24)); // NOI18N
        TitleMessage.setForeground(new java.awt.Color(255, 255, 255));
        TitleMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleMessage.setText("Title");

        OkayButton.setBackground(new java.awt.Color(84, 129, 118));
        OkayButton.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        OkayButton.setForeground(new java.awt.Color(255, 255, 255));
        OkayButton.setText("Okay!");
        OkayButton.setBorder(null);
        OkayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SubtitleMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TitleMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(OkayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(TitleMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubtitleMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(OkayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PopupWindowTop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PopupWindowTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClosePopupMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosePopupMouseReleased
        this.dispose();
    }//GEN-LAST:event_ClosePopupMouseReleased

    private void PopupWindowTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopupWindowTopMouseDragged
        // Moves application based on cursor location
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();

        this.setLocation(x1- x, y1 - y);
    }//GEN-LAST:event_PopupWindowTopMouseDragged

    private void PopupWindowTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopupWindowTopMousePressed
        // Get current cursor location upon clicking Top
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_PopupWindowTopMousePressed

    private void OkayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkayButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_OkayButtonActionPerformed
    
    public void setMessages(String title, String subtitle){
        this.TitleMessage.setText(title);
        this.SubtitleMessage.setText(subtitle);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopupWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel ClosePopup;
    private javax.swing.JButton OkayButton;
    private javax.swing.JPanel PopupWindowTop;
    private javax.swing.JLabel SubtitleMessage;
    private javax.swing.JLabel TitleMessage;
    // End of variables declaration//GEN-END:variables
}
