
package QuickQuirkGameLab;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;


public class RegistrationPage1 extends javax.swing.JFrame {

    private int x; // Needed to make application draggable
    private int y; // Needed to make application draggable
    public RegistrationPage1() {
        initComponents();
        this.setLocationRelativeTo(null); // Puts the application in the center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FreeLearnerRegistrationTop = new javax.swing.JPanel();
        CloseApplication = new javax.swing.JLabel();
        RegistrationBody = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        Birthday_Label = new javax.swing.JLabel();
        RegistrationFirstNameInput = new javax.swing.JTextField();
        RegistrationEmailInput = new javax.swing.JTextField();
        ContinueButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        FeedbackOutput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        FreeLearnerRegistrationTop.setBackground(new java.awt.Color(85, 143, 127));
        FreeLearnerRegistrationTop.setForeground(new java.awt.Color(85, 143, 127));
        FreeLearnerRegistrationTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FreeLearnerRegistrationTopMouseDragged(evt);
            }
        });
        FreeLearnerRegistrationTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FreeLearnerRegistrationTopMousePressed(evt);
            }
        });

        CloseApplication.setBackground(new java.awt.Color(242, 0, 0));
        CloseApplication.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        CloseApplication.setForeground(new java.awt.Color(255, 255, 255));
        CloseApplication.setText("x");
        CloseApplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CloseApplicationMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout FreeLearnerRegistrationTopLayout = new javax.swing.GroupLayout(FreeLearnerRegistrationTop);
        FreeLearnerRegistrationTop.setLayout(FreeLearnerRegistrationTopLayout);
        FreeLearnerRegistrationTopLayout.setHorizontalGroup(
            FreeLearnerRegistrationTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FreeLearnerRegistrationTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseApplication)
                .addGap(16, 16, 16))
        );
        FreeLearnerRegistrationTopLayout.setVerticalGroup(
            FreeLearnerRegistrationTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FreeLearnerRegistrationTopLayout.createSequentialGroup()
                .addComponent(CloseApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        RegistrationBody.setBackground(new java.awt.Color(35, 64, 69));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up");

        FirstNameLabel.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        FirstNameLabel.setForeground(new java.awt.Color(242, 242, 242));
        FirstNameLabel.setText("Full Name");

        Birthday_Label.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        Birthday_Label.setForeground(new java.awt.Color(242, 242, 242));
        Birthday_Label.setText("Email");

        RegistrationFirstNameInput.setBackground(new java.awt.Color(74, 126, 112));
        RegistrationFirstNameInput.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        RegistrationFirstNameInput.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationFirstNameInput.setBorder(null);
        RegistrationFirstNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationFirstNameInputActionPerformed(evt);
            }
        });

        RegistrationEmailInput.setBackground(new java.awt.Color(74, 126, 112));
        RegistrationEmailInput.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        RegistrationEmailInput.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationEmailInput.setBorder(null);
        RegistrationEmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationEmailInputActionPerformed(evt);
            }
        });

        ContinueButton.setBackground(new java.awt.Color(84, 129, 118));
        ContinueButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        ContinueButton.setForeground(new java.awt.Color(255, 255, 255));
        ContinueButton.setText("Continue");
        ContinueButton.setBorderPainted(false);
        ContinueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContinueButtonMouseClicked(evt);
            }
        });
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(151, 92, 92));
        BackButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Go Back");
        BackButton.setBorderPainted(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        FeedbackOutput.setEditable(false);
        FeedbackOutput.setBackground(new java.awt.Color(35, 64, 69));
        FeedbackOutput.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        FeedbackOutput.setForeground(new java.awt.Color(255, 255, 51));
        FeedbackOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FeedbackOutput.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Join us to access our courses and to learn the way you know best!");

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Step 1 of 2");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout RegistrationBodyLayout = new javax.swing.GroupLayout(RegistrationBody);
        RegistrationBody.setLayout(RegistrationBodyLayout);
        RegistrationBodyLayout.setHorizontalGroup(
            RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FeedbackOutput, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(RegistrationBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                    .addGroup(RegistrationBodyLayout.createSequentialGroup()
                        .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistrationBodyLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Birthday_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(RegistrationFirstNameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                                        .addComponent(RegistrationEmailInput))))
                            .addGroup(RegistrationBodyLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegistrationBodyLayout.createSequentialGroup()
                                        .addGap(273, 273, 273)
                                        .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        RegistrationBodyLayout.setVerticalGroup(
            RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationBodyLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(FirstNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegistrationFirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Birthday_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegistrationEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(FeedbackOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FreeLearnerRegistrationTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(RegistrationBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FreeLearnerRegistrationTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(RegistrationBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseApplicationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseApplicationMouseReleased
        System.exit(0);
    }//GEN-LAST:event_CloseApplicationMouseReleased

    private void FreeLearnerRegistrationTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FreeLearnerRegistrationTopMouseDragged
        // Moves application based on cursor location
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();

        this.setLocation(x1- x, y1 - y);
    }//GEN-LAST:event_FreeLearnerRegistrationTopMouseDragged

    private void RegistrationFirstNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationFirstNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrationFirstNameInputActionPerformed

    private void RegistrationEmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationEmailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrationEmailInputActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        LoginPage log = new LoginPage();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ContinueButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ContinueButtonMouseClicked

    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        String fname = RegistrationFirstNameInput.getText();
        String email = RegistrationEmailInput.getText();
        
        // CSV File Path
        String filepath = "usermasterlist.csv";
        
        // Check if fields are empty
        if ((fname.isEmpty() || email.isEmpty())) {
            System.out.println("Please fill in all fields");
            FeedbackOutput.setText("Please fill in all fields");
        
        // Check if email is the correct format    
        } else if (!checkEmailValidity(email)){
            System.out.println("Invalid email format! Please enter a valid email");
            FeedbackOutput.setText("Invalid email format! Please enter a valid email");
            
        } else if (emailExists(filepath, email)) { 
            System.out.println("This email is already registered!");
            FeedbackOutput.setText("This email is already registered!");
            
        } else {
            // Next Page, pass Full Name String and Email
            
            RegistrationPage2 reg2 = new RegistrationPage2();
            reg2.setVisible(true);
            reg2.pack();
            reg2.setLocationRelativeTo(null);
            reg2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            
            reg2.getNameEmail(fname, email);
            
            // Clears variables
            fname = email =  "";
        }        
    }//GEN-LAST:event_ContinueButtonActionPerformed

    private void FreeLearnerRegistrationTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FreeLearnerRegistrationTopMousePressed
        // Get current cursor location upon clicking Top
        this.x = evt.getX();
        this.y = evt.getY();                        
    }//GEN-LAST:event_FreeLearnerRegistrationTopMousePressed

    
    // Method to check if email is in the correct format
    private boolean checkEmailValidity(String email) {
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$"; // Regex for a valid email
        return email.matches(emailRegex);
    }
    
    // Method to check if email exists
    private boolean emailExists(String filepath, String email) {
        try (BufferedReader reader = new BufferedReader(new FileReader(filepath))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] values = line.split(","); // Split CSV data
                if (values.length > 4 && values[4].equalsIgnoreCase(email)) { // Check email column
                    return true; // Email found
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return false; // Email not found
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationPage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Birthday_Label;
    private javax.swing.JLabel CloseApplication;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JTextField FeedbackOutput;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JPanel FreeLearnerRegistrationTop;
    private javax.swing.JPanel RegistrationBody;
    private javax.swing.JTextField RegistrationEmailInput;
    private javax.swing.JTextField RegistrationFirstNameInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
