// This page is unused, it is being kept in case of method copying

package QuickQuirkGameLab;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;


public class RegistrationPage extends javax.swing.JFrame {

    private int x; // Needed to make application draggable
    private int y; // Needed to make application draggable
    public RegistrationPage() {
        initComponents();
        this.setLocationRelativeTo(null); // Puts the application in the center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FreeLearnerRegistrationTop = new javax.swing.JPanel();
        CloseApplication = new javax.swing.JLabel();
        RegistrationBody = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        RegistrationUsernameLabel = new javax.swing.JLabel();
        Birthday_Label = new javax.swing.JLabel();
        RegistrationFirstNameInput = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        RegistrationLastNameInput = new javax.swing.JTextField();
        RegistrationPasswordInput = new javax.swing.JTextField();
        RegistrationEmailInput = new javax.swing.JTextField();
        LearningRoleLabel = new javax.swing.JLabel();
        RegistrationLearningRoleInput = new javax.swing.JComboBox<>();
        RegisterButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        RegistrationUsernameInput = new javax.swing.JTextField();
        IllegalSymbolsLabel = new javax.swing.JLabel();
        FeedbackOutput = new javax.swing.JTextField();
        UsernameNotice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        FreeLearnerRegistrationTop.setBackground(new java.awt.Color(85, 143, 127));
        FreeLearnerRegistrationTop.setForeground(new java.awt.Color(85, 143, 127));
        FreeLearnerRegistrationTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FreeLearnerRegistrationTopMouseDragged(evt);
            }
        });
        FreeLearnerRegistrationTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FreeLearnerRegistrationTopMousePressed(evt);
            }
        });

        CloseApplication.setBackground(new java.awt.Color(242, 0, 0));
        CloseApplication.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        CloseApplication.setForeground(new java.awt.Color(255, 255, 255));
        CloseApplication.setText("x");
        CloseApplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CloseApplicationMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout FreeLearnerRegistrationTopLayout = new javax.swing.GroupLayout(FreeLearnerRegistrationTop);
        FreeLearnerRegistrationTop.setLayout(FreeLearnerRegistrationTopLayout);
        FreeLearnerRegistrationTopLayout.setHorizontalGroup(
            FreeLearnerRegistrationTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FreeLearnerRegistrationTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseApplication)
                .addGap(16, 16, 16))
        );
        FreeLearnerRegistrationTopLayout.setVerticalGroup(
            FreeLearnerRegistrationTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FreeLearnerRegistrationTopLayout.createSequentialGroup()
                .addComponent(CloseApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        RegistrationBody.setBackground(new java.awt.Color(35, 64, 69));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QuickQuirk GameLab Registration");

        FirstNameLabel.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        FirstNameLabel.setForeground(new java.awt.Color(242, 242, 242));
        FirstNameLabel.setText("First Name");

        LastNameLabel.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        LastNameLabel.setForeground(new java.awt.Color(242, 242, 242));
        LastNameLabel.setText("Last Name");

        RegistrationUsernameLabel.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        RegistrationUsernameLabel.setForeground(new java.awt.Color(242, 242, 242));
        RegistrationUsernameLabel.setText("Username");

        Birthday_Label.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        Birthday_Label.setForeground(new java.awt.Color(242, 242, 242));
        Birthday_Label.setText("Email");

        RegistrationFirstNameInput.setBackground(new java.awt.Color(74, 126, 112));
        RegistrationFirstNameInput.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        RegistrationFirstNameInput.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationFirstNameInput.setBorder(null);
        RegistrationFirstNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationFirstNameInputActionPerformed(evt);
            }
        });

        PasswordLabel.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(242, 242, 242));
        PasswordLabel.setText("Password");

        RegistrationLastNameInput.setBackground(new java.awt.Color(74, 126, 112));
        RegistrationLastNameInput.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        RegistrationLastNameInput.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationLastNameInput.setBorder(null);
        RegistrationLastNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationLastNameInputActionPerformed(evt);
            }
        });

        RegistrationPasswordInput.setBackground(new java.awt.Color(74, 126, 112));
        RegistrationPasswordInput.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        RegistrationPasswordInput.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationPasswordInput.setBorder(null);
        RegistrationPasswordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationPasswordInputActionPerformed(evt);
            }
        });

        RegistrationEmailInput.setBackground(new java.awt.Color(74, 126, 112));
        RegistrationEmailInput.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        RegistrationEmailInput.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationEmailInput.setBorder(null);
        RegistrationEmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationEmailInputActionPerformed(evt);
            }
        });

        LearningRoleLabel.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        LearningRoleLabel.setForeground(new java.awt.Color(242, 242, 242));
        LearningRoleLabel.setText("Learning Role");

        RegistrationLearningRoleInput.setBackground(new java.awt.Color(74, 126, 112));
        RegistrationLearningRoleInput.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        RegistrationLearningRoleInput.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationLearningRoleInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Learner", "Educator" }));
        RegistrationLearningRoleInput.setBorder(null);

        RegisterButton.setBackground(new java.awt.Color(84, 129, 118));
        RegisterButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Register");
        RegisterButton.setBorderPainted(false);
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseClicked(evt);
            }
        });
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(151, 92, 92));
        BackButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Go Back");
        BackButton.setBorderPainted(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        RegistrationUsernameInput.setBackground(new java.awt.Color(74, 126, 112));
        RegistrationUsernameInput.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        RegistrationUsernameInput.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationUsernameInput.setBorder(null);
        RegistrationUsernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationUsernameInputActionPerformed(evt);
            }
        });

        IllegalSymbolsLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        IllegalSymbolsLabel.setForeground(new java.awt.Color(255, 204, 204));
        IllegalSymbolsLabel.setText("Illegal Symbols: ,  \\  \"  ;  #  =  +");

        FeedbackOutput.setEditable(false);
        FeedbackOutput.setBackground(new java.awt.Color(35, 64, 69));
        FeedbackOutput.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        FeedbackOutput.setForeground(new java.awt.Color(255, 255, 51));
        FeedbackOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FeedbackOutput.setBorder(null);

        UsernameNotice.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        UsernameNotice.setForeground(new java.awt.Color(255, 204, 204));
        UsernameNotice.setText("Username cannot be changed later");

        javax.swing.GroupLayout RegistrationBodyLayout = new javax.swing.GroupLayout(RegistrationBody);
        RegistrationBody.setLayout(RegistrationBodyLayout);
        RegistrationBodyLayout.setHorizontalGroup(
            RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(RegistrationBodyLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(RegistrationBodyLayout.createSequentialGroup()
                            .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(RegistrationBodyLayout.createSequentialGroup()
                            .addComponent(LearningRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RegistrationLearningRoleInput, 0, 155, Short.MAX_VALUE)))
                    .addGroup(RegistrationBodyLayout.createSequentialGroup()
                        .addComponent(Birthday_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RegistrationEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistrationBodyLayout.createSequentialGroup()
                        .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegistrationUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistrationBodyLayout.createSequentialGroup()
                                .addComponent(RegistrationPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IllegalSymbolsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistrationBodyLayout.createSequentialGroup()
                                .addComponent(RegistrationUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UsernameNotice, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(RegistrationLastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegistrationFirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(FeedbackOutput, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        RegistrationBodyLayout.setVerticalGroup(
            RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationBodyLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationBodyLayout.createSequentialGroup()
                        .addComponent(FirstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegistrationLastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(RegistrationFirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegistrationUsernameLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RegistrationUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UsernameNotice)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(RegistrationPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IllegalSymbolsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Birthday_Label)
                    .addComponent(RegistrationEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LearningRoleLabel)
                    .addComponent(RegistrationLearningRoleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(RegistrationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(FeedbackOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FreeLearnerRegistrationTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(RegistrationBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FreeLearnerRegistrationTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(RegistrationBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseApplicationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseApplicationMouseReleased
        System.exit(0);
    }//GEN-LAST:event_CloseApplicationMouseReleased

    private void FreeLearnerRegistrationTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FreeLearnerRegistrationTopMouseDragged
        // Moves application based on cursor location
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();

        this.setLocation(x1- x, y1 - y);
    }//GEN-LAST:event_FreeLearnerRegistrationTopMouseDragged

    private void RegistrationFirstNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationFirstNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrationFirstNameInputActionPerformed

    private void RegistrationLastNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationLastNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrationLastNameInputActionPerformed

    private void RegistrationPasswordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationPasswordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrationPasswordInputActionPerformed

    private void RegistrationEmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationEmailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrationEmailInputActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        LoginPage log = new LoginPage();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void RegistrationUsernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationUsernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrationUsernameInputActionPerformed

    private void RegisterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterButtonMouseClicked

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        String fname = RegistrationFirstNameInput.getText();
        String lname = RegistrationLastNameInput.getText();
        String uname = RegistrationUsernameInput.getText();
        String pass = RegistrationPasswordInput.getText();
        String email = RegistrationEmailInput.getText();
        String role = (String) RegistrationLearningRoleInput.getSelectedItem();
        
        // CSV File Path
        String filepath = "usermasterlist.csv";
        
        // Check if fields are empty
        if ((fname.isEmpty() || lname.isEmpty() || uname.isEmpty() || pass.isEmpty() || email.isEmpty())) {
            System.out.println("Please fill in all fields");
            FeedbackOutput.setText("Please fill in all fields");
        
        // Check if username exists  
        } else if (checkExistingUsername(filepath, uname)) { 
            System.out.println("Username already exists!");
            FeedbackOutput.setText("Username already exists!");
        
        // Check if password contains restricted symbols
        } else if (checkRestrictedSymbols(pass)){ 
            System.out.println("Password contains invalid symbols!");
            FeedbackOutput.setText("Password contains invalid symbols.");
        
        // Check if email is the correct format    
        } else if (!checkEmailValidity(email)){
            System.out.println("Invalid email format! Please enter a valid email");
            FeedbackOutput.setText("Invalid email format! Please enter a valid email");
            
        } else if (emailExists(filepath, email)) { 
            System.out.println("This email is already registered!");
            FeedbackOutput.setText("This email is already registered!");
            
        } else {
            // Everything is valid and writes to CSV file
            try (FileWriter writer = new FileWriter(filepath, true)) {
                String line = fname + "," + lname + "," + uname + "," + pass + "," + email + "," + role + "\n";
                writer.write(line);
                System.out.println("Data saved successfully!");
                FeedbackOutput.setText("You have been registered successfully");
                
                // Clear text fields
                RegistrationFirstNameInput.setText("");
                RegistrationLastNameInput.setText("");
                RegistrationUsernameInput.setText("");
                RegistrationPasswordInput.setText("");
                RegistrationEmailInput.setText("");
                RegistrationLearningRoleInput.setSelectedIndex(0); // Reset JComboBox to default

            } catch (IOException e) {
                e.printStackTrace();
                System.out.println("Error writing to CSV file.");
                
            }
            
            // Creates a folder for Learner and Educator
            File learnerFolder = new File("Learner");
            File educatorFolder = new File("Educator");
            
            // If folders are missing, they are created
            if(!learnerFolder.exists()) learnerFolder.mkdirs();
            if(!educatorFolder.exists()) educatorFolder.mkdirs();
            
            // Creates user's personal folder
            if(role.equals("Learner")) {
                System.out.println("Creating Learner Folders"); //Debugging statement
                File learnerUser = new File("Learner/" + uname);
                learnerUser.mkdirs();
                
                // Creates a CSV file to store purchased icons
                File learnerCSV = new File("Learner/" + uname + "/inventory.csv");
                try {
                    learnerCSV.createNewFile();
                } catch (IOException e){
                    e.printStackTrace();
                }
                
                // Creates a file to hold account details
                File accountDetails = new File("Learner/" + uname + "/accountDetails.csv");
                try {
                    accountDetails.createNewFile();
                    
                    // Write to the file
                    FileWriter writer = new FileWriter(accountDetails);
                    
                    // Write each piece of data on a new line
                    writer.write(fname + "\n");
                    writer.write(lname + "\n");
                    writer.write(uname + "\n");
                    writer.write(pass + "\n");
                    writer.write(email + "\n");
                    writer.write("300\n"); // coins
                    writer.write("DefaultIcon1\n"); // equipped icon

                    writer.close();

                    System.out.println("Account details created successfully "); // Debug
                    
                } catch (IOException e){
                    e.printStackTrace();
                }
                
            } else if (role.equals("Educator")){
                System.out.println("Creating Educator Folders"); //Debugging Statement
                File educatorUser = new File ("Educator/" + uname + "/Classrooms");
                educatorUser.mkdirs();
            }
            
            // Clears variables
            fname = lname = uname = pass = email = role = "";
        }        
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void FreeLearnerRegistrationTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FreeLearnerRegistrationTopMousePressed
        // Get current cursor location upon clicking Top
        this.x = evt.getX();
        this.y = evt.getY();                        
    }//GEN-LAST:event_FreeLearnerRegistrationTopMousePressed
    
    // Method to check if username exists
    private boolean checkExistingUsername(String filepath, String username) {
        try (Scanner scanner = new Scanner(new File(filepath))) {
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                String[] values = line.split(","); 

                if (values.length > 2) { // Ensure username column exists
                    if (values[2].equals(username)) { // Compare usernames
                        return true; // Username exists
                    }
                }
            }
        } catch (FileNotFoundException e) {
            System.out.println("File not found. Creating a new one.");
        }
        return false; // Username missing
    }
    
    // Method to check if password contains restricted symbols
    private boolean checkRestrictedSymbols(String password) {
        String restrictedSymbols = ",\";#=+\\\\"; 
        for (char c : restrictedSymbols.toCharArray()) {
            if (password.indexOf(c) != -1) {
            return true; // Found a restricted symbol
            }
        }
        return false; // Password is safe
    }
    
    // Method to check if email is in the correct format
    private boolean checkEmailValidity(String email) {
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$"; // Regex for a valid email
        return email.matches(emailRegex);
    }
    
    // Method to check if email exists
    private boolean emailExists(String filepath, String email) {
        try (BufferedReader reader = new BufferedReader(new FileReader(filepath))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] values = line.split(","); // Split CSV data
                if (values.length > 4 && values[4].equalsIgnoreCase(email)) { // Check email column
                    return true; // Email found
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return false; // Email not found
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Birthday_Label;
    private javax.swing.JLabel CloseApplication;
    private javax.swing.JTextField FeedbackOutput;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JPanel FreeLearnerRegistrationTop;
    private javax.swing.JLabel IllegalSymbolsLabel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel LearningRoleLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JPanel RegistrationBody;
    private javax.swing.JTextField RegistrationEmailInput;
    private javax.swing.JTextField RegistrationFirstNameInput;
    private javax.swing.JTextField RegistrationLastNameInput;
    private javax.swing.JComboBox<String> RegistrationLearningRoleInput;
    private javax.swing.JTextField RegistrationPasswordInput;
    private javax.swing.JTextField RegistrationUsernameInput;
    private javax.swing.JLabel RegistrationUsernameLabel;
    private javax.swing.JLabel UsernameNotice;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
